"use client";

import { useActionState, useEffect, useMemo, useState, type ReactNode } from "react";
import Image from "next/image";
import type { Session } from "@supabase/supabase-js";
import { submitConsumerJob as submitConsumerJobServer } from "@/app/post-job/actions";
import { getJob, getService, marketplaceServices, type MarketplaceJob, type PricingQuestion } from "@/app/data/marketplace";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import { UK_POSTCODE_PATTERN } from "@/lib/uk-address";

type Props = { initialService?: string; initialPostcode?: string; initialLocation?: string; initialJob?: string; error?: string; onStarted?: () => void };
type Step = 1 | 2 | 3 | 4;
const input = "mt-2 min-h-12 w-full rounded-xl border border-[#dfe5ee] bg-white px-4 py-3 text-[15px] font-semibold text-[#061b3f] outline-none focus:border-[#23a955] focus:ring-4 focus:ring-[#e9f9ee]";
const featured = ["cleaning", "gardening", "handyman", "plumbing", "electrical", "removals", "furniture-assembly", "painting"];
const servicePickerIcons: Record<string, string> = {
  cleaning: "/icons/services/cleaning.svg",
  gardening: "/icons/services/gardening.svg",
  handyman: "/icons/services/handyman.svg",
  "furniture-assembly": "/icons/services/assembly.svg",
  plumbing: "/icons/services/plumbing.svg",
  electrical: "/icons/services/electrical.svg",
  removals: "/icons/services/moving.svg",
  painting: "/icons/services/painting.svg",
};
const locationIds = ["postcode", "when", "date", "fromPostcode", "toPostcode"];
function answersForJob(current: Record<string, string | number>, nextJob: MarketplaceJob | undefined) {
  return {
    ...Object.fromEntries(Object.entries(current).filter(([key]) => nextJob?.pricingQuestions.some((question) => question.id === key) || locationIds.includes(key))),
    ...(nextJob?.inferredAnswers || {}),
    ...Object.fromEntries((nextJob?.pricingQuestions || []).filter((question) => question.type === "counter" && current[question.id] === undefined && nextJob?.inferredAnswers?.[question.id] === undefined).map((question) => [question.id, question.id === "bedrooms" ? 1 : 0])),
  };
}

export default function ConsumerJobComposer({ initialService = "", initialPostcode = "", initialLocation = "", initialJob = "", error = "", onStarted }: Props) {
  const [categorySlug, setCategorySlug] = useState(initialService);
  const [jobSlug, setJobSlug] = useState(initialJob);
  const [answers, setAnswers] = useState<Record<string, string | number>>(() => answersForJob(initialPostcode ? { postcode: initialPostcode } : {}, getJob(initialService, initialJob)));
  const [moreOpen, setMoreOpen] = useState(false);
  const [note, setNote] = useState("");
  const [noteOpen, setNoteOpen] = useState(false);
  const [budgetMode, setBudgetMode] = useState<"open" | "set">("open");
  const [budget, setBudget] = useState("");
  const [contactOpen, setContactOpen] = useState(false);
  const [mobileStep, setMobileStep] = useState<Step>(initialJob ? 2 : 1);
  const [submissionKey] = useState(() => crypto.randomUUID());
  const [submissionState, action, pending] = useActionState(submitConsumerJobServer, { message: "" });
  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    const auth = createSupabaseBrowserClient();
    void auth.auth.getSession().then((result: { data: { session: Session | null } }) => setAuthenticated(Boolean(result.data.session))).catch(() => setAuthenticated(false));
  }, []);

  const service = getService(categorySlug);
  const activeJobSlug = jobSlug || (typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("job") || "" : "");
  const selectedJob = getJob(categorySlug, activeJobSlug);
  const questions = useMemo(() => selectedJob?.pricingQuestions.filter((question) => !question.showWhen || question.showWhen.values.includes(String(answers[question.showWhen.question] || ""))) || [], [selectedJob, answers]);
  const firstIncomplete = questions.findIndex((question) => question.required && !hasAnswer(question, answers));
  const ready = Boolean(selectedJob && firstIncomplete === -1);
  const detailQuestions = questions.filter((question) => !locationIds.includes(question.id));
  const locationQuestions = questions.filter((question) => locationIds.includes(question.id));
  const detailReady = detailQuestions.every((question) => !question.required || hasAnswer(question, answers));
  const locationReady = locationQuestions.every((question) => !question.required || hasAnswer(question, answers));
  const setAnswer = (id: string, value: string | number) => setAnswers((current) => ({ ...current, [id]: value }));
  const preserveSharedAnswers = (current: Record<string, string | number>) => Object.fromEntries(Object.entries(current).filter(([key]) => locationIds.includes(key)));
  const reset = () => { setCategorySlug(""); setJobSlug(""); setMobileStep(1); };
  const selectJob = (slug: string) => {
    const nextJob = getJob(categorySlug, slug);
    setJobSlug(slug);
    setAnswers((current) => answersForJob(current, nextJob));
    setMobileStep(2);
    onStarted?.();
  };

  return <div id="job-composer" className="relative z-30 scroll-mt-24 rounded-[24px] bg-white p-4 pt-3 text-[#061b3f] shadow-[0_22px_60px_rgba(0,0,0,.24)] md:rounded-[28px] md:p-6 lg:border lg:border-[#e6ebef] lg:p-7 lg:pt-6">
    {selectedJob && <div className="hidden md:block"><DesktopProgress step={2} /></div>}
    <div className="mb-2 md:hidden"><MobileProgress step={selectedJob ? mobileStep : 1} /></div>
    <div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#159548]">Your service</p><h2 className="mt-0.5 text-xl font-black tracking-[-.03em]">{selectedJob ? `${selectedJob.name} ✓` : service ? service.name : "What do you need?"}</h2></div>{(service || selectedJob) && <button type="button" onClick={reset} className="min-h-10 rounded-xl px-3 text-sm font-black text-[#526078] hover:bg-[#eef8f1]">Change</button>}</div>
    {error && <p role="alert" className="mt-3 rounded-xl bg-[#fff3e7] p-3 text-base font-bold text-[#974c00]">{error}</p>}
    {!service ? <CategoryPicker moreOpen={moreOpen} onMore={() => setMoreOpen((value) => !value)} onSelect={(slug) => { setCategorySlug(slug); setJobSlug(""); setMobileStep(1); setAnswers((current) => preserveSharedAnswers(current)); }} /> : !selectedJob ? <JobPicker service={service} onSelect={selectJob} /> : <>
      <div className="mt-4 md:hidden"><MobileStepForm step={mobileStep} selectedJob={selectedJob} detailQuestions={detailQuestions} locationQuestions={locationQuestions} answers={answers} detailReady={detailReady} locationReady={locationReady} ready={ready} budgetMode={budgetMode} budget={budget} note={note} noteOpen={noteOpen} setAnswer={setAnswer} setStep={setMobileStep} setBudgetMode={setBudgetMode} setBudget={setBudget} setNote={setNote} setNoteOpen={setNoteOpen} onPost={() => setContactOpen(true)} /></div>
      <div className="mt-4 hidden md:block"><DesktopForm questions={questions} answers={answers} setAnswer={setAnswer} budgetMode={budgetMode} budget={budget} setBudgetMode={setBudgetMode} setBudget={setBudget} note={note} noteOpen={noteOpen} setNote={setNote} setNoteOpen={setNoteOpen} ready={ready} onPost={() => setContactOpen(true)} /></div>
    </>}
    {contactOpen && <ContactSheet authenticated={authenticated} submissionKey={submissionKey} pending={pending} message={submissionState.message} category={categorySlug} job={selectedJob} answers={answers} note={note} budget={budgetMode === "set" ? budget : ""} location={initialLocation} action={action} onClose={() => setContactOpen(false)} />}
  </div>;
}

type MarketplaceProgressStep = 1 | 2 | 3;
function getMarketplaceProgressStep(step: number): MarketplaceProgressStep { const normalized = Math.min(4, Math.max(1, Math.trunc(step))); return normalized <= 1 ? 1 : normalized >= 4 ? 3 : 2; }
function MobileProgress({ step }: { step: number }) { const displayStep = getMarketplaceProgressStep(step); const labels: Record<MarketplaceProgressStep, string> = { 1: "Service", 2: "Job details", 3: "Get quotes" }; return <div aria-label={`Step ${displayStep} of 3`}><p className="text-center text-sm font-black text-[#061b3f]">Step {displayStep} of 3 · {labels[displayStep]}</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-[#dce4ea]"><div className="h-full rounded-full bg-[#23a955]" style={{ width: `${(displayStep / 3) * 100}%` }} /></div></div>; }
function DesktopProgress({ step }: { step: 1 | 2 | 3 }) { return <div className="mb-3 flex items-center gap-5 border-b border-[#eef1f3] pb-3" aria-label={`Step ${step} of 3`}>{["Service", "Job details", "Get quotes"].map((label, index) => { const number = index + 1; return <div key={label} className={`flex items-center gap-1.5 text-xs font-black ${number <= step ? "text-[#159548]" : "text-[#91a0b1]"}`}>{number < step ? "✓" : number} {label}</div>; })}<div className="h-1 flex-1 overflow-hidden rounded-full bg-[#dce4ea]"><div className="h-full bg-[#23a955]" style={{ width: `${((step - 1) / 2) * 100}%` }} /></div></div>; }

function MobileStepForm({ step, selectedJob, detailQuestions, locationQuestions, answers, detailReady, locationReady, ready, budgetMode, budget, note, noteOpen, setAnswer, setStep, setBudgetMode, setBudget, setNote, setNoteOpen, onPost }: { step: Step; selectedJob: MarketplaceJob; detailQuestions: PricingQuestion[]; locationQuestions: PricingQuestion[]; answers: Record<string, string | number>; detailReady: boolean; locationReady: boolean; ready: boolean; budgetMode: "open" | "set"; budget: string; note: string; noteOpen: boolean; setAnswer: (id: string, value: string | number) => void; setStep: (step: Step) => void; setBudgetMode: (mode: "open" | "set") => void; setBudget: (value: string) => void; setNote: (value: string) => void; setNoteOpen: (value: boolean) => void; onPost: () => void }) {
  if (step === 2) return <StepPanel title="Job details"><div className="grid gap-1">{detailQuestions.map((question) => <Question key={question.id} question={question} value={answers[question.id]} active onChange={(value) => setAnswer(question.id, value)} />)}</div><button type="button" disabled={!detailReady} onClick={() => setStep(3)} className="mt-5 min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-base font-black disabled:opacity-40">Continue</button></StepPanel>;
  if (step === 3) return <StepPanel title="Where & when"><div className="grid gap-1">{locationQuestions.map((question) => <Question key={question.id} question={question} value={answers[question.id]} active onChange={(value) => setAnswer(question.id, value)} />)}</div><div className="mt-5 flex gap-2"><button type="button" onClick={() => setStep(2)} className="min-h-12 flex-1 rounded-xl border border-[#dfe5ee] px-4 text-base font-black">Back</button><button type="button" disabled={!locationReady} onClick={() => setStep(4)} className="min-h-12 flex-1 rounded-xl bg-[#23dc63] px-4 text-base font-black disabled:opacity-40">Continue</button></div></StepPanel>;
  if (step === 4) return <StepPanel title="Budget & post"><BudgetChoice mode={budgetMode} value={budget} onModeChange={setBudgetMode} onChange={setBudget} /><button type="button" onClick={() => setNoteOpen(!noteOpen)} className="mt-3 min-h-11 text-left text-base font-black text-[#167d3c]">{noteOpen ? "− Hide note" : "+ Add a note"} <span className="font-normal text-[#707b8d]">(optional)</span></button>{noteOpen && <textarea value={note} onChange={(event) => setNote(event.target.value)} rows={2} placeholder="Anything else we should know? (optional)" className={input} />}<div className="mt-5 flex gap-2"><button type="button" onClick={() => setStep(3)} className="min-h-12 flex-1 rounded-xl border border-[#dfe5ee] px-4 text-base font-black">Back</button><button type="button" disabled={!ready || (budgetMode === "set" && !budget)} onClick={onPost} className="min-h-12 flex-1 rounded-xl bg-[#23dc63] px-4 text-base font-black disabled:opacity-40">Post what you need</button></div></StepPanel>;
  return <StepPanel title={selectedJob.name}><p className="text-sm text-[#707b8d]">Your service is selected. Continue to add the details people need to send an offer.</p><button type="button" onClick={() => setStep(2)} className="mt-5 min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-base font-black">Start job details</button></StepPanel>;
}

function StepPanel({ title, children }: { title: string; children: ReactNode }) { return <section><h3 className="text-lg font-black tracking-[-.02em]">{title}</h3>{children}</section>; }
function DesktopForm({ questions, answers, setAnswer, budgetMode, budget, setBudgetMode, setBudget, note, noteOpen, setNote, setNoteOpen, ready, onPost }: { questions: PricingQuestion[]; answers: Record<string, string | number>; setAnswer: (id: string, value: string | number) => void; budgetMode: "open" | "set"; budget: string; setBudgetMode: (mode: "open" | "set") => void; setBudget: (value: string) => void; note: string; noteOpen: boolean; setNote: (value: string) => void; setNoteOpen: (value: boolean) => void; ready: boolean; onPost: () => void }) { const details = questions.filter((question) => !locationIds.includes(question.id)); const location = questions.filter((question) => locationIds.includes(question.id)); return <><div className="grid gap-6 lg:grid-cols-2 lg:gap-8"><section id="job-details-section"><h3 className="text-base font-black tracking-[-.02em]">{details.some((question) => question.id === "bedrooms") ? "Tell us about your home" : "Tell us about your job"}</h3><div className="grid gap-1 lg:grid-cols-2 lg:gap-2">{details.map((question) => <Question key={question.id} question={question} value={answers[question.id]} active onChange={(value) => setAnswer(question.id, value)} />)}</div></section><section id="job-location-section" className="border-t border-[#e6ebef] pt-5 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><h3 className="text-base font-black tracking-[-.02em]">Location &amp; timing</h3>{location.map((question) => <Question key={question.id} question={question} value={answers[question.id]} active onChange={(value) => setAnswer(question.id, value)} />)}</section></div><section id="job-review-section" className="mt-6 border-t border-[#e6ebef] pt-5"><h3 className="text-base font-black tracking-[-.02em]">Price &amp; extras</h3><BudgetChoice mode={budgetMode} value={budget} onModeChange={setBudgetMode} onChange={setBudget} /><button type="button" onClick={() => setNoteOpen(!noteOpen)} className="mt-2 min-h-10 text-left text-sm font-black text-[#167d3c]">{noteOpen ? "− Hide note" : "+ Add a note"} <span className="font-normal text-[#707b8d]">(optional)</span></button>{noteOpen && <textarea value={note} onChange={(event) => setNote(event.target.value)} rows={2} placeholder="Anything else we should know? (optional)" className={input} />}<button type="button" disabled={!ready || (budgetMode === "set" && !budget)} onClick={onPost} className="mt-3 min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-base font-black disabled:opacity-40">Post what you need</button></section></>; }
function CategoryPicker({ moreOpen, onMore, onSelect }: { moreOpen: boolean; onMore: () => void; onSelect: (slug: string) => void }) { const services = moreOpen ? marketplaceServices : marketplaceServices.filter((item) => featured.includes(item.slug)); return <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-3 lg:gap-4">{services.map((item) => <button type="button" key={item.slug} onClick={() => onSelect(item.slug)} aria-label={`Choose ${item.shortName}`} className="flex h-16 min-h-16 items-center justify-center gap-1.5 rounded-2xl border border-[#e3e8ef] px-2 text-base font-black text-[#061b3f] hover:border-[#23a955] hover:bg-[#eef8f1] md:h-auto md:min-h-12 md:rounded-xl lg:h-[72px] lg:min-h-[72px] lg:gap-3 lg:rounded-[15px] lg:text-[18px]"><span className="grid h-[38px] w-[38px] shrink-0 place-items-center md:h-10 md:w-10"><Image src={servicePickerIcons[item.slug] || item.image} alt="" width={40} height={40} className="h-full w-full object-contain" /></span>{item.shortName}</button>)}<button type="button" onClick={onMore} className="col-span-2 h-16 min-h-16 rounded-2xl border border-dashed border-[#b8c4bd] px-2 text-base font-black text-[#167d3c] hover:bg-[#eef8f1] md:col-span-1 md:h-auto md:min-h-12 md:rounded-xl lg:col-span-1 lg:h-[72px] lg:min-h-[72px] lg:rounded-[15px] lg:text-[18px]">{moreOpen ? "Fewer" : "More services"}</button></div>; }
function JobPicker({ service, onSelect }: { service: NonNullable<ReturnType<typeof getService>>; onSelect: (slug: string) => void }) { return <div className="mt-4"><p className="text-base font-black">What needs doing?</p><div className="mt-2 grid gap-2 md:grid-cols-2">{service.jobs.filter((item) => item.active).map((item) => <button type="button" key={item.slug} onClick={() => onSelect(item.slug)} className="min-h-11 rounded-xl border border-[#e6ebef] px-3 text-left text-base font-black hover:border-[#23a955] hover:bg-[#eef8f1]">{item.name}</button>)}</div></div>; }
function hasAnswer(question: PricingQuestion, answers: Record<string, string | number>) { const value = answers[question.id]; if (question.type === "postcode") return UK_POSTCODE_PATTERN.test(String(value || "")); return value !== undefined && value !== "" && value !== 0; }
function BudgetChoice({ mode, value, onModeChange, onChange }: { mode: "open" | "set"; value: string; onModeChange: (mode: "open" | "set") => void; onChange: (value: string) => void }) { return <fieldset className="mt-4 rounded-xl border border-[#e6ebef] p-2.5"><legend className="px-1 text-sm font-black">Budget <span className="font-normal text-[#707b8d]">(optional)</span></legend><div className="mt-0.5 grid gap-1 text-sm font-semibold"><label className="flex min-h-9 items-center gap-2"><input type="radio" name="budget-choice" checked={mode === "open"} onChange={() => onModeChange("open")} />Open to offers</label><label className="flex min-h-9 items-center gap-2"><input type="radio" name="budget-choice" checked={mode === "set"} onChange={() => onModeChange("set")} />I have a budget</label></div><p className="mt-1 text-xs text-[#707b8d]">{mode === "open" ? "You’ll see prices before choosing anyone." : "People can still send their own price."}</p>{mode === "set" && <label className="mt-2 block text-sm font-black">£ <input value={value} onChange={(event) => onChange(event.target.value)} inputMode="decimal" type="number" min="1" max="100000" step="0.01" placeholder="150" className="ml-1 min-h-10 w-40 rounded-xl border border-[#dfe5ee] bg-white px-3 font-semibold outline-none focus:border-[#23a955]" /></label>}</fieldset>; }
function Question({ question, value, active, onChange }: { question: PricingQuestion; value?: string | number; active: boolean; onChange: (value: string | number) => void }) { if (!active) return null; const label = question.id === "postcode" ? "Postcode" : question.id === "when" ? "When?" : question.label; if (question.type === "postcode") { const postcode = String(value || ""); const invalid = postcode.replace(/\s/g, "").length >= 5 && !UK_POSTCODE_PATTERN.test(postcode); return <label className="mt-3 block text-base font-black">{label}<input value={postcode} onChange={(event) => onChange(event.target.value.toUpperCase())} placeholder={question.placeholder} aria-invalid={invalid} aria-describedby={invalid ? "postcode-format-help" : undefined} className={`${input} ${invalid ? "border-red-300 focus:border-red-500 focus:ring-red-100" : ""}`} />{invalid && <span id="postcode-format-help" className="mt-1 block text-xs font-semibold text-red-700">Enter a valid UK postcode, e.g. SL1 3BD.</span>}</label>; } if (question.type === "counter") return <div className="mt-2 flex min-h-[48px] items-center justify-between rounded-xl border border-[#e6ebef] px-3"><span className="text-base font-black">{label}</span><div className="flex items-center gap-2"><button type="button" onClick={() => onChange(Math.max(0, Number(value || 0) - 1))} aria-label={`Decrease ${label}`} className="grid h-9 w-9 place-items-center rounded-full bg-[#f0f3f6] text-lg font-black">−</button><span className="w-5 text-center font-black">{value || 0}</span><button type="button" onClick={() => onChange(Number(value || 0) + 1)} aria-label={`Increase ${label}`} className="grid h-9 w-9 place-items-center rounded-full bg-[#061b3f] text-lg font-black text-white">+</button></div></div>; if (question.type === "date") return <label className="mt-3 block text-base font-black">{label}<input type="date" value={String(value || "")} onChange={(event) => onChange(event.target.value)} className={input} /></label>; const helper = question.id === "wasteRemoval" ? "We’ll take garden waste away with us." : ""; return <div className="mt-3"><p className="text-base font-black">{label}</p>{helper && <p className="mt-0.5 text-xs font-semibold text-[#7b8796]">{helper}</p>}<div className="mt-1.5 flex flex-wrap gap-2">{(question.options || []).map((option) => <button type="button" key={option} onClick={() => onChange(option)} className={`min-h-10 rounded-xl border px-3.5 py-1.5 text-sm font-black ${value === option ? "border-[#23a955] bg-[#eef8f1] text-[#167d3c]" : "border-[#e6ebef]"}`}>{option}</button>)}</div></div>; }
function ContactSheet({ authenticated, submissionKey, pending, message, category, job, answers, note, budget, location, action, onClose }: { authenticated: boolean; submissionKey: string; pending: boolean; message: string; category: string; job: MarketplaceJob | undefined; answers: Record<string, string | number>; note: string; budget: string; location: string; action: (formData: FormData) => void; onClose: () => void }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#061b3f]/55 p-3"><div role="dialog" aria-modal="true" className="relative w-full max-w-md rounded-3xl bg-white p-5 text-[#061b3f] shadow-2xl sm:p-7"><button type="button" onClick={onClose} aria-label="Close" className="absolute right-4 top-3 grid h-9 w-9 place-items-center rounded-full text-2xl leading-none text-[#707b8d] hover:bg-[#f3f6f4]">×</button><h2 className="pr-10 text-2xl font-black">{authenticated ? "Post your job" : "You" + "'re ready to get quotes"}</h2><p className="mt-2 pr-4 text-sm leading-5 text-[#707b8d]">{authenticated ? "Your job will be posted immediately and local people who can help can send private offers." : "Your job details are saved. Sign in to post your job and start receiving offers."}</p>{message && <p role="alert" className="mt-4 rounded-xl bg-[#fff3e7] p-3 text-sm font-bold text-[#974c00]">{message}</p>}<form action={action} className="mt-5"><input type="hidden" name="submissionKey" value={submissionKey} /><input type="hidden" name="category" value={category} /><input type="hidden" name="service" value={job?.slug || ""} /><input type="hidden" name="answers" value={JSON.stringify(answers)} /><input type="hidden" name="postcode" value={String(answers.postcode || answers.fromPostcode || "")} /><input type="hidden" name="when" value={String(answers.when || answers.date || "")} /><input type="hidden" name="budget" value={budget} /><input type="hidden" name="description" value={note} /><input type="hidden" name="location" value={location} /><button disabled={pending} className="min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-sm font-black disabled:opacity-60">{pending ? "Posting your job…" : "Post job & get quotes"}</button></form>{!authenticated && <p className="mt-2 text-center text-xs text-[#707b8d]">Your job won&apos;t be lost.</p>}</div></div>; }
