"use client";

import { useActionState, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { submitConsumerJob as submitConsumerJobServer } from "@/app/post-job/actions";
import { getJob, getService, marketplaceServices, type MarketplaceJob, type PricingQuestion } from "@/app/data/marketplace";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Props = { initialService?: string; initialPostcode?: string; initialLocation?: string; initialJob?: string; error?: string };
const input = "mt-2 min-h-12 w-full rounded-xl border border-[#dfe5ee] bg-white px-4 py-3 text-[15px] font-semibold text-[#061b3f] outline-none focus:border-[#23a955] focus:ring-4 focus:ring-[#e9f9ee]";
const featured = ["cleaning", "gardening", "handyman", "plumbing", "electrical", "removals", "furniture-assembly", "painting"];

export default function ConsumerJobComposer({ initialService = "", initialPostcode = "", initialLocation = "", initialJob = "", error = "" }: Props) {
  const [categorySlug, setCategorySlug] = useState(initialService); const [jobSlug, setJobSlug] = useState(initialJob); const [answers, setAnswers] = useState<Record<string, string | number>>(initialPostcode ? { postcode: initialPostcode } : {}); const [moreOpen, setMoreOpen] = useState(false); const [note, setNote] = useState(""); const [noteOpen, setNoteOpen] = useState(false); const [contactOpen, setContactOpen] = useState(false); const [submissionKey] = useState(() => crypto.randomUUID());
  const [submissionState, action, pending] = useActionState(submitConsumerJobServer, { message: "" }); const [authenticated, setAuthenticated] = useState(false);
  useEffect(() => { const auth = createSupabaseBrowserClient(); void auth.auth.getSession().then((result: { data: { session: Session | null } }) => setAuthenticated(Boolean(result.data.session))).catch(() => setAuthenticated(false)); }, []);
  const service = getService(categorySlug); const activeJobSlug = jobSlug || (typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("job") || "" : ""); const selectedJob = getJob(categorySlug, activeJobSlug); const questions = useMemo(() => selectedJob?.pricingQuestions.filter((q) => !q.showWhen || q.showWhen.values.includes(String(answers[q.showWhen.question] || ""))) || [], [selectedJob, answers]); const firstIncomplete = questions.findIndex((q) => q.required && !hasAnswer(q, answers)); const ready = Boolean(selectedJob && firstIncomplete === -1);
  const setAnswer = (id: string, value: string | number) => setAnswers((current) => ({ ...current, [id]: value })); const reset = () => { setCategorySlug(""); setJobSlug(""); setAnswers({}); };
  return <div id="job-composer" className="scroll-mt-24 rounded-2xl bg-white p-4 text-[#061b3f] shadow-[0_22px_60px_rgba(0,0,0,.24)] sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#159548]">Choose a service</p><h2 className="mt-1 text-xl font-black tracking-[-.03em]">{selectedJob ? `${selectedJob.name} ✓` : service ? service.name : "What do you need?"}</h2></div>{(service || selectedJob) && <button type="button" onClick={reset} className="text-xs font-black text-[#707b8d] underline">Change</button>}</div>{error && <p role="alert" className="mt-3 rounded-xl bg-[#fff3e7] p-3 text-sm font-bold text-[#974c00]">{error}</p>}{!service ? <CategoryPicker moreOpen={moreOpen} onMore={() => setMoreOpen((value) => !value)} onSelect={(slug) => { setCategorySlug(slug); setJobSlug(""); setAnswers({}); }} /> : !selectedJob ? <JobPicker service={service} onSelect={(slug) => { setJobSlug(slug); setAnswers({}); }} /> : <div className="mt-4">{questions.map((question, index) => <Question key={question.id} question={question} value={answers[question.id]} active={index <= firstIncomplete || firstIncomplete === -1} onChange={(value) => setAnswer(question.id, value)} />)}<button type="button" onClick={() => setNoteOpen((value) => !value)} className="mt-3 text-sm font-black text-[#167d3c]">{noteOpen ? "− Hide note" : "+ Add a note"} <span className="font-normal text-[#707b8d]">(optional)</span></button>{noteOpen && <textarea value={note} onChange={(event) => setNote(event.target.value)} rows={2} placeholder="Anything useful about the job" className={input} />}<button type="button" disabled={!ready} onClick={() => setContactOpen(true)} className="mt-4 min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-sm font-black disabled:opacity-40">Get quotes</button></div>}{contactOpen && <ContactSheet authenticated={authenticated} submissionKey={submissionKey} pending={pending} message={submissionState.message} category={categorySlug} job={selectedJob} answers={answers} note={note} location={initialLocation} action={action} onClose={() => setContactOpen(false)} />}</div>;
}

function CategoryPicker({ moreOpen, onMore, onSelect }: { moreOpen: boolean; onMore: () => void; onSelect: (slug: string) => void }) { const services = moreOpen ? marketplaceServices : marketplaceServices.filter((item) => featured.includes(item.slug)); return <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{services.map((item) => <button type="button" key={item.slug} onClick={() => onSelect(item.slug)} className="min-h-12 rounded-xl border border-[#e6ebef] px-2 text-xs font-black hover:border-[#23a955]">{item.shortName}</button>)}<button type="button" onClick={onMore} className="min-h-12 rounded-xl border border-dashed border-[#b8c4bd] px-2 text-xs font-black text-[#167d3c]">{moreOpen ? "Fewer" : "More services"}</button></div>; }
function JobPicker({ service, onSelect }: { service: NonNullable<ReturnType<typeof getService>>; onSelect: (slug: string) => void }) { return <div className="mt-4"><p className="text-sm font-black">What do you need?</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{service.jobs.filter((item) => item.active).map((item) => <button type="button" key={item.slug} onClick={() => onSelect(item.slug)} className="min-h-11 rounded-xl border border-[#e6ebef] px-3 text-left text-xs font-black hover:border-[#23a955]">{item.name}</button>)}</div></div>; }
function hasAnswer(question: PricingQuestion, answers: Record<string, string | number>) { const value = answers[question.id]; return value !== undefined && value !== "" && value !== 0; }
function Question({ question, value, active, onChange }: { question: PricingQuestion; value?: string | number; active: boolean; onChange: (value: string | number) => void }) { if (!active) return null; if (question.type === "postcode") return <label className="mt-4 block text-sm font-black">{question.label}<input value={String(value || "")} onChange={(event) => onChange(event.target.value.toUpperCase())} placeholder={question.placeholder} className={input} /></label>; if (question.type === "counter") return <div className="mt-4 flex min-h-12 items-center justify-between rounded-xl border border-[#e6ebef] px-3"><span className="text-sm font-black">{question.label}</span><div className="flex items-center gap-3"><button type="button" onClick={() => onChange(Math.max(0, Number(value || 0) - 1))} className="grid h-8 w-8 place-items-center rounded-full bg-[#f0f3f6] text-lg font-black">−</button><span className="w-4 text-center font-black">{value || 0}</span><button type="button" onClick={() => onChange(Number(value || 0) + 1)} className="grid h-8 w-8 place-items-center rounded-full bg-[#061b3f] text-lg font-black text-white">+</button></div></div>; if (question.type === "date") return <label className="mt-4 block text-sm font-black">{question.label}<input type="date" value={String(value || "")} onChange={(event) => onChange(event.target.value)} className={input} /></label>; return <div className="mt-4"><p className="text-sm font-black">{question.label}</p><div className="mt-2 flex flex-wrap gap-2">{(question.options || []).map((option) => <button type="button" key={option} onClick={() => onChange(option)} className={`min-h-10 rounded-xl border px-3 text-xs font-black ${value === option ? "border-[#23a955] bg-[#eef8f1] text-[#167d3c]" : "border-[#e6ebef]"}`}>{option}</button>)}</div></div>; }
function ContactSheet({ authenticated, submissionKey, pending, message, category, job, answers, note, location, action, onClose }: { authenticated: boolean; submissionKey: string; pending: boolean; message: string; category: string; job: MarketplaceJob | undefined; answers: Record<string, string | number>; note: string; location: string; action: (formData: FormData) => void; onClose: () => void }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#061b3f]/55 p-3"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-5 text-[#061b3f] shadow-2xl sm:p-7"><h2 className="text-2xl font-black">{authenticated ? "Post your job" : "Get quotes from local people"}</h2><p className="mt-2 text-sm leading-5 text-[#707b8d]">{authenticated ? "Your job will be posted immediately and local people who can help can send private offers." : "Save your job and start receiving offers."}</p>{message && <p role="alert" className="mt-4 rounded-xl bg-[#fff3e7] p-3 text-sm font-bold text-[#974c00]">{message}</p>}<form action={action} className="mt-5"><input type="hidden" name="submissionKey" value={submissionKey} /><input type="hidden" name="category" value={category} /><input type="hidden" name="service" value={job?.slug || ""} /><input type="hidden" name="answers" value={JSON.stringify(answers)} /><input type="hidden" name="postcode" value={String(answers.postcode || answers.fromPostcode || "")} /><input type="hidden" name="when" value={String(answers.when || answers.date || "")} /><input type="hidden" name="description" value={note} /><input type="hidden" name="location" value={location} />{job && job.photoRequirement !== "none" && <label className="mt-4 block text-sm font-black">Add photos <span className="font-normal text-[#707b8d]">({job.photoRequirement})</span><input name="photos" type="file" accept="image/*" multiple className="mt-2 block w-full text-sm" /></label>}<button disabled={pending} className="mt-5 min-h-12 w-full rounded-xl bg-[#23dc63] px-5 text-sm font-black disabled:opacity-60">{pending ? "Posting your job…" : authenticated ? "Post job & get quotes" : "Continue with email"}</button></form>{!authenticated && <p className="mt-3 text-center text-xs text-[#707b8d]">Your job will be posted immediately after signing in.</p>}<button type="button" onClick={onClose} className="mt-3 w-full text-sm font-black text-[#707b8d]">Cancel</button></div></div>; }
