import Image from "next/image";
import Link from "next/link";
import { customerSignOut } from "@/app/components/marketplace/actions";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getCurrentAccountRole } from "@/lib/auth/account-role";

export default async function MarketplaceHeader() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  const role = await getCurrentAccountRole();
  const authenticated = Boolean(user);
  const customerMode = role === "customer" || (!user && !role);
  const quoteLinkClass = "rounded-xl bg-[#23a955] px-4 py-3 text-sm font-black text-[#061b3f] lg:flex lg:min-h-9 lg:w-[150px] lg:items-center lg:justify-center lg:rounded-[15px] lg:px-6 lg:py-1 lg:text-base";
  const links = customerMode ? authenticated ? <><Link href="/home">Home</Link><Link href="/my-jobs">My jobs</Link><Link href="/messages">Messages</Link><Link href="/account">Account</Link><Link href="/#job-composer">Post a job</Link></> : <><Link href="/#how-it-works">How it works</Link><Link href="/#job-composer">Find help</Link><Link href="/sign-in">Sign in</Link></> : <Link href={role === "admin" ? "/admin" : "/work"}>{role === "admin" ? "Admin console" : "Provider workspace"}</Link>;
  const customerSignOutClass = "rounded-lg border border-[#dbe1ea] bg-white px-3 py-2 text-sm font-black text-[#061b3f] transition hover:border-[#b9c8d8] hover:bg-[#f7f9fb] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#23a955]/30";
  const homeHref = role === "customer" ? "/home" : role === "admin" ? "/admin" : "/";
  return <header className="sticky top-0 z-50 border-b border-[#e7ebef] bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-14 max-w-[1480px] items-center justify-between gap-4 px-4 sm:px-8 lg:min-h-[60px] lg:px-12"><Link href={homeHref} className="flex items-center gap-2 text-xl font-black tracking-[-.03em] lg:gap-3 lg:text-3xl" aria-label="Quickola home"><Image src="/quickola/logo-mark.png" alt="" width={36} height={36} priority className="lg:h-12 lg:w-12" />Quickola</Link><nav className="hidden items-center gap-6 text-sm font-extrabold md:flex lg:gap-9 lg:text-base" aria-label="Primary navigation">{links}</nav><div className="hidden items-center gap-3 sm:flex">{authenticated ? <><span className="grid h-9 w-9 place-items-center rounded-full bg-[#061b3f] text-sm font-black text-white" aria-label="Account">Q</span><form action={customerSignOut}><button className={customerMode ? customerSignOutClass : "text-sm font-black text-[#167d3c]"}>Sign out</button></form></> : <Link href="/#job-composer" className={quoteLinkClass}>Get quotes</Link>}</div><details className="relative sm:hidden"><summary aria-label="Open menu" className="flex min-h-11 cursor-pointer list-none items-center rounded-xl px-2 [&::-webkit-details-marker]:hidden"><span className="sr-only">Open menu</span><span aria-hidden="true" className="grid gap-1"><i className="h-0.5 w-5 bg-[#061b3f]" /><i className="h-0.5 w-5 bg-[#061b3f]" /><i className="h-0.5 w-5 bg-[#061b3f]" /></span></summary><nav className="absolute right-0 top-12 z-50 grid w-64 gap-1 rounded-2xl border border-[#e7ebef] bg-white p-3 text-sm font-extrabold shadow-xl" aria-label="Mobile navigation">{customerMode ? authenticated ? <><Link href="/home" className="rounded-xl px-1 py-3">Home</Link><Link href="/my-jobs" className="rounded-xl px-1 py-3">My jobs</Link><Link href="/messages" className="rounded-xl px-1 py-3">Messages</Link><Link href="/account" className="rounded-xl px-1 py-3">Account</Link><Link href="/#job-composer" className="rounded-xl px-1 py-3">Post a job</Link></> : <><Link href="/#how-it-works" className="rounded-xl px-1 py-3">How it works</Link><Link href="/#job-composer" className="rounded-xl px-1 py-3">Find help</Link><Link href="/sign-in" className="rounded-xl px-1 py-3">Sign in</Link><Link href="/#job-composer" className="rounded-xl bg-[#23a955] px-3 py-3 text-[#061b3f]">Get quotes</Link></> : <Link href={role === "admin" ? "/admin" : "/work"} className="rounded-xl px-1 py-3">{role === "admin" ? "Admin console" : "Provider workspace"}</Link>}{authenticated && <form action={customerSignOut}><button className={customerMode ? "rounded-lg border border-[#dbe1ea] bg-white px-3 py-2 text-left text-[#061b3f]" : "rounded-xl px-1 py-3 text-left text-[#167d3c]"}>Sign out</button></form>}</nav></details></div></header>;
}
