"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { AuthChangeEvent, Session } from "@supabase/supabase-js";
import LandingAuthTrigger from "@/app/components/marketplace/LandingAuthTrigger";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

export default function MarketplaceHeader() {
  const [authenticated, setAuthenticated] = useState(false);
  useEffect(() => { const auth = createSupabaseBrowserClient(); void auth.auth.getSession().then((result: { data: { session: Session | null } }) => setAuthenticated(Boolean(result.data.session))); const { data: listener } = auth.auth.onAuthStateChange((_event: AuthChangeEvent, session: Session | null) => setAuthenticated(Boolean(session))); return () => listener.subscription.unsubscribe(); }, []);
  const links = [["Browse jobs", "/jobs"]];
  const marketplaceLinks = <>{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}<Link href="/my-jobs">My jobs</Link><Link href="/messages">Messages</Link></>;
  return <header className="sticky top-0 z-50 border-b border-[#e7ebef] bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-[1480px] items-center justify-between gap-4 px-4 sm:px-8"><Link href="/" className="flex items-center gap-2 text-xl font-black tracking-[-.03em]" aria-label="Quickola home"><Image src="/quickola/logo-mark.png" alt="" width={36} height={36} priority />Quickola</Link><nav className="hidden items-center gap-6 text-sm font-extrabold md:flex" aria-label="Primary navigation">{marketplaceLinks}{authenticated ? <Link href="/#job-composer">Post a job</Link> : <><LandingAuthTrigger label="Post a job" className="px-1 py-3" /><LandingAuthTrigger label="Sign in" className="px-1 py-3" /></>}</nav><div className="hidden items-center gap-3 sm:flex">{authenticated ? <><span className="text-lg" aria-label="Notifications">♧</span><span className="grid h-9 w-9 place-items-center rounded-full bg-[#061b3f] text-sm font-black text-white">Q</span></> : <LandingAuthTrigger label="Get started" className="rounded-xl bg-[#23a955] px-4 py-3 text-sm font-black text-[#061b3f]" />}</div><details className="relative sm:hidden"><summary className="flex min-h-11 cursor-pointer list-none items-center rounded-xl border border-[#dfe4e9] px-3 text-sm font-extrabold [&::-webkit-details-marker]:hidden">Menu</summary><nav className="absolute right-0 top-13 z-50 grid w-64 gap-1 rounded-2xl border border-[#e7ebef] bg-white p-3 text-sm font-extrabold shadow-xl" aria-label="Mobile navigation">{marketplaceLinks}{authenticated ? <Link href="/#job-composer" className="rounded-xl px-1 py-3">Post a job</Link> : <LandingAuthTrigger label="Post a job" className="rounded-xl px-1 py-3 text-left" />}{!authenticated && <LandingAuthTrigger label="Sign in" className="rounded-xl px-1 py-3 text-left" />}{!authenticated && <LandingAuthTrigger label="Get started" className="rounded-xl bg-[#23a955] px-3 py-3 text-left text-[#061b3f]" />}</nav></details></div></header>;
}
