import Image from "next/image";
import Link from "next/link";
import { customerSignOut } from "@/app/components/marketplace/actions";
import LandingAuthTrigger from "@/app/components/marketplace/LandingAuthTrigger";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function MarketplaceHeader() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  const authenticated = Boolean(user);
  return <header className="sticky top-0 z-50 border-b border-[#e7ebef] bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-[1480px] items-center justify-between gap-4 px-4 sm:px-8 lg:min-h-[60px] lg:px-12"><Link href="/" className="flex items-center gap-2 text-xl font-black tracking-[-.03em] lg:gap-3 lg:text-3xl" aria-label="Quickola home"><Image src="/quickola/logo-mark.png" alt="" width={36} height={36} priority className="lg:h-12 lg:w-12" />Quickola</Link><nav className="hidden items-center gap-6 text-sm font-extrabold md:flex lg:gap-11 lg:text-base" aria-label="Primary navigation">{authenticated ? <><Link href="/my-jobs">My jobs</Link><Link href="/messages">Messages</Link><Link href="/#job-composer">Post a job</Link></> : <><Link href="/#how-it-works">How it works</Link><Link href="/#job-composer">Find help</Link><Link href="/sign-in">Sign in</Link></>}</nav><div className="hidden items-center gap-3 sm:flex">{authenticated ? <><span className="grid h-9 w-9 place-items-center rounded-full bg-[#061b3f] text-sm font-black text-white" aria-label="Account">Q</span><form action={customerSignOut}><button className="text-sm font-black text-[#167d3c]">Sign out</button></form></> : <LandingAuthTrigger label="Get started" className="rounded-xl bg-[#23a955] px-4 py-3 text-sm font-black text-[#061b3f] lg:flex lg:min-h-9 lg:w-[150px] lg:items-center lg:justify-center lg:rounded-[15px] lg:px-6 lg:py-1 lg:text-base" />}</div><details className="relative sm:hidden"><summary aria-label="Open menu" className="flex min-h-11 cursor-pointer list-none items-center rounded-xl px-2 text-3xl leading-none [&::-webkit-details-marker]:hidden">☰</summary><nav className="absolute right-0 top-13 z-50 grid w-64 gap-1 rounded-2xl border border-[#e7ebef] bg-white p-3 text-sm font-extrabold shadow-xl" aria-label="Mobile navigation">{authenticated ? <><Link href="/my-jobs" className="rounded-xl px-1 py-3">My jobs</Link><Link href="/messages" className="rounded-xl px-1 py-3">Messages</Link><Link href="/#job-composer" className="rounded-xl px-1 py-3">Post a job</Link><form action={customerSignOut}><button className="rounded-xl px-1 py-3 text-left text-[#167d3c]">Sign out</button></form></> : <><Link href="/#how-it-works" className="rounded-xl px-1 py-3">How it works</Link><Link href="/#job-composer" className="rounded-xl px-1 py-3">Find help</Link><Link href="/sign-in" className="rounded-xl px-1 py-3">Sign in</Link><Link href="/#job-composer" className="rounded-xl bg-[#23a955] px-3 py-3 text-[#061b3f]">Get started</Link></>}</nav></details></div></header>;
}
