import Link from "next/link";
import { marketplaceLocations, marketplaceServices, type MarketplaceService } from "@/app/data/marketplace";
import ServiceJobCards from "./ServiceJobCards";
import ServiceQuoteTrigger from "./ServiceQuoteTrigger";

type Location = { slug: string; name: string };

export default function ServiceLandingPage({ service, location }: { service: MarketplaceService; location?: Location }) {
  const locationSuffix = location ? ` in ${location.name}` : "";
  const description = location ? service.locationHeroDescription : service.heroDescription;
  const cta = location ? service.localQuoteCta : service.quoteCta;
  return <>
    <section className="bg-[#061b3f] px-5 py-14 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-[1120px]"><div className="max-w-2xl"><Link href="/services" className="text-sm font-bold text-white/60">← All services</Link><p className="mt-5 text-xs font-black uppercase tracking-[.16em] text-[#23dc63]">{service.heroEyebrow}</p><h1 className="mt-3 text-5xl font-black tracking-[-.06em] sm:text-6xl">{service.heroOutcome}{locationSuffix}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">{description}</p><ServiceQuoteTrigger className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-[#23dc63] px-6 font-black text-[#061b3f]">{cta}</ServiceQuoteTrigger></div></div></section>
    <ServiceJobCards service={service} locationName={location?.name} interactive heading={service.jobQuestion} showLabel={false} />
    <section className="px-5 pb-12 sm:px-8 sm:pb-16"><div className="mx-auto max-w-[1120px]">{location && <p className="mb-6 leading-7 text-[#707b8d]">{service.localContextCopy.replace("{location}", location.name).replace("{postcode}", "SL6")}</p>}<div className="rounded-2xl bg-[#eef8f1] p-6"><h2 className="text-3xl font-black tracking-[-.04em]">One job. One request. Compare your options.</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><div><h3 className="font-black">Tell us once</h3><p className="mt-2 leading-7 text-[#707b8d]">Describe what needs doing, where the job is and when you need it.</p></div><div><h3 className="font-black">Compare local prices</h3><p className="mt-2 leading-7 text-[#707b8d]">Available local providers can send you their price for the job.</p></div><div><h3 className="font-black">Choose who works for you</h3><p className="mt-2 leading-7 text-[#707b8d]">Compare your options and decide who you want to go with.</p></div></div></div><div className="mt-8 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-black tracking-[-.04em]">Tell local providers what needs sorting</h2><p className="mt-4 leading-7 text-[#707b8d]">Add the job location, what needs doing, when you need it and any useful access details. Photos can help providers understand the work before they send a price.</p></div><div className="rounded-2xl bg-white p-6 ring-1 ring-[#e9edf1]"><h2 className="text-xl font-black">Related services</h2><div className="mt-4 grid gap-2">{marketplaceServices.filter((item) => item.slug !== service.slug).slice(0, 4).map((item) => <Link key={item.slug} href={`/services/${item.slug}${location ? `/${location.slug}` : ""}`} className="font-extrabold text-[#167d3c]">{item.name}{location ? ` in ${location.name}` : ""} →</Link>)}</div></div></div>{!location && <aside className="mt-10 rounded-2xl bg-white p-6 ring-1 ring-[#e9edf1]"><h2 className="text-xl font-black">Explore local areas</h2><div className="mt-4 flex flex-wrap gap-2">{marketplaceLocations.slice(0, 3).map((area) => <Link key={area.slug} href={`/services/${service.slug}/${area.slug}`} className="rounded-xl bg-[#eef8f1] px-4 py-3 text-sm font-extrabold text-[#167d3c]">{service.name} in {area.name} →</Link>)}</div></aside>}</div></section>
  </>;
}
