import { ActivityIndicator, RefreshControl, ScrollView, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { EmptyState, PrimaryButton, ScreenHeader } from "@/components/ui";
import { getCleanerClients } from "@/lib/api";
import { addressFor, displayName, formatDate } from "@/lib/types";
import { colors, spacing, styles, typography } from "@/lib/theme";

export default function Clients() { const router = useRouter(); const query = useQuery({ queryKey: ["cleaner-clients"], queryFn: getCleanerClients }); return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={colors.blue} />}><ScreenHeader title="Clients" subtitle="Keep every client, property and clean organised." />{query.isLoading ? <ActivityIndicator style={{ marginTop: spacing.lg }} color={colors.blue} /> : query.isError ? <View style={styles.card}><Text style={styles.heading}>Couldn’t load clients</Text><Text style={[styles.body, { marginTop: 7 }]}>Check your connection and try again.</Text><View style={{ marginTop: spacing.md }}><PrimaryButton label="Try again" onPress={() => void query.refetch()} /></View></View> : query.data?.length ? query.data.map(({ invitation, properties, jobs }) => { const next = jobs.filter((job) => !["ready", "cancelled", "declined"].includes(job.status)).sort((a, b) => new Date(a.turnover_date).getTime() - new Date(b.turnover_date).getTime())[0]; const last = jobs.find((job) => job.status === "ready"); return <View key={invitation.id} style={[styles.card, { marginBottom: spacing.sm }]}><Text style={typography.card}>{displayName(invitation.host_name, "Client")}</Text><Text style={[typography.meta, { marginTop: 4 }]}>{invitation.status === "accepted" ? "Connected client" : "Invitation pending"}</Text><Text style={[styles.body, { marginTop: spacing.sm }]}>{properties.length} propert{properties.length === 1 ? "y" : "ies"} · {jobs.length} clean{jobs.length === 1 ? "" : "s"}</Text>{properties[0] && <Text style={typography.meta}>{addressFor(properties[0], properties[0].nickname || "Property")}</Text>}{next && <Text style={[typography.meta, { marginTop: 6 }]}>Next clean · {formatDate(next.turnover_date)}</Text>}{last && <Text style={typography.meta}>Last clean · {formatDate(last.turnover_date)}</Text>}</View>; }) : <View style={styles.card}><EmptyState title="Build your cleaning business" copy="Add the clients you already clean for. Quickola keeps their properties, cleans, instructions and reports together." action="Add existing client" onPress={() => router.push("/invite-host")} secondary="Invite client" onSecondary={() => router.push("/invite-host")} /></View>}</ScrollView>; }
