import { useEffect, useRef, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { Link, Redirect, useRouter } from "expo-router";
import { useAuth } from "@/lib/auth";
import { colors, styles } from "@/lib/theme";

const schema = z.object({ email: z.string().trim().email("Enter a valid email address"), password: z.string().min(10, "Use at least 10 characters for your password") });
type FormValues = z.infer<typeof schema>;

export default function CreateAccount() {
  const { session, signUp } = useAuth(); const router = useRouter(); const [serverError, setServerError] = useState(""); const [sent, setSent] = useState(""); const [created, setCreated] = useState(false); const mounted = useRef(true); useEffect(() => () => { mounted.current = false; }, []);
  const { control, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { email: "", password: "" }, mode: "onSubmit" });
  if (session && !created) return <Redirect href="/" />;
  async function submit(values: FormValues) { setServerError(""); const result = await signUp(values); if (!mounted.current) return; if (result.existing || result.error) { setServerError(result.error || "An account already exists with this email."); return; } if (result.session) { setCreated(true); router.replace("/onboarding"); return; } setSent(values.email.trim().toLowerCase()); }
  if (sent) return <View style={[styles.screen, { justifyContent: "center", padding: 24 }]}><View style={styles.card}><Text style={styles.eyebrow}>ACCOUNT CREATED</Text><Text style={[styles.title, { fontSize: 27, marginTop: 8 }]}>Check your email</Text><Text style={[styles.body, { marginTop: 12 }]}>We sent a confirmation link to <Text style={{ color: colors.ink, fontWeight: "800" }}>{sent}</Text>. Confirm your email to finish creating your Quickola account.</Text><Link href="/sign-in" style={[button, { marginTop: 22, paddingVertical: 16 }]}>Back to sign in</Link></View></View>;
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.screen}><ScrollView contentContainerStyle={content} keyboardShouldPersistTaps="handled"><View><Text style={styles.eyebrow}>QUICKOLA CLEANER APP</Text><Text style={[styles.title, { marginTop: 10 }]}>Create your cleaner account</Text><Text style={[styles.body, { marginTop: 8 }]}>Manage cleans, complete checklists and send photo reports to your hosts.</Text></View><View style={form}><Text style={label}>Email</Text><Controller control={control} name="email" render={({ field: { onChange, onBlur, value } }) => <TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={value} onBlur={() => { onBlur(); setServerError(""); }} onChangeText={(next) => { onChange(next); setServerError(""); }} style={input} placeholder="you@example.com" placeholderTextColor="#9aa5b5" />} />{errors.email && <Text style={error}>{errors.email.message}</Text>}<Text style={[label, { marginTop: 22 }]}>Password</Text><Controller control={control} name="password" render={({ field: { onChange, onBlur, value } }) => <TextInput secureTextEntry autoComplete="new-password" value={value} onBlur={() => { onBlur(); setServerError(""); }} onChangeText={(next) => { onChange(next); setServerError(""); }} style={input} placeholder="At least 10 characters" placeholderTextColor="#9aa5b5" />} />{errors.password && <Text style={error}>{errors.password.message}</Text>}{serverError && !errors.email && !errors.password && <Text accessibilityLiveRegion="polite" style={[error, serverErrorStyle]}>{serverError}</Text>}<Pressable disabled={isSubmitting} onPress={() => void handleSubmit(submit)()} style={[button, isSubmitting && { opacity: 0.5 }]}><Text style={buttonText}>{isSubmitting ? "Creating account…" : "Create account"}</Text></Pressable><Text style={footer}>Already have an account? <Link href="/sign-in" style={link}>Sign in</Link></Text></View></ScrollView></KeyboardAvoidingView>;
}
const content = { flexGrow: 1, justifyContent: "center" as const, padding: 24, paddingTop: 40, paddingBottom: 40 }; const form = { marginTop: 30, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 20 }; const label = { color: colors.ink, fontSize: 14, fontWeight: "700" as const }; const input = { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 14, color: colors.ink, fontSize: 16, marginTop: 8 }; const error = { color: colors.danger, fontSize: 13, marginTop: 6 }; const serverErrorStyle = { fontSize: 14, marginTop: 12 }; const button = { minHeight: 52, borderRadius: 11, backgroundColor: colors.navy, alignItems: "center" as const, justifyContent: "center" as const }; const buttonText = { color: colors.white, fontSize: 16, fontWeight: "800" as const }; const link = { color: colors.blue, fontWeight: "800" as const }; const footer = { color: colors.muted, textAlign: "center" as const, marginTop: 18, fontSize: 14 };
