import { ActivityIndicator, Image, ScrollView, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { getCleanerReports, getReportEvidenceUrls } from "@/lib/api";
import type { CleanerReport } from "@/lib/types";
import { colors, spacing, styles } from "@/lib/theme";
import { EmptyState, ReportCard, ScreenHeader } from "@/components/ui";

export default function Reports() { const router = useRouter(); const query = useQuery({ queryKey: ["cleaner-reports"] , queryFn: getCleanerReports }); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader title="Professional clean reports" subtitle="Show clients exactly what was completed." back={() => router.back()} />{query.isLoading ? <ActivityIndicator style={{ marginTop: spacing.lg }} color={colors.blue} /> : query.isError ? <View style={styles.card}><Text style={styles.heading}>Couldn’t load reports</Text><Text style={[styles.body, { marginTop: 7 }]}>Check your connection and try again.</Text></View> : query.data?.length ? query.data.map((report) => <ReportCardWithThumb key={report.id} report={report} onPress={() => router.push(`/report/${report.id}`)} />) : <View style={styles.card}><EmptyState title="No reports yet" copy="Reports appear here after you complete a clean." action="Back to Today" onPress={() => router.replace("/(tabs)/today")} /></View>}</ScrollView>; }
function ReportCardWithThumb({ report, onPress }: { report: CleanerReport; onPress: () => void }) { const path = report.report_data.evidence?.find((item) => item.storage_path)?.storage_path; const image = useQuery({ queryKey: ["report-list-thumb", report.id, path], queryFn: () => getReportEvidenceUrls([path!]), enabled: Boolean(path), staleTime: 5 * 60 * 1000 }); const url = image.data?.[0]?.signedUrl; const displayReport: CleanerReport = url ? { ...report, report_data: { ...report.report_data, evidence: [{ signedUrl: url }, ...(report.report_data.evidence || []).slice(1)] } } : report; return <View><ReportCard report={displayReport} onPress={onPress} />{url && <Image accessibilityLabel="Report preview" source={{ uri: url }} style={{ position: "absolute", right: 16, top: 16, width: 52, height: 52, borderRadius: 10 }} />}</View>; }
