"use client";

import { useMemo, useState } from "react";
import { calculateCleaningQuote, CLEANING_HOURLY_RATE, cleaningExtras } from "@/lib/cleaningPricing";

const RATE = CLEANING_HOURLY_RATE;
const extras = cleaningExtras;

function Choice({ active, title, note, onClick }: { active: boolean; title: string; note?: string; onClick: () => void }) {
  return <button type="button" onClick={onClick} className={`min-h-[64px] rounded-[14px] border p-3.5 text-left transition ${active ? "border-[#079448] bg-[#effaf3] shadow-[0_5px_16px_rgba(7,148,72,.08)]" : "border-[#dfe6ee] bg-white hover:border-[#a8b8ae]"}`}><span className={`block text-[13px] font-black ${active ? "text-[#06753a]" : "text-[#071638]"}`}>{active && <span className="mr-1.5">✓</span>}{title}</span>{note && <span className="mt-1 block text-[10px] font-bold leading-4 text-[#7a8598]">{note}</span>}</button>;
}

function Counter({ label, value, setValue, min = 0 }: { label: string; value: number; setValue: (n: number) => void; min?: number }) {
  return <div className="flex items-center justify-between rounded-[14px] border border-[#dfe6ee] p-3"><span className="text-[13px] font-black text-[#071638]">{label}</span><div className="flex items-center gap-4"><button type="button" aria-label={`Remove ${label}`} onClick={() => setValue(Math.max(min, value - 1))} className="grid h-9 w-9 place-items-center rounded-full bg-[#f0f3f6] text-xl font-black">−</button><span className="w-4 text-center text-[16px] font-black">{value}</span><button type="button" aria-label={`Add ${label}`} onClick={() => setValue(Math.min(8, value + 1))} className="grid h-9 w-9 place-items-center rounded-full bg-[#071638] text-xl font-black text-white">+</button></div></div>;
}

export default function CleaningBookingForm({ initialType = "Domestic clean" }: { initialType?: string }) {
  const [step, setStep] = useState(1), [type, setType] = useState(initialType), [frequency, setFrequency] = useState("One-off");
  const [property, setProperty] = useState("House"), [floor, setFloor] = useState("Ground / lift"), [bedrooms, setBedrooms] = useState(2), [bathrooms, setBathrooms] = useState(1);
  const [lastClean, setLastClean] = useState("Cleaned regularly"), [condition, setCondition] = useState("Tidy — just needs a clean");
  const [selectedExtras, setSelectedExtras] = useState<string[]>([]), [parking, setParking] = useState("Free / driveway"), [postcode, setPostcode] = useState(""), [postcodeError, setPostcodeError] = useState("");

  const quote = useMemo(() => calculateCleaningQuote({ service: type, frequency, property, floor, bedrooms, bathrooms, condition, lastClean, extras: selectedExtras, parking }), [bedrooms, bathrooms, type, lastClean, condition, property, floor, selectedExtras, frequency, parking]);

  const toggle = (name: string) => setSelectedExtras(current => current.includes(name) ? current.filter(x => x !== name) : [...current, name]);
  const goNext = () => { if (step === 4) { const valid = /^SL[1-6][A-Z]?\s?\d[A-Z]{2}$/i.test(postcode.trim()); if (!valid) { setPostcodeError("Enter a valid Slough postcode, for example SL1 2AB."); return; } setPostcodeError(""); } setStep(current => Math.min(5, current + 1)); };
  const goBack = () => setStep(current => Math.max(1, current - 1));
  const book = () => { const q = new URLSearchParams({ service: type, frequency, property, floor, bedrooms: String(bedrooms), bathrooms: String(bathrooms), condition, lastClean, extras: selectedExtras.join(", ") || "None", parking, hours: String(quote.hours), price: String(quote.price), postcode }); window.location.href = `/book?${q}`; };

  return <div className="mx-auto max-w-[820px] overflow-hidden rounded-[24px] bg-white shadow-[0_24px_70px_rgba(4,18,45,.22)] ring-1 ring-black/5">
    <div className="px-5 pb-4 pt-5 sm:px-8 sm:pt-7"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#079448]">Instant cleaning estimate</p><h2 className="mt-1 text-[25px] font-black tracking-[-.04em] text-[#071638] sm:text-[31px]">A few quick questions.</h2></div><span className="rounded-full bg-[#f1f6f3] px-3 py-2 text-[11px] font-black text-[#53645a]">{step < 5 ? `${step} of 4` : "Your price"}</span></div>
      <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#e9eef0]"><div className="h-full rounded-full bg-[#079448] transition-all duration-300" style={{ width: `${Math.min(step, 4) * 25}%` }} /></div></div>

    <div className="min-h-[340px] border-t border-[#edf1f4] p-5 sm:min-h-[360px] sm:p-8">
      {step === 1 && <div><p className="text-[11px] font-black uppercase tracking-[.1em] text-[#7a8598]">Step 1</p><h3 className="mt-1 text-[23px] font-black tracking-[-.035em]">What clean do you need?</h3><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{[["Domestic clean","For everyday home cleaning"],["Deep clean","A more detailed reset"],["Airbnb turnover","Reset between guest stays"],["End of tenancy","Detailed move-in or move-out"],["After builders","Dust and debris after works"]].map(([name,note]) => <Choice key={name} active={type === name} title={name} note={note} onClick={() => setType(name)} />)}</div><p className="mt-5 text-[12px] font-black text-[#536079]">How often?</p><div className="mt-2 grid grid-cols-3 gap-2">{["One-off","Weekly","Fortnightly"].map(name => <Choice key={name} active={frequency === name} title={name} onClick={() => setFrequency(name)} />)}</div></div>}

      {step === 2 && <div><p className="text-[11px] font-black uppercase tracking-[.1em] text-[#7a8598]">Step 2</p><h3 className="mt-1 text-[23px] font-black tracking-[-.035em]">Tell us about the property.</h3><p className="mt-1 text-[12px] font-semibold text-[#718078]">Kitchen, lounge and common areas are included as standard.</p><div className="mt-5 grid grid-cols-3 gap-2">{["House","Flat","Studio"].map(name => <Choice key={name} active={property === name} title={name} onClick={() => setProperty(name)} />)}</div>{property === "Flat" && <div className="mt-3 grid grid-cols-2 gap-2">{["Ground / lift","Stairs only"].map(name => <Choice key={name} active={floor === name} title={name} onClick={() => setFloor(name)} />)}</div>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><Counter label="Bedrooms" value={bedrooms} setValue={setBedrooms} /><Counter label="Bathrooms" value={bathrooms} setValue={setBathrooms} min={1} /></div></div>}

      {step === 3 && <div><p className="text-[11px] font-black uppercase tracking-[.1em] text-[#7a8598]">Step 3</p><h3 className="mt-1 text-[23px] font-black tracking-[-.035em]">What condition is it in?</h3><p className="mt-1 text-[12px] font-semibold text-[#718078]">This is the biggest driver of how long the clean takes.</p><p className="mt-5 text-[12px] font-black">When was it last professionally cleaned?</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{["Cleaned regularly","A while ago","Never professionally cleaned"].map(name => <Choice key={name} active={lastClean === name} title={name} onClick={() => setLastClean(name)} />)}</div><p className="mt-5 text-[12px] font-black">Current condition</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{["Tidy — just needs a clean","Cluttered","Heavily soiled"].map(name => <Choice key={name} active={condition === name} title={name} onClick={() => setCondition(name)} />)}</div></div>}

      {step === 4 && <div><p className="text-[11px] font-black uppercase tracking-[.1em] text-[#7a8598]">Step 4</p><h3 className="mt-1 text-[23px] font-black tracking-[-.035em]">Extras and location.</h3><p className="mt-1 text-[12px] font-semibold text-[#718078]">Extras are optional and add a fixed amount of time.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{extras.map(x => <Choice key={x.name} active={selectedExtras.includes(x.name)} title={x.name} note={`+${x.minutes} min`} onClick={() => toggle(x.name)} />)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label><span className="mb-2 block text-[11px] font-black uppercase tracking-[.08em] text-[#647087]">Postcode</span><input value={postcode} onChange={e => {setPostcode(e.target.value.toUpperCase());setPostcodeError("")}} placeholder="e.g. SL1 2AB" maxLength={9} autoComplete="postal-code" className={`h-12 w-full rounded-xl border px-3 text-[14px] font-black uppercase outline-none focus:border-[#079448] ${postcodeError?"border-red-400":"border-[#dce4ed]"}`} />{postcodeError&&<span className="mt-1 block text-[11px] font-bold text-red-600">{postcodeError}</span>}</label><label><span className="mb-2 block text-[11px] font-black uppercase tracking-[.08em] text-[#647087]">Parking</span><select value={parking} onChange={e => setParking(e.target.value)} className="h-12 w-full rounded-xl border border-[#dce4ed] px-3 text-[13px] font-bold"><option>Free / driveway</option><option>Permit provided</option><option>Paid parking (+£5)</option><option>No nearby parking</option></select></label></div></div>}

      {step === 5 && <div className="text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#eaf8ee] text-xl text-[#079448]">✓</span><p className="mt-4 text-[11px] font-black uppercase tracking-[.12em] text-[#079448]">Your instant price</p><div className="mt-2 text-[52px] font-black leading-none tracking-[-.06em] text-[#071638]">£{quote.price}</div><p className="mt-2 text-[14px] font-black text-[#536079]">{quote.hours} hours · {type}</p><p className="mx-auto mt-3 max-w-[430px] text-[12px] font-semibold leading-5 text-[#7a8598]">Calculated at £{RATE}/hour from your property, condition and extras. Contact and arrival details come next.</p><button type="button" onClick={book} className="mt-6 h-14 w-full max-w-[420px] rounded-xl bg-[#079448] text-[15px] font-black text-white shadow-[0_12px_25px_rgba(7,148,72,.22)]">Continue to booking →</button><button type="button" onClick={() => setStep(1)} className="mt-3 block w-full text-[12px] font-black text-[#607089]">Start again</button></div>}
    </div>

    {step < 5 && <div className="flex items-center justify-between border-t border-[#edf1f4] bg-[#fbfcfc] px-5 py-4 sm:px-8"><button type="button" onClick={goBack} className={`text-[13px] font-black text-[#607089] ${step === 1 ? "invisible" : ""}`}>← Back</button><button type="button" onClick={goNext} disabled={step === 4 && !postcode.trim()} className="h-12 rounded-xl bg-[#079448] px-7 text-[14px] font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{step === 4 ? "Get my price" : "Continue"} →</button></div>}
    <div className="grid grid-cols-3 divide-x divide-[#e2e8e4] border-t border-[#e6ece8] py-3 text-center text-[9px] font-black text-[#536079] sm:text-[11px]"><span>✓ Clear pricing</span><span>✓ Book with Quickola</span><span>Flexible times</span></div>
  </div>;
}
