const steps = [["01", "Post your job", "Tell local providers what you need and where the work is located."], ["02", "Review offers", "Compare prices, availability and provider information in one place."], ["03", "Choose and book", "Message the provider you prefer and book or pay where supported."]];

export default function HowItWorks() {
  return <>
    <section id="services" className="bg-white px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1120px]"><div className="max-w-[650px]"><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#079448]">LOCAL SERVICE MARKETPLACE</p><h2 className="mt-3 text-[36px] font-black leading-[1.03] tracking-[-.045em] sm:text-[48px]">One clear workflow.<br/>The help you need.</h2><p className="mt-4 text-[16px] font-semibold leading-7 text-[#667188]">Post a local service job, compare offers from independent providers and choose what works for you.</p></div></div></section>
    <section id="how" className="bg-[#f5f7f9] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1120px]"><div className="text-center"><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#079448]">How Quickola works</p><h2 className="mt-3 text-[36px] font-black tracking-[-.045em] sm:text-[48px]">From job post to booking.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(([number, title, text]) => <div key={number} className="rounded-[22px] bg-white p-6 shadow-[0_10px_30px_rgba(7,22,56,.04)]"><span className="text-[12px] font-black tracking-[.12em] text-[#079448]">{number}</span><h3 className="mt-8 text-[20px] font-black">{title}</h3><p className="mt-2 text-[14px] font-semibold leading-6 text-[#68738a]">{text}</p></div>)}</div></div></section>
    <section className="bg-[#061a3d] px-5 py-14 text-white sm:px-8"><div className="mx-auto flex max-w-[1120px] flex-col gap-6 rounded-[24px] border border-white/10 bg-white/5 p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-[#4bd35f]">For customers and providers</p><h2 className="mt-2 text-[28px] font-black sm:text-[36px]">Get local work moving.</h2><p className="mt-3 max-w-[690px] text-[14px] font-semibold leading-6 text-white/68">Post a job or join the marketplace as an independent provider.</p></div><a href="/create-account" className="inline-flex h-13 shrink-0 items-center justify-center rounded-xl bg-[#4bd35f] px-7 text-[14px] font-black text-[#061a3d]">Create account →</a></div></section>
  </>;
}
