import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getMarketplaceBookingLifecycleLabel, getMarketplaceBookingLifecycleState } from "@/lib/marketplace/customer-job-state";
import { customerMetrics, humanService, netBookingValue, relationshipState, relativeAge, rebookingOpportunity, type CrmBooking, type CrmIssue, type CrmJob, type CrmRefund, type CrmReview } from "@/lib/marketplace/customer-crm";

const money = (pence: number) => `£${(pence / 100).toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
type Provider = { user_id: string; display_name: string | null; business_name: string | null };

export default async function MarketplaceCustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params; const db = createSupabaseAdminClient();
  const [{ data: customer }, { data: jobs }, { data: bookings }] = await Promise.all([
    db.from("marketplace_customers").select("id,display_name,email,mobile,created_at").eq("id", id).maybeSingle(),
    db.from("marketplace_jobs").select("id,customer_id,service,service_subtype,postcode,status,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
    db.from("marketplace_bookings").select("id,job_id,customer_id,provider_id,status,payment_status,amount_pence,refunded_amount_pence,completion_status,payout_hold_status,payout_hold_reason,created_at,updated_at").eq("customer_id", id).order("created_at", { ascending: false }),
  ]);
  if (!customer) notFound();
  const bookingIds = ((bookings || []) as Array<{ id: string }>).map((booking) => booking.id);
  const [{ data: providers }, { data: reviews }, { data: disputes }, { data: refunds }] = await Promise.all([
    db.from("marketplace_providers").select("user_id,display_name,business_name"),
    db.from("marketplace_reviews").select("id,booking_id,customer_id,provider_id,rating,review_text,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
    bookingIds.length ? db.from("marketplace_disputes").select("id,booking_id,status,reason_code,description,opened_at,resolved_at").in("booking_id", bookingIds) : Promise.resolve({ data: [] }),
    bookingIds.length ? db.from("marketplace_refunds").select("id,booking_id,amount_pence,status,created_at").in("booking_id", bookingIds) : Promise.resolve({ data: [] }),
  ]);
  const crmJobs = (jobs || []) as CrmJob[]; const crmBookings = (bookings || []) as CrmBooking[]; const crmProviders = (providers || []) as Provider[]; const crmReviews = (reviews || []) as CrmReview[]; const crmIssues = (disputes || []) as CrmIssue[]; const crmRefunds = (refunds || []) as CrmRefund[]; const metrics = customerMetrics(crmBookings, crmJobs, crmReviews); const relationship = relationshipState({ bookings: crmBookings, jobs: crmJobs, issues: crmIssues, reviews: crmReviews, refunds: crmRefunds }); const opportunities = rebookingOpportunity(crmBookings, crmJobs, crmReviews); const issueBookingIds = new Set(crmIssues.filter((issue) => ["open", "in_review"].includes(issue.status)).map((issue) => issue.booking_id));
  const providersUsed = [...new Map(metrics.genuine.map((booking) => [booking.provider_id, booking])).values()].map((sample) => { const providerBookings = metrics.genuine.filter((booking) => booking.provider_id === sample.provider_id); const providerReviews = crmReviews.filter((review) => review.provider_id === sample.provider_id); const provider = crmProviders.find((candidate) => candidate.user_id === sample.provider_id); return { provider, bookings: providerBookings, completed: providerBookings.filter((booking) => booking.status === "completed").length, spend: providerBookings.reduce((sum, booking) => sum + netBookingValue(booking), 0), reviews: providerReviews, averageRating: providerReviews.length ? providerReviews.reduce((sum, review) => sum + Number(review.rating), 0) / providerReviews.length : null, last: providerBookings[0] }; }).sort((a, b) => b.bookings.length - a.bookings.length);
  const firstBooking = [...metrics.genuine].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime())[0]; const refunded = crmRefunds.filter((refund) => refund.status === "succeeded").reduce((sum, refund) => sum + Number(refund.amount_pence || 0), 0);
  return <div className="mx-auto max-w-[1180px]"><Link href="/admin/customers" className="text-sm font-black text-[#167d3c]">← Customers</Link><header className="mt-4 flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#159548]">CUSTOMER DOSSIER</p><h1 className="mt-1 text-3xl font-black">{customer.display_name || "Unnamed customer"}</h1><p className="mt-1 text-sm text-[#657089]">Customer since {new Date(customer.created_at).toLocaleDateString("en-GB")} · {customer.email || "No email"}{customer.mobile ? ` · ${customer.mobile}` : ""}</p></div><span className={`rounded-full px-3 py-2 text-xs font-black ${relationship.state === "AT RISK" ? "bg-[#fdeaea] text-[#b33a3a]" : relationship.state === "REBOOK DUE" ? "bg-[#fff4dc] text-[#9a6900]" : "bg-[#e7f6ec] text-[#177b42]"}`}>{relationship.state}</span></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Jobs" value={crmJobs.length} /><Metric label="Bookings" value={metrics.genuine.length} /><Metric label="Completed" value={metrics.completed.length} /><Metric label="Total spend" value={money(metrics.spendPence)} /></section>
    <section className="mt-4 rounded-xl border bg-white p-4"><h2 className="text-sm font-black">Relationship summary</h2><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Most-used service" value={metrics.mostUsedService || "—"} /><Info label="Last service" value={humanService(metrics.latest ? crmJobs.find((job) => job.id === metrics.latest?.job_id) : undefined)} /><Info label="Last provider" value={crmProviders.find((provider) => provider.user_id === metrics.latest?.provider_id)?.business_name || crmProviders.find((provider) => provider.user_id === metrics.latest?.provider_id)?.display_name || "—"} /><Info label="Providers used" value={providersUsed.length} /><Info label="Average booking" value={metrics.genuine.length ? money(metrics.averageBookingPence) : "—"} /><Info label="Reviews given" value={metrics.reviews.length} /><Info label="Average rating given" value={metrics.averageRating === null ? "—" : metrics.averageRating.toFixed(1)} /><Info label="Issues" value={`${crmIssues.filter((issue) => ["open", "in_review"].includes(issue.status)).length} open · ${crmIssues.filter((issue) => !["open", "in_review"].includes(issue.status)).length} historical`} /><Info label="Refunded" value={refunded ? money(refunded) : "£0.00"} /><Info label="Last booking" value={relativeAge(metrics.latest?.created_at) === null ? "—" : `${relativeAge(metrics.latest?.created_at)}d ago`} /><Info label="First booking" value={relativeAge(firstBooking?.created_at) === null ? "—" : `${relativeAge(firstBooking?.created_at)}d ago`} /></div></section>
    {opportunities.length > 0 && <section className="mt-4 rounded-xl border border-[#eadfbf] bg-[#fffaf0] p-4"><h2 className="text-sm font-black">Potential rebooking opportunity</h2>{opportunities.map((opportunity) => <div key={opportunity.booking.id} className="mt-2 text-sm"><b>{humanService(opportunity.job)}</b><p className="mt-1 text-[#526078]">Last completed {opportunity.age} days ago. Previous provider: {crmProviders.find((provider) => provider.user_id === opportunity.booking.provider_id)?.business_name || crmProviders.find((provider) => provider.user_id === opportunity.booking.provider_id)?.display_name || "Provider record"}.</p><p className="mt-1 font-bold text-[#8a5a00]">Customer may be ready to book this service again.</p></div>)}</section>}
    <section className="mt-4 rounded-xl border bg-white p-4"><h2 className="text-sm font-black">Providers used</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{providersUsed.map((item, index) => <Link key={item.provider?.user_id || index} href={item.provider ? `/admin/providers/${item.provider.user_id}` : "/admin/providers"} className="rounded-lg border p-3 hover:bg-[#f7fbf8]"><div className="flex items-start justify-between gap-3"><b>{item.provider?.business_name || item.provider?.display_name || "Provider record"}</b>{index === 0 && <span className="text-[10px] font-black text-[#159548]">MOST USED PROVIDER</span>}</div><p className="mt-1 text-xs text-[#526078]">{item.bookings.length} bookings · {item.completed} completed · {money(item.spend)} spent</p><p className="mt-1 text-xs text-[#718099]">{item.averageRating === null ? "No rating given" : `★ ${item.averageRating.toFixed(1)}`} · Last booked {relativeAge(item.last.created_at)}d ago</p></Link>)}{!providersUsed.length && <p className="text-sm text-[#718099]">No provider relationship recorded yet.</p>}</div></section>
    <section className="mt-4 rounded-xl border bg-white p-4"><h2 className="text-sm font-black">Booking history</h2><div className="mt-3 grid gap-2">{metrics.genuine.map((booking) => { const job = crmJobs.find((candidate) => candidate.id === booking.job_id); const provider = crmProviders.find((candidate) => candidate.user_id === booking.provider_id); const review = crmReviews.find((candidate) => candidate.booking_id === booking.id); const state = getMarketplaceBookingLifecycleState(booking, issueBookingIds.has(booking.id)); return <Link key={booking.id} href={`/admin/marketplace-bookings/${booking.id}`} className="grid gap-2 rounded-lg border p-3 hover:bg-[#f7fbf8] md:grid-cols-[1.3fr_1fr_auto_auto] md:items-center"><span><b>{humanService(job)}</b><small className="mt-1 block text-xs text-[#718099]">{provider?.business_name || provider?.display_name || "Provider"}</small></span><span className="text-xs text-[#526078]">{money(Number(booking.amount_pence || 0))}{Number(booking.refunded_amount_pence || 0) > 0 ? ` · ${money(Number(booking.refunded_amount_pence))} refunded` : ""}<br />{money(netBookingValue(booking))} net paid</span><span className="text-xs font-bold">{getMarketplaceBookingLifecycleLabel(state)} · {booking.completion_status?.replaceAll("_", " ") || "—"}</span><span className="text-xs text-[#718099]">{review ? `★ ${review.rating}` : "—"} · {new Date(booking.created_at).toLocaleDateString("en-GB")}</span></Link>})}{!metrics.genuine.length && <p className="text-sm text-[#718099]">No genuine paid marketplace bookings.</p>}</div></section>
    <section className="mt-4 rounded-xl border bg-white p-4"><h2 className="text-sm font-black">Reviews given</h2><div className="mt-3 grid gap-2">{crmReviews.map((review) => { const booking = crmBookings.find((candidate) => candidate.id === review.booking_id); const job = crmJobs.find((candidate) => candidate.id === booking?.job_id); const provider = crmProviders.find((candidate) => candidate.user_id === review.provider_id); return <Link key={review.booking_id} href={`/admin/marketplace-bookings/${review.booking_id}`} className="rounded-lg border p-3 hover:bg-[#f7fbf8]"><div className="flex flex-wrap justify-between gap-2"><b>{humanService(job)} · {provider?.business_name || provider?.display_name || "Provider"}</b><span className="font-black">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)} · {review.rating}/5</span></div>{review.review_text && <p className="mt-1 text-sm text-[#526078]">“{review.review_text}”</p>}<p className="mt-1 text-xs text-[#718099]">{new Date(review.created_at).toLocaleDateString("en-GB")}</p></Link>})}{!crmReviews.length && <p className="text-sm text-[#718099]">No reviews submitted yet.</p>}</div></section>
    <section className="mt-4 grid gap-4 pb-8 lg:grid-cols-2"><Panel title="Issues">{crmIssues.map((issue) => <Link key={issue.booking_id} href={`/admin/marketplace-bookings/${issue.booking_id}`} className="block border-b py-2 text-sm"><b>{issue.status.replaceAll("_", " ")}</b><span className="ml-2 text-[#718099]">{issue.reason_code || "Marketplace issue"}</span></Link>)}{!crmIssues.length && <p className="text-sm text-[#718099]">No issues recorded.</p>}</Panel><Panel title="Refunds">{crmRefunds.map((refund) => <Link key={`${refund.booking_id}-${refund.amount_pence}`} href={`/admin/marketplace-bookings/${refund.booking_id}`} className="block border-b py-2 text-sm"><b>{money(Number(refund.amount_pence))}</b><span className="ml-2 capitalize text-[#718099]">{refund.status}</span></Link>)}<p className="mt-3 text-sm font-black">Total succeeded: {money(refunded)}</p>{!crmRefunds.length && <p className="mt-2 text-sm text-[#718099]">No refunds recorded.</p>}</Panel></section>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-[#657089]">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs font-bold text-[#718099]">{label}</p><p className="mt-1 font-black capitalize">{value}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-4"><h2 className="text-sm font-black">{title}</h2><div className="mt-2">{children}</div></section>; }
