import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function MarketplaceCustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params; const db = createSupabaseAdminClient();
  const [{ data: customer }, { data: jobs }, { data: bookings }, { data: conversations }, { data: reviews }] = await Promise.all([
    db.from("marketplace_customers").select("id,display_name,email,mobile,created_at").eq("id", id).maybeSingle(),
    db.from("marketplace_jobs").select("id,service,service_subtype,postcode,status,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
    db.from("marketplace_bookings").select("id,job_id,status,payment_status,amount_pence,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
    db.from("marketplace_conversations").select("id,job_id,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
    db.from("marketplace_reviews").select("id,booking_id,rating,review_text,created_at").eq("customer_id", id).order("created_at", { ascending: false }),
  ]);
  if (!customer) notFound();
  const spend = (bookings || []).filter((booking) => booking.payment_status === "paid").reduce((sum, booking) => sum + Number(booking.amount_pence || 0), 0);
  return <div className="mx-auto max-w-[1100px]"><Link href="/admin/customers" className="text-sm font-black text-[#167d3c]">← Customers</Link><div className="mt-4"><p className="text-xs font-black uppercase tracking-[.12em] text-[#159548]">CUSTOMER SUPPORT VIEW</p><h1 className="mt-1 text-3xl font-black">{customer.display_name || "Unnamed customer"}</h1><p className="mt-1 text-[#657089]">{customer.email || "No email"} · Joined {new Date(customer.created_at).toLocaleDateString("en-GB")}</p></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><Metric label="Jobs posted" value={(jobs || []).length} /><Metric label="Bookings" value={(bookings || []).length} /><Metric label="Conversations" value={(conversations || []).length} /><Metric label="Paid spend" value={spend ? `£${(spend / 100).toFixed(2)}` : "Not available"} /></div><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Jobs</h2><div className="mt-4 grid gap-3">{(jobs || []).map((job) => <Link key={job.id} href={`/admin/jobs/${job.id}`} className="flex flex-wrap justify-between gap-3 rounded-xl border p-4"><span><span className="font-black">{job.service_subtype || job.service}</span><span className="ml-2 text-sm text-[#657089]">{job.postcode}</span></span><span className="text-sm font-bold capitalize">{job.status.replaceAll("_", " ")}</span></Link>)}{!(jobs || []).length && <p className="text-[#657089]">No marketplace jobs posted.</p>}</div></section><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Bookings and payments</h2><div className="mt-4 grid gap-3">{(bookings || []).map((booking) => <Link key={booking.id} href={`/admin/marketplace-bookings/${booking.id}`} className="flex flex-wrap justify-between gap-3 rounded-xl border p-4"><span className="font-black">{(jobs || []).find((job) => job.id === booking.job_id)?.service_subtype || "Marketplace booking"}</span><span className="text-sm capitalize">{booking.payment_status.replaceAll("_", " ")} · {booking.status.replaceAll("_", " ")}</span></Link>)}{!(bookings || []).length && <p className="text-[#657089]">No marketplace bookings.</p>}</div></section><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Conversations</h2><div className="mt-4 grid gap-3">{(conversations || []).map((conversation) => <Link key={conversation.id} href="/admin/support" className="flex justify-between rounded-xl border p-4"><span className="font-black">Conversation for {(jobs || []).find((job) => job.id === conversation.job_id)?.service_subtype || "marketplace job"}</span><span className="text-sm text-[#657089]">{new Date(conversation.created_at).toLocaleDateString("en-GB")}</span></Link>)}{!(conversations || []).length && <p className="text-[#657089]">No conversations.</p>}</div></section></div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold text-[#657089]">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>; }
