import Link from "next/link";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/admin/auth";

type Customer = { id: string; auth_user_id: string | null; display_name: string | null; email: string | null; mobile: string | null; created_at: string };
const money = (pence: number) => pence ? `£${(pence / 100).toLocaleString("en-GB", { maximumFractionDigits: 0 })}` : "—";

export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  await requireAdmin(); const query = await searchParams; const page = Math.max(1, Number(query.page || 1) || 1); const admin = createSupabaseAdminClient();
  const [{ data: customerData, count: customerCount }, { data: jobs }, { data: bookings }, { data: reviews }] = await Promise.all([
    admin.from("marketplace_customers").select("id,auth_user_id,display_name,email,mobile,created_at", { count: "exact" }).order("created_at", { ascending: false }).range((page - 1) * 50, page * 50 - 1),
    admin.from("marketplace_jobs").select("customer_id").limit(1000),
    admin.from("marketplace_bookings").select("customer_id,status,payment_status,amount_pence,updated_at,created_at").limit(1000),
    admin.from("marketplace_reviews").select("customer_id").limit(1000),
  ]);
  const customers = (customerData || []) as Customer[]; const needle = (query.q || "").trim().toLowerCase(); const visible = customers.filter((customer) => !needle || [customer.display_name, customer.email, customer.mobile].some((value) => String(value || "").toLowerCase().includes(needle))); const count = (items: Array<Record<string, string | null>>, key: string, value: string) => items.filter((item) => item[key] === value).length; const totalPages = Math.max(1, Math.ceil((customerCount || customers.length) / 50));
  return <div className="mx-auto max-w-[1260px]"><header className="flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-[25px] font-black tracking-[-.04em]">Customers</h1><p className="mt-1 text-sm text-[#718099]">Manage homeowners and customers</p></div><div className="flex items-center gap-2"><button type="button" disabled className="min-h-9 rounded-lg border border-[#e2e8ee] bg-white px-3 text-xs font-bold text-[#758399]">Export</button><button type="button" className="min-h-9 rounded-lg border border-[#e2e8ee] bg-white px-3 text-xs font-bold text-[#52637b]">☷ Filters</button></div></header>
    <form className="mt-6 flex max-w-sm gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search name, email or phone" className="min-h-9 w-full rounded-lg border border-[#e2e8ee] bg-white px-3 text-xs outline-none focus:border-[#159b50]" /><button className="min-h-9 rounded-lg bg-[#112b4b] px-3 text-xs font-bold text-white">Search</button></form>
    <section className="mt-4 overflow-hidden rounded-lg border border-[#e5eaf0] bg-white shadow-[0_2px_8px_rgba(28,48,76,.03)]"><div className="overflow-x-auto"><table className="w-full min-w-[930px] text-left text-xs"><thead className="border-b border-[#e8edf2] bg-[#fafbfc] text-[10px] uppercase tracking-[.08em] text-[#7a889b]"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Jobs posted</th><th className="px-4 py-3">Total spend</th><th className="px-4 py-3">Joined</th><th className="px-4 py-3">Rating given</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{visible.map((customer) => { const customerBookings = (bookings || []).filter((booking) => booking.customer_id === customer.id); const paid = customerBookings.filter((booking) => booking.payment_status === "paid" && !["refunded", "failed"].includes(booking.status)).reduce((sum, booking) => sum + Number(booking.amount_pence || 0), 0); return <tr key={customer.id} className="hover:bg-[#fbfcfd]"><td className="px-4 py-3"><Link href={`/admin/customers/${customer.id}`} className="flex items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e8f4ec] text-[11px] font-black text-[#177b42]">{(customer.display_name || "C").slice(0, 1).toUpperCase()}</span><span><strong className="block text-[12px] font-black text-[#1d304c]">{customer.display_name || "Unnamed customer"}</strong><small className="mt-0.5 block text-[10px] text-[#8190a3]">{customer.email || customer.mobile || "No contact details"}</small></span></Link></td><td className="px-4 py-3 font-bold text-[#263752]">{count(jobs || [], "customer_id", customer.id)}</td><td className="px-4 py-3 font-bold text-[#263752]">{money(paid)}</td><td className="px-4 py-3 text-[#62728a]">{new Date(customer.created_at).toLocaleDateString("en-GB")}</td><td className="px-4 py-3 text-[#7c899b]">—</td><td className="px-4 py-3"><span className="rounded-full bg-[#e7f6ec] px-2 py-1 text-[10px] font-black text-[#177b42]">Active</span></td><td className="px-4 py-3 text-right"><details className="relative inline-block"><summary className="cursor-pointer list-none rounded-md px-2 py-1 text-lg leading-none text-[#74839a] hover:bg-[#f0f4f7]">⋯</summary><div className="absolute right-0 z-10 mt-1 w-32 rounded-md border border-[#e2e8ee] bg-white p-1 text-left shadow-lg"><Link href={`/admin/customers/${customer.id}`} className="block rounded px-2 py-2 text-xs font-bold hover:bg-[#f5f7f9]">View activity</Link><span className="block px-2 py-2 text-[10px] text-[#8995a5]">{customerBookings.length} bookings · {count(reviews || [], "customer_id", customer.id)} reviews</span></div></details></td></tr>; })}</tbody></table></div>{!visible.length && <p className="p-8 text-center text-sm text-[#718099]">No marketplace customers found.</p>}</section>
    <div className="flex flex-wrap items-center justify-between gap-3 py-4 text-xs text-[#758399]"><span>Showing {visible.length ? (page - 1) * 50 + 1 : 0} to {Math.min(page * 50, customerCount || visible.length)} of {customerCount ?? customers.length} customers</span><div className="flex items-center gap-1"><Link href={`/admin/customers?${query.q ? `q=${encodeURIComponent(query.q)}&` : ""}page=${Math.max(1, page - 1)}`} className="rounded border border-[#e2e8ee] bg-white px-2 py-1">‹</Link>{[...Array(Math.min(3, totalPages))].map((_, index) => <Link key={index} href={`/admin/customers?${query.q ? `q=${encodeURIComponent(query.q)}&` : ""}page=${index + 1}`} className={`rounded border px-2.5 py-1 ${page === index + 1 ? "border-[#159b50] bg-[#eaf7ee] text-[#177b42]" : "border-[#e2e8ee] bg-white"}`}>{index + 1}</Link>)}<Link href={`/admin/customers?${query.q ? `q=${encodeURIComponent(query.q)}&` : ""}page=${Math.min(totalPages, page + 1)}`} className="rounded border border-[#e2e8ee] bg-white px-2 py-1">›</Link></div></div>
  </div>;
}
