import Link from "next/link";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/admin/auth";
import ServiceCombobox from "@/app/admin/components/ServiceCombobox";
import { customerMetrics, humanService, relationshipState, rebookingOpportunity, repeatRate, relativeAge, type CrmBooking, type CrmIssue, type CrmJob, type CrmRefund, type CrmReview } from "@/lib/marketplace/customer-crm";

type Customer = { id: string; display_name: string | null; email: string | null; mobile: string | null; created_at: string };
type Provider = { user_id: string; display_name: string | null; business_name: string | null };
type Query = Promise<{ q?: string; relationship?: string; service?: string; outcode?: string; sort?: string; page?: string }>;
const money = (pence: number) => `£${(pence / 100).toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const outcode = (postcode?: string | null) => String(postcode || "").trim().split(/\s+/)[0].toUpperCase();

export default async function Page({ searchParams }: { searchParams: Query }) {
  await requireAdmin();
  const query = await searchParams;
  const page = Math.max(1, Number(query.page || 1) || 1);
  const db = createSupabaseAdminClient();
  const [{ data: customerRows }, { data: jobRows }, { data: bookingRows }, { data: providerRows }, { data: reviewRows }, { data: issueRows }, { data: refundRows }] = await Promise.all([
    db.from("marketplace_customers").select("id,display_name,email,mobile,created_at").order("created_at", { ascending: false }),
    db.from("marketplace_jobs").select("id,customer_id,service,service_subtype,postcode,created_at").order("created_at", { ascending: false }),
    db.from("marketplace_bookings").select("id,job_id,customer_id,provider_id,status,payment_status,amount_pence,refunded_amount_pence,completion_status,created_at,updated_at").order("created_at", { ascending: false }),
    db.from("marketplace_providers").select("user_id,display_name,business_name"),
    db.from("marketplace_reviews").select("id,booking_id,customer_id,provider_id,rating,review_text,created_at").order("created_at", { ascending: false }),
    db.from("marketplace_disputes").select("booking_id,status,opened_at").order("opened_at", { ascending: false }),
    db.from("marketplace_refunds").select("booking_id,amount_pence,status"),
  ]);
  const customers = (customerRows || []) as Customer[]; const jobs = (jobRows || []) as CrmJob[]; const bookings = (bookingRows || []) as CrmBooking[]; const providers = (providerRows || []) as Provider[]; const reviews = (reviewRows || []) as CrmReview[]; const issues = (issueRows || []) as CrmIssue[]; const refunds = (refundRows || []) as CrmRefund[];
  const jobsByCustomer = (id: string) => jobs.filter((job) => job.customer_id === id); const bookingsByCustomer = (id: string) => bookings.filter((booking) => booking.customer_id === id); const reviewsByCustomer = (id: string) => reviews.filter((review) => review.customer_id === id); const issuesByCustomer = (id: string) => { const ids = new Set(bookingsByCustomer(id).map((booking) => booking.id)); return issues.filter((issue) => ids.has(issue.booking_id)); }; const refundsByCustomer = (id: string) => { const ids = new Set(bookingsByCustomer(id).map((booking) => booking.id)); return refunds.filter((refund) => ids.has(refund.booking_id)); };
  const rows = customers.map((customer) => { const customerBookings = bookingsByCustomer(customer.id); const customerJobs = jobsByCustomer(customer.id); const customerReviews = reviewsByCustomer(customer.id); const customerIssues = issuesByCustomer(customer.id); const customerRefunds = refundsByCustomer(customer.id); return { customer, bookings: customerBookings, jobs: customerJobs, reviews: customerReviews, issues: customerIssues, refunds: customerRefunds, metrics: customerMetrics(customerBookings, customerJobs, customerReviews), relationship: relationshipState({ bookings: customerBookings, jobs: customerJobs, issues: customerIssues, reviews: customerReviews, refunds: customerRefunds }) }; });
  const serviceOptionMap = new Map<string, { value: string; label: string }>(); jobs.forEach((job) => { const value = job.service_subtype || job.service || ""; if (value) serviceOptionMap.set(value, { value, label: humanService(job) }); }); const options = [...serviceOptionMap.values()].sort((a, b) => a.label.localeCompare(b.label)); const outcodes = [...new Set(jobs.map((job) => outcode(job.postcode)).filter(Boolean))].sort();
  const needle = (query.q || "").trim().toLowerCase(); const filtered = rows.filter((row) => { const serviceMatch = !query.service || row.jobs.some((job) => (job.service_subtype || job.service) === query.service); const areaMatch = !query.outcode || row.jobs.some((job) => outcode(job.postcode) === query.outcode); const relationshipMatch = !query.relationship || row.relationship.state === query.relationship; const searchMatch = !needle || `${row.customer.display_name || ""} ${row.customer.email || ""} ${row.customer.mobile || ""}`.toLowerCase().includes(needle); return serviceMatch && areaMatch && relationshipMatch && searchMatch; });
  const sorted = [...filtered].sort((a, b) => { if (query.sort === "spend") return b.metrics.spendPence - a.metrics.spendPence; if (query.sort === "bookings") return b.metrics.genuine.length - a.metrics.genuine.length; if (query.sort === "completed") return b.metrics.completed.length - a.metrics.completed.length; if (query.sort === "rebook") return Number(b.relationship.state === "REBOOK DUE") - Number(a.relationship.state === "REBOOK DUE"); if (query.sort === "risk") return Number(b.relationship.state === "AT RISK") - Number(a.relationship.state === "AT RISK"); if (query.sort === "newest") return new Date(b.customer.created_at).getTime() - new Date(a.customer.created_at).getTime(); return (new Date(b.metrics.latest?.created_at || 0).getTime() - new Date(a.metrics.latest?.created_at || 0).getTime()); });
  const visible = sorted.slice((page - 1) * 25, page * 25); const totalPages = Math.max(1, Math.ceil(sorted.length / 25)); const repeat = repeatRate(rows); const opportunities = rows.flatMap((row) => rebookingOpportunity(row.bookings, row.jobs, row.reviews).map((opportunity) => ({ ...opportunity, customer: row.customer, provider: providers.find((provider) => provider.user_id === opportunity.booking.provider_id) }))).slice(0, 8); const atRisk = rows.filter((row) => row.relationship.state === "AT RISK").length;
  const qs = (extra: Record<string, string | undefined> = {}) => { const params = new URLSearchParams(); const values = { q: query.q, relationship: query.relationship, service: query.service, outcode: query.outcode, sort: query.sort, ...extra }; Object.entries(values).forEach(([key, value]) => { if (value) params.set(key, value); }); return `/admin/customers?${params.toString()}`; };
  return <div className="mx-auto max-w-[1450px]"><header><p className="text-xs font-black uppercase tracking-[.14em] text-[#159548]">CUSTOMER RETENTION</p><h1 className="mt-1 text-[28px] font-black tracking-[-.04em]">Customers</h1><p className="mt-1 text-sm text-[#718099]">Customer relationships, retention and rebooking.</p></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Total customers" value={customers.length} /><Kpi label="Repeat customers" value={repeat.repeat} detail={`${Math.round(repeat.rate * 100)}% repeat rate`} /><Kpi label="Rebooking opportunities" value={opportunities.length} detail="Potential opportunities" /><Kpi label="Customers at risk" value={atRisk} detail="Recent issue or poor experience" danger={atRisk > 0} /></section>
    <form className="mt-5 flex flex-wrap items-center gap-2 rounded-xl border bg-white p-3"><input name="q" defaultValue={query.q || ""} placeholder="Search customer, email or phone" className="min-h-10 min-w-64 flex-1 rounded-lg border px-3 text-xs" /><select name="relationship" defaultValue={query.relationship || ""} className="min-h-10 rounded-lg border px-3 text-xs"><option value="">All customers</option>{["NEW", "ACTIVE", "REPEAT", "REBOOK DUE", "LAPSED", "AT RISK"].map((state) => <option key={state} value={state}>{state}</option>)}</select><ServiceCombobox options={options} defaultValue={query.service || ""} /><select name="outcode" defaultValue={query.outcode || ""} className="min-h-10 rounded-lg border px-3 text-xs"><option value="">All areas</option>{outcodes.map((code) => <option key={code} value={code}>{code}</option>)}</select><select name="sort" defaultValue={query.sort || ""} className="min-h-10 rounded-lg border px-3 text-xs"><option value="">Most recently booked</option><option value="spend">Highest spend</option><option value="bookings">Most bookings</option><option value="completed">Most completed</option><option value="rebook">Rebooking opportunities</option><option value="risk">At risk</option><option value="newest">Newest</option></select><button className="min-h-9 rounded-lg border bg-[#f7f9fa] px-3 text-xs font-black text-[#526078]">Apply</button></form>
    <section className="mt-4 overflow-hidden rounded-xl border bg-white shadow-[0_2px_8px_rgba(28,48,76,.03)]"><div className="flex items-center justify-between border-b bg-[#fafbfc] px-4 py-3"><h2 className="text-sm font-black">Customer relationships</h2><span className="text-[11px] text-[#718099]">{sorted.length} matching customers</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1260px] text-left text-xs"><thead className="border-b text-[10px] uppercase tracking-[.08em] text-[#7a889b]"><tr><th className="px-4 py-3">Customer</th><th>Jobs</th><th>Bookings</th><th>Completed</th><th>Total spend</th><th>Last service</th><th>Last provider</th><th>Reviews</th><th>Last booking</th><th>Relationship</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{visible.map((row) => <CustomerRow key={row.customer.id} row={row} providers={providers} />)}</tbody></table></div>{!visible.length && <p className="p-10 text-center text-sm text-[#718099]">No customers match these filters.</p>}<div className="flex items-center justify-between border-t px-4 py-3 text-xs text-[#718099]"><span>{sorted.length ? `${(page - 1) * 25 + 1}–${Math.min(page * 25, sorted.length)} of ${sorted.length}` : "0 customers"}</span><span className="flex gap-1"><Link href={qs({ page: String(Math.max(1, page - 1)) })} className="rounded border px-2 py-1">‹</Link><span className="px-2 py-1">Page {page} of {totalPages}</span><Link href={qs({ page: String(Math.min(totalPages, page + 1)) })} className="rounded border px-2 py-1">›</Link></span></div></section>
    <section className="mt-4 rounded-xl border bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black">Rebooking opportunities</h2><p className="mt-1 text-xs text-[#718099]">Policy-based candidates only; no booking or outreach is created.</p></div><span className="text-[10px] font-black uppercase tracking-[.1em] text-[#b77900]">Admin intelligence</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{opportunities.map((opportunity) => <Link key={`${opportunity.customer.id}-${opportunity.booking.id}`} href={`/admin/customers/${opportunity.customer.id}`} className="rounded-lg border p-3 hover:bg-[#f7fbf8]"><b>{opportunity.customer.display_name || "Unnamed customer"}</b><p className="mt-1 text-xs text-[#526078]">{humanService(opportunity.job)} · last booked {opportunity.age}d ago</p><p className="mt-1 text-xs text-[#718099]">Previous provider: {opportunity.provider?.business_name || opportunity.provider?.display_name || "Provider record"}</p><span className="mt-2 inline-block text-[10px] font-black text-[#b77900]">REBOOK DUE →</span></Link>)}{!opportunities.length && <p className="text-xs text-[#718099]">No policy-based rebooking opportunities currently.</p>}</div></section>
  </div>;
}

function CustomerRow({ row, providers }: { row: { customer: Customer; jobs: CrmJob[]; bookings: CrmBooking[]; reviews: CrmReview[]; metrics: ReturnType<typeof customerMetrics>; relationship: { state: string; reason: string } }; providers: Provider[] }) { const provider = row.metrics.latest ? providers.find((candidate) => candidate.user_id === row.metrics.latest?.provider_id) : undefined; const service = humanService(row.metrics.latest ? row.jobs.find((job) => job.id === row.metrics.latest?.job_id) : undefined); const reviewAverage = row.metrics.averageRating === null ? "—" : `${row.metrics.averageRating.toFixed(1)} (${row.metrics.reviews.length})`; const age = relativeAge(row.metrics.latest?.created_at); return <tr className="hover:bg-[#f7fbf8]"><td className="px-4 py-3"><Link href={`/admin/customers/${row.customer.id}`} className="flex items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e8f4ec] text-[11px] font-black text-[#177b42]">{(row.customer.display_name || "C").slice(0, 1).toUpperCase()}</span><span><strong className="block text-[12px] font-black text-[#1d304c]">{row.customer.display_name || "Unnamed customer"}</strong><small className="block text-[10px] text-[#8190a3]">{row.customer.email || row.customer.mobile || "No contact details"}</small></span></Link></td><td>{row.jobs.length}</td><td>{row.metrics.genuine.length}</td><td>{row.metrics.completed.length}</td><td className="font-bold">{money(row.metrics.spendPence)}</td><td>{service}</td><td>{provider?.business_name || provider?.display_name || "—"}</td><td>{reviewAverage}</td><td>{age === null ? "—" : `${age}d ago`}</td><td><span title={row.relationship.reason} className={`rounded-full px-2 py-1 text-[10px] font-black ${row.relationship.state === "AT RISK" ? "bg-[#fdeaea] text-[#b33a3a]" : row.relationship.state === "REBOOK DUE" ? "bg-[#fff4dc] text-[#9a6900]" : "bg-[#e7f6ec] text-[#177b42]"}`}>{row.relationship.state}</span></td></tr>; }
function Kpi({ label, value, detail, danger = false }: { label: string; value: number; detail?: string; danger?: boolean }) { return <article className="rounded-xl border bg-white p-4 shadow-[0_2px_8px_rgba(28,48,76,.03)]"><p className="text-[11px] font-black text-[#748198]">{label}</p><p className={`mt-2 text-2xl font-black ${danger ? "text-[#c44747]" : "text-[#142745]"}`}>{value}</p>{detail && <p className="mt-1 text-[11px] text-[#718099]">{detail}</p>}</article>; }
