import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { submitProviderOffer } from "@/app/provider/actions";
export default async function ProviderJobPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ sent?: string; error?: string }> }) {
  const { id } = await params; const query = await searchParams; const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/auth/portal/sign-in?next=${encodeURIComponent(`/provider/jobs/${id}`)}`);
  const { data: opportunities } = await supabase.rpc("get_marketplace_opportunities"); const job = (opportunities || []).find((item: { id: string }) => item.id === id) as { id: string; job_type_slug: string; postcode_district: string; requested_timing: string | null; optional_note: string | null; structured_answers: Record<string, string | number> | null; photo_count: number } | undefined;
  if (!job) return <main className="mx-auto max-w-2xl px-5 py-16"><h1 className="text-2xl font-black">Job unavailable</h1><p className="mt-2 text-[#657089]">This opportunity is no longer open for offers.</p><Link href="/provider" className="mt-5 inline-block font-bold text-[#167d3c]">Back to browse</Link></main>;
  const details = Object.entries(job.structured_answers || {}).filter(([key]) => !["postcode", "when", "date"].includes(key));
  return <main className="mx-auto max-w-2xl px-5 py-10"><Link href="/provider" className="text-sm font-bold text-[#167d3c]">← Browse jobs</Link><h1 className="mt-5 text-3xl font-black">{job.job_type_slug.replaceAll("-", " ")}</h1><p className="mt-2 text-[#657089]">{job.postcode_district} · {job.requested_timing || "Flexible timing"}</p><section className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Job details</h2>{details.map(([key, value]) => <p key={key} className="mt-3 text-sm text-[#39465b]"><span className="font-bold">{key.replaceAll("_", " ")}:</span> {String(value)}</p>)}{job.optional_note && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#39465b]">{job.optional_note}</p>}</section>{query.sent === "1" ? <div className="mt-5 rounded-2xl bg-[#eef8f1] p-5 font-black text-[#167d3c]">Offer sent. The customer will see it privately.</div> : <form action={submitProviderOffer} className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><input type="hidden" name="jobId" value={job.id} /><h2 className="text-xl font-black">Make an offer</h2><label className="mt-5 block text-sm font-black">Your offer (£)<input name="amount" type="number" min="1" step="1" required className="mt-2 min-h-12 w-full rounded-xl border border-[#dbe1ea] px-4" placeholder="55" /></label><label className="mt-4 block text-sm font-black">Message <span className="font-normal text-[#657089]">(optional)</span><textarea name="message" rows={4} className="mt-2 w-full rounded-xl border border-[#dbe1ea] px-4 py-3" placeholder="Hi, I can complete this today around 4pm. I have my own equipment." /></label>{query.error && <p className="mt-3 text-sm font-bold text-red-700">We couldn’t send that offer. Check your amount and eligibility.</p>}<button className="mt-5 min-h-12 w-full rounded-xl bg-[#23dc63] font-black text-[#061b3f]">Submit offer</button></form>}</main>;
}
