import Link from "next/link";
import { redirect } from "next/navigation";
import { marketplaceServices } from "@/app/data/marketplace";
import { getMarketplaceProvider, isProviderReadyToSubmit } from "@/lib/marketplace/provider-access";
import { resolveProviderPhotoUrl } from "@/lib/marketplace/provider-photo";
import { destinationForAccount, getCurrentAccountContext } from "@/lib/auth/account-role";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { refreshProviderPayoutStatus } from "@/lib/server/provider-stripe";
import ProviderHeader from "@/app/components/marketplace/ProviderHeader";
import ProfileEditForm from "./ProfileEditForm";
import { startProviderPayoutSetup, submitProviderApplication } from "../onboarding/actions";

export default async function ProviderProfilePage({ searchParams }: { searchParams: Promise<{ payouts?: string; saved?: string; error?: string; edit?: string; returnTo?: string }> }) {
  const query = await searchParams;
  const account = await getCurrentAccountContext();
  if (account.role !== "provider") redirect(destinationForAccount(account) || "/");
  let provider = await getMarketplaceProvider();
  if (!provider) redirect("/pro/login");
  if (["return", "refresh"].includes(query.payouts || "")) {
    try { await refreshProviderPayoutStatus(provider.providerId); provider = await getMarketplaceProvider(); } catch { /* Keep the last known state visible if Stripe is temporarily unavailable. */ }
  }
  if (!provider) redirect("/pro/login");
  if (["pending_review", "suspended"].includes(provider.providerStatus)) redirect("/work");
  const admin = createSupabaseAdminClient();
  const [{ data: services }, { data: areas }, { count: completedJobs }, { data: reviews, count: reviewCount }] = await Promise.all([
    admin.from("marketplace_provider_services").select("category_slug,job_type_slug,active").eq("provider_id", provider.providerId).eq("active", true).order("category_slug"),
    admin.from("marketplace_provider_service_areas").select("postcode_district").eq("provider_id", provider.providerId).eq("active", true).order("postcode_district"),
    admin.from("marketplace_bookings").select("id", { count: "exact", head: true }).eq("provider_id", provider.providerId).eq("status", "completed"),
    admin.from("marketplace_reviews").select("rating").eq("provider_id", provider.providerId),
  ]);
  const selectedServices = services || [];
  const selectedCategories = [...new Set(selectedServices.map((service) => service.category_slug))];
  const profileReadyToSubmit = isProviderReadyToSubmit(provider.profile, selectedServices.length, areas?.length || 0, provider.emailConfirmedAt, provider.stripeStatus);
  const canSubmit = ["draft", "action_required"].includes(provider.providerStatus) && profileReadyToSubmit;
  const needsSetup = ["draft", "action_required"].includes(provider.providerStatus) && !profileReadyToSubmit;
  const photoPath = String(provider.profile.profile_photo_url || "") || null;
  const photoUrl = await resolveProviderPhotoUrl(admin, photoPath, 600);
  const name = String(provider.profile.display_name || provider.profile.business_name || "Provider");
  const providerType = String(provider.profile.provider_type || "").replaceAll("_", " ");
  const reviewRatings = (reviews || []).map((review) => Number(review.rating)).filter((rating) => Number.isFinite(rating));
  const averageRating = reviewRatings.length ? (reviewRatings.reduce((total, rating) => total + rating, 0) / reviewRatings.length).toFixed(1) : null;
  const hasActivity = Boolean(completedJobs || reviewCount || provider.profile.created_at);
  const setupError = query.error === "provider_email_missing" ? "Verify your email before setting up payouts." : query.error ? "We couldn’t update your profile. Please try again." : "";
  if (query.edit === "1") return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><ProviderHeader /><section className="mx-auto max-w-3xl px-5 py-8 sm:px-8"><Link href="/work/profile" className="text-sm font-black text-[#167d3c]">← Your profile</Link><ProfileEditForm profile={provider.profile} photoUrl={photoUrl} photoPath={photoPath} selectedServices={selectedServices.map((service) => `${service.category_slug}|${service.job_type_slug}`)} areas={(areas || []).map((area) => String(area.postcode_district))} returnTo={query.returnTo === "onboarding" ? "onboarding" : undefined} /></section></main>;
  return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><ProviderHeader /><section className="mx-auto max-w-3xl px-5 py-8 sm:px-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#159548]">YOUR PROFILE</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">How customers see you</h1><p className="mt-2 text-[#657089]">Keep your public marketplace profile clear and up to date.</p></div><div className="flex flex-wrap gap-3"><Link href={`/providers/${provider.providerId}`} className="inline-flex min-h-11 items-center rounded-xl border border-[#dbe1ea] px-4 text-sm font-black">View public profile</Link><Link href="/work/profile?edit=1" className="inline-flex min-h-11 items-center rounded-xl border border-[#dbe1ea] px-4 text-sm font-black">Edit profile</Link></div></div>
    {setupError && <p className="mt-5 rounded-xl bg-[#fff1f0] p-3 text-sm font-bold text-[#a12b20]">{setupError}</p>}{query.saved && <p className="mt-5 text-sm font-black text-[#167d3c]">✓ Profile saved</p>}
    <section className="mt-7 rounded-3xl border border-[#e7ebef] bg-white p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center">{photoUrl ? <img src={photoUrl} alt="" className="h-24 w-24 rounded-full object-cover" /> : <span className="grid h-24 w-24 place-items-center rounded-full bg-[#e8f4ec] text-3xl font-black text-[#167d3c]">{name.slice(0, 1).toUpperCase()}</span>}<div><p className="text-xs font-black uppercase tracking-[.14em] text-[#159548]">YOUR PROFILE</p><h2 className="mt-2 text-3xl font-black">{name}</h2><p className="mt-1 capitalize text-[#526078]">{providerType || "Independent provider"}{provider.profile.base_town ? ` · ${String(provider.profile.base_town)}` : ""}</p><div className="mt-3 flex flex-wrap gap-3 text-sm font-bold text-[#526078]">{provider.providerStatus === "approved" && <span className="text-[#167d3c]">✓ Approved</span>}{averageRating ? <span>★ {averageRating} ({reviewCount} {reviewCount === 1 ? "review" : "reviews"})</span> : <span>New to Quickola</span>}{completedJobs != null && <span>{completedJobs} completed {completedJobs === 1 ? "job" : "jobs"}</span>}</div></div></div></section>
    <section className="mt-8 border-t border-[#e7ebef] pt-7"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-black">About</h2><Link href="/work/profile?edit=1" className="min-h-11 px-2 py-2 text-sm font-black text-[#167d3c]">{provider.profile.marketplace_bio ? "Edit introduction" : "Add introduction"}</Link></div>{provider.profile.marketplace_bio ? <p className="mt-3 whitespace-pre-wrap leading-7 text-[#39465b]">{String(provider.profile.marketplace_bio)}</p> : <p className="mt-3 text-[#657089]">Tell customers about your experience and the type of work you do.</p>}</section>
    <section className="mt-8 border-t border-[#e7ebef] pt-7"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-black">Services</h2><Link href="/work/profile?edit=1" className="min-h-11 px-2 py-2 text-sm font-black text-[#167d3c]">Edit services</Link></div><div className="mt-4 grid gap-5 sm:grid-cols-2">{selectedCategories.length ? selectedCategories.map((categorySlug) => { const category = marketplaceServices.find((item) => item.slug === categorySlug); const jobs = selectedServices.filter((service) => service.category_slug === categorySlug); return <div key={categorySlug}><h3 className="font-black">{category?.name || categorySlug.replaceAll("-", " ")}</h3><ul className="mt-2 grid gap-1 text-sm leading-6 text-[#526078]">{jobs.map((service) => <li key={`${service.category_slug}-${service.job_type_slug}`}>· {category?.jobs.find((job) => job.slug === service.job_type_slug)?.name || service.job_type_slug.replaceAll("-", " ")}</li>)}</ul></div>; }) : <p className="text-[#657089]">No services selected yet.</p>}</div></section>
    <section className="mt-8 border-t border-[#e7ebef] pt-7"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-black">Areas you cover</h2><Link href="/work/profile?edit=1" className="min-h-11 px-2 py-2 text-sm font-black text-[#167d3c]">Edit areas</Link></div>{Boolean(provider.profile.base_town) && <p className="mt-3 text-[#526078]">{String(provider.profile.base_town)}</p>}{areas?.length ? <p className="mt-2 leading-7 text-[#526078]">{areas.map((area) => String(area.postcode_district)).join(" · ")}</p> : <p className="mt-3 text-[#657089]">No service areas added yet.</p>}</section>
    <section className="mt-8 border-t border-[#e7ebef] pt-7"><h2 className="text-2xl font-black">Your Quickola activity</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="text-2xl font-black">{completedJobs || 0}</p><p className="text-sm text-[#657089]">Jobs completed</p></div><div><p className="text-2xl font-black">{reviewCount || 0}</p><p className="text-sm text-[#657089]">Reviews</p></div><div><p className="text-2xl font-black">{averageRating || "—"}</p><p className="text-sm text-[#657089]">Rating</p></div>{Boolean(provider.profile.created_at) && <div><p className="text-2xl font-black">{new Intl.DateTimeFormat("en-GB", { month: "short", year: "numeric" }).format(new Date(String(provider.profile.created_at)))}</p><p className="text-sm text-[#657089]">Member since</p></div>}</div>{!hasActivity && <p className="mt-4 text-sm text-[#657089]">New to Quickola — your activity will appear here as you complete jobs.</p>}</section>
    {canSubmit ? <section className="mt-8 rounded-2xl border border-[#bfe3ca] bg-[#f5fbf6] p-5"><p className="text-xl font-black">Everything is ready</p><p className="mt-2 text-sm leading-6 text-[#526078]">Your profile is ready to be reviewed by Quickola.</p><form action={submitProviderApplication} className="mt-4"><button className="min-h-11 rounded-xl bg-[#23a955] px-5 font-black text-[#061b3f]">Submit for review</button></form></section> : needsSetup ? <section className="mt-8 rounded-2xl bg-[#f5f7f9] p-4 text-sm text-[#526078]">Finish your setup before submitting for review. <Link href="/work/onboarding?step=3" className="font-black text-[#167d3c] underline">Continue setup</Link></section> : null}
    <section className="mt-8 border-t border-[#e7ebef] pt-7"><h2 className="text-sm font-black uppercase tracking-[.14em] text-[#657089]">Account</h2><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-sm font-black">{provider.providerStatus === "approved" ? <span className="text-[#167d3c]">✓ Approved</span> : <span className="capitalize text-[#526078]">{provider.providerStatus.replaceAll("_", " ")}</span>}<span className={provider.stripeStatus === "ready" ? "text-[#167d3c]" : "text-[#8a5a00]"}>{provider.stripeStatus === "ready" ? "✓ Payouts ready" : "Payouts action needed"}</span></div>{provider.stripeStatus !== "ready" && <form action={startProviderPayoutSetup} className="mt-4"><input type="hidden" name="returnPath" value="/work/profile" /><button className="min-h-11 rounded-xl border border-[#dbe1ea] px-4 text-sm font-black">Set up payouts</button></form>}</section>
    </section></main>;
}
