import Image from "next/image";
import Link from "next/link";
const groups=[
  ["Platform",[["Product","/product"],["How it works","/how-it-works"],["Service area","/service-area"]]],
  ["Solutions",[["Letting agents","/solutions/letting-agents"],["Airbnb operators","/solutions/airbnb"],["Offices","/solutions/offices"]]],
  ["Company",[["About","/about"],["Trust & safety","/trust-safety"],["Contact","/contact"],["Sign in","/business/sign-in"]]],
  ["Legal",[["Privacy","/privacy-policy"],["Business terms","/business/legal/terms"],["Cancellations","/business/legal/cancellation"],["Cookies","/cookies"]]],
];
export default function Footer(){return <footer className="border-t border-[#dfe6eb] bg-white px-5 py-12 text-[#071638] sm:px-8"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[1.2fr_2fr]"><div><Link href="/" className="flex items-center gap-2.5" aria-label="Quickola homepage"><Image src="/quickola/logo-mark.png" alt="" width={40} height={40}/><span className="text-2xl font-black">Quickola</span></Link><p className="mt-4 max-w-sm text-sm leading-6 text-[#526078]">A managed cleaning platform for property professionals and businesses in the Slough area.</p><Link href="/business/enquire" className="button-primary mt-6">Request business access</Link></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{groups.map(([heading,items])=><nav key={heading as string} aria-label={`${heading} links`}><p className="text-xs font-black uppercase tracking-[.12em] text-[#657089]">{heading as string}</p><div className="mt-4 grid gap-3 text-sm font-bold">{(items as string[][]).map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div></nav>)}</div></div><div className="mx-auto mt-10 flex max-w-[1200px] flex-col gap-2 border-t border-[#e5eaed] pt-6 text-xs text-[#657089] sm:flex-row sm:justify-between"><p>© {new Date().getFullYear()} Quickola. All rights reserved.</p><p>Controlled managed-cleaning service in Slough.</p></div></footer>}
