import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function Page() {
  await requireAdmin();
  const admin = createSupabaseAdminClient();
  const today = new Date();
  const start = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate())).toISOString();
  const [{ count: openJobs }, { count: jobsToday }, { count: activeProviders }, { count: pendingInvites }, { count: offersToday }, { count: acceptedJobs }, { count: completedJobs }, { data: jobs }, { data: noOfferCandidates }] = await Promise.all([
    admin.from("marketplace_jobs").select("id", { count: "exact", head: true }).in("status", ["posted", "finding_provider"]),
    admin.from("marketplace_jobs").select("id", { count: "exact", head: true }).gte("created_at", start),
    admin.from("cleaner_profiles").select("user_id", { count: "exact", head: true }).eq("marketplace_active", true),
    admin.from("marketplace_provider_invitations").select("id", { count: "exact", head: true }).eq("status", "pending"),
    admin.from("marketplace_quotes").select("id", { count: "exact", head: true }).gte("created_at", start),
    admin.from("marketplace_jobs").select("id", { count: "exact", head: true }).in("status", ["awaiting_booking", "booked", "en_route", "arrived", "in_progress"]),
    admin.from("marketplace_jobs").select("id", { count: "exact", head: true }).eq("status", "completed"),
    admin.from("marketplace_jobs").select("id,public_token,service,service_subtype,postcode,budget_amount,status,created_at,contact_name,marketplace_customers(display_name,email),marketplace_quotes(count)").order("created_at", { ascending: false }).limit(8),
    admin.from("marketplace_jobs").select("id,public_token,service,service_subtype,postcode,created_at,marketplace_quotes(count)").in("status", ["posted", "finding_provider"]).order("created_at", { ascending: true }).limit(30),
  ]);
  const noOfferJobs = (noOfferCandidates || []).filter((job) => !Array.isArray(job.marketplace_quotes) || Number(job.marketplace_quotes[0]?.count || 0) === 0).slice(0, 8);
  const cards = [["Open jobs", openJobs || 0, "/admin/jobs"], ["Jobs posted today", jobsToday || 0, "/admin/jobs"], ["Active providers", activeProviders || 0, "/admin/providers"], ["Pending invites", pendingInvites || 0, "/admin/providers"], ["Offers today", offersToday || 0, "/admin/offers"], ["Accepted jobs", acceptedJobs || 0, "/admin/jobs"], ["Completed jobs", completedJobs || 0, "/admin/jobs"], ["Jobs with no offers", noOfferJobs?.length || 0, "/admin/jobs?offers=none"]];
  return <div className="mx-auto max-w-[1380px]"><p className="text-sm font-black uppercase tracking-[.12em] text-[#159548]">QUICKOLA MARKETPLACE</p><h1 className="mt-1 text-3xl font-black tracking-[-.03em] sm:text-4xl">Marketplace dashboard</h1><p className="mt-2 text-[#657089]">Monitor jobs, offers, customers and providers.</p><section className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{cards.map(([label, value, href]) => <Link key={String(label)} href={String(href)} className="rounded-2xl border bg-white p-4 hover:border-[#23a955]"><p className="text-xs font-bold text-[#657089]">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></Link>)}</section><div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="text-xl font-black">Recent jobs</h2><Link href="/admin/jobs" className="text-sm font-black text-[#167d3c]">View all →</Link></div><div className="divide-y">{jobs?.map((job) => { const customer = Array.isArray(job.marketplace_customers) ? job.marketplace_customers[0] : job.marketplace_customers; const count = Array.isArray(job.marketplace_quotes) ? Number(job.marketplace_quotes[0]?.count || 0) : 0; return <Link key={job.id} href={`/admin/jobs/${job.id}`} className="block p-5 hover:bg-[#f7f8fa]"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black capitalize">{(job.service_subtype || job.service).replaceAll("-", " ")}</h3><p className="mt-1 text-sm text-[#657089]">{customer?.display_name || customer?.email || job.contact_name || "Customer"} · {job.postcode} · {job.service}</p></div><span className="font-black text-[#167d3c]">{count} offers</span></div><p className="mt-3 text-sm font-bold">{job.budget_amount == null ? "Open budget" : `£${Number(job.budget_amount).toFixed(2).replace(/\.00$/, "")}`} · <span className="capitalize">{job.status.replaceAll("_", " ")}</span></p></Link>})}{!jobs?.length && <p className="p-8 text-[#657089]">No marketplace jobs yet.</p>}</div></section><section className="rounded-2xl border bg-white"><div className="border-b px-5 py-4"><h2 className="text-xl font-black">Needs attention</h2><p className="mt-1 text-sm text-[#657089]">Open jobs currently without offers.</p></div><div className="divide-y">{noOfferJobs?.map((job) => <Link key={job.id} href={`/admin/jobs/${job.id}`} className="block p-5 hover:bg-[#f7f8fa]"><h3 className="font-black capitalize">{(job.service_subtype || job.service).replaceAll("-", " ")}</h3><p className="mt-1 text-sm text-[#657089]">{job.postcode} · Posted {new Date(job.created_at).toLocaleDateString("en-GB")}</p></Link>)}{!noOfferJobs?.length && <p className="p-8 text-[#657089]">No jobs currently need attention.</p>}</div></section></div></div>;
}
