import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getMarketplaceBookingLifecycleState } from "@/lib/marketplace/customer-job-state";
import { expansionReadiness, isGenuineBooking, jobLabel, moneyPence, outcodeOf, overviewMetrics, percent, relationOne, type OverviewBooking, type OverviewDispute, type OverviewJob, type OverviewQuote, type OverviewReview } from "@/lib/marketplace/admin-overview";
import { ACTIVE_MARKETPLACE_POSTCODE_DISTRICTS } from "@/lib/marketplace/service-areas";

type Query = Promise<{ range?: string | string[]; outcode?: string | string[] }>;
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const daysFor = (value?: string) => value === "today" ? 1 : value === "7" ? 7 : 30;
const label = (value?: string | null) => (value || "unknown").replaceAll("_", " ");
const relative = (value: string) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago`; };

export default async function Page({ searchParams }: { searchParams: Query }) {
  await requireAdmin();
  const query = await searchParams;
  const selectedRange = one(query.range) || "30";
  const selectedOutcode = one(query.outcode) || ACTIVE_MARKETPLACE_POSTCODE_DISTRICTS[0] || "all";
  const now = new Date();
  const from = new Date(now); from.setHours(0, 0, 0, 0); from.setDate(from.getDate() - (daysFor(selectedRange) - 1));
  const strategicFrom = new Date(now); strategicFrom.setHours(0, 0, 0, 0); strategicFrom.setDate(strategicFrom.getDate() - 29);
  const to = new Date(now); to.setDate(to.getDate() + 1); to.setHours(0, 0, 0, 0);
  const admin = createSupabaseAdminClient();
  const [{ data: jobs }, { data: quotes }, { data: bookings }, { data: disputes }, { data: reviews }, { data: providers }, { data: providerAreas }] = await Promise.all([
    admin.from("marketplace_jobs").select("id,service,service_subtype,postcode,status,created_at").gte("created_at", strategicFrom.toISOString()).lt("created_at", to.toISOString()).order("created_at", { ascending: false }),
    admin.from("marketplace_quotes").select("job_id,status,created_at").gte("created_at", strategicFrom.toISOString()).lt("created_at", to.toISOString()),
    admin.from("marketplace_bookings").select("id,job_id,customer_id,status,payment_status,amount_pence,refunded_amount_pence,completion_status,payout_hold_status,payout_hold_reason,provider_transfer_status,created_at,customer_completed_at,marketplace_jobs(id,service,service_subtype,postcode,created_at),marketplace_customers(display_name,email)").gte("created_at", strategicFrom.toISOString()).lt("created_at", to.toISOString()),
    admin.from("marketplace_disputes").select("booking_id,status,opened_at,marketplace_bookings(id,job_id,created_at,amount_pence,refunded_amount_pence,payment_status,status,completion_status,payout_hold_status,payout_hold_reason,marketplace_jobs(id,service,service_subtype,postcode,created_at))").order("opened_at", { ascending: false }),
    admin.from("marketplace_reviews").select("rating,created_at").gte("created_at", strategicFrom.toISOString()).lt("created_at", to.toISOString()),
    admin.from("marketplace_providers").select("user_id,marketplace_active,provider_status,created_at"),
    admin.from("marketplace_provider_service_areas").select("provider_id,postcode_district,active"),
  ]);
  const rawJobs = (jobs || []) as OverviewJob[];
  const rawQuotes = (quotes || []) as OverviewQuote[];
  const rawBookings = (bookings || []) as OverviewBooking[];
  const areaCodes = new Map<string, string[]>();
  (providerAreas || []).forEach((area) => { if (area.active) areaCodes.set(area.provider_id, [...(areaCodes.get(area.provider_id) || []), area.postcode_district]); });
  const providerRows = (providers || []).map((provider) => ({ ...provider, postcode_districts: areaCodes.get(provider.user_id) || [] }));
  const metrics = overviewMetrics({ jobs: rawJobs, quotes: rawQuotes, bookings: rawBookings, disputes: (disputes || []) as OverviewDispute[], reviews: (reviews || []) as OverviewReview[], providers: providerRows, from, to });
  const strategicMetrics = overviewMetrics({ jobs: rawJobs, quotes: rawQuotes, bookings: rawBookings, disputes: (disputes || []) as OverviewDispute[], reviews: (reviews || []) as OverviewReview[], providers: providerRows, from: strategicFrom, to });
  const visibleJobs = selectedOutcode === "all" ? metrics.periodJobs : metrics.periodJobs.filter((job) => outcodeOf(job.postcode) === selectedOutcode);
  const visibleJobIds = new Set(visibleJobs.map((job) => job.id));
  const visibleBookings = metrics.genuineBookings.filter((booking) => visibleJobIds.has(booking.job_id));
  const visibleQuoted = [...metrics.quotedJobIds].filter((id) => visibleJobIds.has(id)).length;
  const visibleIssues = metrics.activeIssues.filter((issue) => visibleJobIds.has(relationOne(issue.marketplace_bookings)?.job_id || ""));
  const visibleCompleted = metrics.completed.filter((booking) => visibleJobIds.has(booking.job_id));
  const readinessOutcode = selectedOutcode === "all" ? ACTIVE_MARKETPLACE_POSTCODE_DISTRICTS[0] || strategicMetrics.outcodes[0]?.[0] : selectedOutcode;
  const readiness = readinessOutcode ? expansionReadiness(strategicMetrics, readinessOutcode) : null;
  const recentBookings = [...visibleBookings].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).slice(0, 5);
  const issueRows = visibleIssues.slice(0, 5);
  const noOfferJobs = visibleJobs.filter((job) => !metrics.quotedJobIds.has(job.id));
  const averageHours = metrics.firstQuoteHours.length ? metrics.firstQuoteHours.reduce((a, b) => a + b, 0) / metrics.firstQuoteHours.length : null;
  const activity = [...visibleJobs.slice(0, 5).map((job) => ({ text: `New job posted: ${jobLabel(job)}`, at: job.created_at, href: `/admin/jobs/${job.id}` })), ...rawQuotes.filter((quote) => visibleJobIds.has(quote.job_id)).slice(0, 5).map((quote) => ({ text: "Provider quote received", at: quote.created_at, href: `/admin/jobs/${quote.job_id}` })), ...visibleBookings.slice(0, 5).map((booking) => ({ text: booking.status === "completed" ? "Job completed" : "Booking paid", at: booking.created_at, href: `/admin/marketplace-bookings/${booking.id}` })), ...visibleIssues.slice(0, 3).map((issue) => ({ text: `Customer issue ${label(issue.status)}`, at: issue.opened_at, href: `/admin/marketplace-bookings/${issue.booking_id}` }))].sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime()).slice(0, 5);
  const today = now.toISOString().slice(0, 10);
  const todayBookings = rawBookings.filter((booking) => booking.created_at.slice(0, 10) === today && isGenuineVisibleBooking(booking, selectedOutcode, rawJobs)).length;
  const yesterday = new Date(now); yesterday.setDate(yesterday.getDate() - 1); const yesterdayKey = yesterday.toISOString().slice(0, 10);
  const yesterdayBookings = rawBookings.filter((booking) => booking.created_at.slice(0, 10) === yesterdayKey && isGenuineVisibleBooking(booking, selectedOutcode, rawJobs)).length;
  const failedPayouts = rawBookings.filter((booking) => booking.provider_transfer_status === "failed" && (selectedOutcode === "all" || outcodeOf(relationOne(booking.marketplace_jobs)?.postcode) === selectedOutcode)).length;
  const pendingApprovals = (providers || []).filter((provider) => provider.provider_status === "pending_review").length;
  const attentionUnquoted = metrics.noOfferAfter24h.filter((job) => selectedOutcode === "all" || outcodeOf(job.postcode) === selectedOutcode).length;
  const visibleRevenue = visibleBookings.reduce((sum, booking) => sum + Math.floor(metrics.refundAwareValue(booking) * 10 / 100), 0);
  const visibleServices = Object.entries((selectedRange === "today" ? strategicMetrics.periodJobs : (selectedOutcode === "all" ? strategicMetrics.periodJobs : strategicMetrics.periodJobs.filter((job) => outcodeOf(job.postcode) === selectedOutcode))).reduce<Record<string, number>>((counts, job) => { const key = jobLabel(job); counts[key] = (counts[key] || 0) + 1; return counts; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const availableOutcodes = [...new Set([...(ACTIVE_MARKETPLACE_POSTCODE_DISTRICTS as readonly string[]), ...strategicMetrics.outcodes.map(([code]) => code)])];
  return <div className="mx-auto max-w-[1450px]">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#159548]">MARKETPLACE OPERATIONS</p><h1 className="mt-1 text-[28px] font-black tracking-[-.04em]">Overview</h1><p className="mt-1 text-sm text-[#718099]">Daily operating picture for demand, supply, bookings and issues.</p></div><div className="flex flex-wrap gap-2"><form className="flex gap-2"><select name="range" defaultValue={selectedRange} className="min-h-10 rounded-lg border bg-white px-3 text-xs font-bold"><option value="today">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><select name="outcode" defaultValue={selectedOutcode} className="min-h-10 rounded-lg border bg-white px-3 text-xs font-bold"><option value="all">All Outcodes</option>{availableOutcodes.map((code) => <option key={code} value={code}>{code}</option>)}</select><button className="rounded-lg bg-[#0a8f52] px-4 text-xs font-black text-white">Apply</button></form><Link href="/" className="rounded-lg border bg-white px-4 py-3 text-xs font-black">View live site ↗</Link></div></header>
    <Attention openIssues={visibleIssues.length} unquotedAfter24h={attentionUnquoted} failedPayouts={failedPayouts} pendingApprovals={pendingApprovals} />
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Today’s bookings" value={todayBookings} detail={yesterdayBookings ? `vs ${yesterdayBookings} yesterday` : "No bookings yesterday"} tone="blue" /><Kpi label="Job posts" value={visibleJobs.length} tone="blue" /><Kpi label="Received ≥1 quote" value={visibleQuoted} detail={`${percent(visibleQuoted, visibleJobs.length)} coverage`} tone="blue" /><Kpi label="Bookings" value={visibleBookings.length} detail={`${percent(visibleBookings.length, visibleJobs.length)} of job posts`} tone="green" /><Kpi label="Completed jobs" value={visibleCompleted.length} detail={`${percent(visibleCompleted.length, visibleBookings.length)} of bookings`} tone="green" /><Kpi label="Open issues" value={visibleIssues.length} detail="Needs attention" tone="red" /><Kpi label="Customer paid value" value={moneyPence(visibleBookings.reduce((sum, booking) => sum + metrics.refundAwareValue(booking), 0))} detail="After refunds" tone="blue" /><Kpi label="Quickola revenue" value={moneyPence(visibleRevenue)} detail="Marketplace fee" tone="green" /></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card title="Jobs, quotes and bookings"><Chart jobs={visibleJobs} quotes={rawQuotes} bookings={visibleBookings} visibleJobIds={visibleJobIds} quotedJobIds={metrics.quotedJobIds} from={from} days={daysFor(selectedRange)} /></Card><Card title="Job funnel" subtitle="selected period"><Funnel label="Job posts" value={visibleJobs.length} total={visibleJobs.length} color="bg-[#77b2f4]" /><Funnel label="Received ≥1 quote" value={visibleQuoted} total={visibleJobs.length} color="bg-[#3487e8]" /><Funnel label="Booked" value={visibleBookings.length} total={visibleJobs.length} color="bg-[#67cda2]" /><Funnel label="Completed" value={visibleCompleted.length} total={visibleJobs.length} color="bg-[#83d8bb]" /><Funnel label="Open issues" value={visibleIssues.length} total={visibleBookings.length} color="bg-[#fa8b8b]" /></Card></section>
    <section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card title="Jobs without offers"><Big value={noOfferJobs.length} detail={`${percent(noOfferJobs.length, visibleJobs.length)} of posts`} extra={attentionUnquoted ? `${attentionUnquoted} still unquoted after 24h` : "No jobs unquoted after 24h"} /><Link href="/admin/jobs?withoutOffers=1" className="mt-3 inline-block rounded-lg border px-3 py-2 text-xs font-black">View unquoted jobs →</Link></Card><Card title="Average time to first quote"><Big value={formatHours(averageHours)} detail={`${metrics.firstQuoteHours.length} quoted jobs`} /></Card><Card title={selectedOutcode === "all" ? "Active eligible providers" : `Eligible providers in ${selectedOutcode}`}><Big value={selectedOutcode === "all" ? metrics.activeProviders : strategicMetrics.eligibleProviders.filter((provider) => (provider.postcode_districts || []).some((code) => code.toUpperCase() === selectedOutcode.toUpperCase())).length} detail="Approved and serving this outcode" /><Link href="/admin/providers" className="mt-3 inline-block rounded-lg border px-3 py-2 text-xs font-black">View providers →</Link></Card><Card title="Average customer rating"><Rating average={metrics.averageRating} count={(reviews || []).length} /><Link href="/admin/jobs" className="mt-3 inline-block rounded-lg border px-3 py-2 text-xs font-black">View reviews →</Link></Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-2"><Card title="Jobs with issues"><div className="grid gap-2">{issueRows.map((issue) => { const booking = relationOne(issue.marketplace_bookings); const job = relationOne(booking?.marketplace_jobs); return <Link key={issue.booking_id} href={`/admin/marketplace-bookings/${issue.booking_id}`} className="flex items-center gap-3 rounded-lg border p-3 text-xs"><span className="h-2 w-2 rounded-full bg-[#ed6161]" /><span className="min-w-0 flex-1"><b className="block capitalize">{jobLabel(job)}</b><span className="text-[#718099]">{outcodeOf(job?.postcode)} · {label(issue.status)}</span></span><time className="text-[#8290a3]">{relative(issue.opened_at)}</time><span className="font-black">View</span></Link>})}{!issueRows.length && <p className="rounded-lg bg-[#f0faf3] p-3 text-xs font-bold text-[#16864a]">No open customer issues.</p>}</div><Link href="/admin/marketplace-bookings" className="mt-3 inline-block text-xs font-black">View all issues →</Link></Card><Card title="Outcode expansion readiness" subtitle={`Trailing 30 days · ${readinessOutcode || "No outcode data"}`}>{readiness ? <><div className="flex items-end justify-between"><div><p className="text-3xl font-black">{readinessOutcode}</p><p className="text-sm font-black text-[#b77900]">{readiness.status}</p></div><b className="text-sm">{readiness.passed} / 7 targets</b></div><div className="mt-4 grid gap-2 text-xs">{[`${readiness.jobs.length} jobs / 30`, `${percent(readiness.quoted, readiness.jobs.length)} quote coverage / 80%`, `${percent(readiness.bookings.length, readiness.jobs.length)} booking rate / 50%`, `${readiness.activeProviders} eligible providers / 10`, `${formatHours(readiness.avgHours)} first quote / 4h`, `${percent(readiness.unquotedAfter24h, readiness.jobs.length)} unquoted after 24h / <10%`, `${percent(readiness.issues, readiness.bookings.length)} open issues / <10%`].map((text, index) => <p key={text} className={readiness.checks[index] ? "text-[#16864a]" : "text-[#d44b4b]"}>{readiness.checks[index] ? "✓" : "✕"} {text}</p>)}</div></> : <Empty />}</Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-3"><Card title="Most in-demand services" subtitle="Last 30 days"><div className="grid gap-3">{visibleServices.map(([service, count], index) => <div key={service} className="flex items-center gap-3 text-xs"><span className="w-5 text-[#8290a3]">{index + 1}</span><span className="w-32 truncate capitalize font-bold">{service}</span><span className="h-2 flex-1 rounded-full bg-[#edf1f4]"><span className="block h-2 rounded-full bg-[#4d96ed]" style={{ width: `${(count / Math.max(1, visibleServices[0]?.[1] || 1)) * 100}%` }} /></span><b>{count}</b></div>)}{!visibleServices.length && <Empty />}</div></Card>{selectedOutcode === "all" && <OutcodeTable jobs={strategicMetrics.periodJobs} metrics={strategicMetrics} />}<Card title="Recent bookings"><div className="grid gap-2">{recentBookings.map((booking) => { const job = relationOne(booking.marketplace_jobs); const customer = relationOne(booking.marketplace_customers); const state = getMarketplaceBookingLifecycleState(booking, metrics.issueBookingIds.has(booking.id)); return <Link key={booking.id} href={`/admin/marketplace-bookings/${booking.id}`} className="grid grid-cols-[1fr_auto] gap-2 border-b pb-2 text-xs"><span><b className="block capitalize">{jobLabel(job)}</b><span className="text-[#718099]">{customer?.display_name || customer?.email || "Customer"} · {outcodeOf(job?.postcode)}</span></span><span className="text-right"><b className="block">{moneyPence(metrics.refundAwareValue(booking))}</b><span className="capitalize text-[#718099]">{label(state)}</span></span></Link>})}{!recentBookings.length && <Empty />}</div></Card><Card title="Recent activity"><div className="grid gap-2">{activity.map((event, index) => <Link key={`${event.at}-${index}`} href={event.href} className="flex gap-2 border-b pb-2 text-xs"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#20ae70]" /><span><b className="block">{event.text}</b><time className="text-[#8290a3]">{relative(event.at)}</time></span></Link>)}{!activity.length && <Empty />}</div></Card></section>
  </div>;
}

function Kpi({ label, value, detail, tone }: { label: string; value: string | number; detail?: string; tone: "blue" | "green" | "red" }) { return <article className="rounded-xl border bg-white p-4 shadow-[0_2px_8px_rgba(28,48,76,.03)]"><p className="text-[11px] font-black text-[#748198]">{label}</p><p className={`mt-3 text-2xl font-black tracking-[-.04em] ${tone === "red" ? "text-[#d44b4b]" : "text-[#142745]"}`}>{typeof value === "number" ? value.toLocaleString("en-GB") : value}</p><p className="mt-1 text-[10px] text-[#8290a3]">{detail || "Selected period"}</p></article>; }
function Card({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-4 shadow-[0_2px_8px_rgba(28,48,76,.03)]"><h2 className="mb-4 text-sm font-black text-[#1a2d49]">{title} {subtitle && <span className="font-normal text-[#78879c]">({subtitle})</span>}</h2>{children}</section>; }
function Big({ value, detail, extra }: { value: string | number; detail: string; extra?: string }) { return <><p className="text-3xl font-black tracking-[-.04em] text-[#142745]">{value}</p><p className="mt-1 text-xs text-[#718099]">{detail}</p>{extra && <p className="mt-2 text-[11px] font-bold text-[#b77900]">{extra}</p>}</>; }
function Rating({ average, count }: { average: number | null; count: number }) { if (!count || average == null) return <div className="py-2"><p className="text-lg font-black text-[#718099]">No reviews yet</p></div>; return <div className="py-1"><p className="text-3xl font-black text-[#142745]">{average.toFixed(1)} / 5</p><p className="mt-1 text-lg tracking-[.12em] text-[#f4b321]">{"★".repeat(Math.round(average))}{"☆".repeat(5 - Math.round(average))}</p><p className="text-xs text-[#718099]">{count} marketplace {count === 1 ? "review" : "reviews"}</p></div>; }
function Attention({ openIssues, unquotedAfter24h, failedPayouts, pendingApprovals }: { openIssues: number; unquotedAfter24h: number; failedPayouts: number; pendingApprovals: number }) { const items = [{ label: "open issues", value: openIssues, href: "/admin/marketplace-bookings" }, { label: "job unquoted >24h", value: unquotedAfter24h, href: "/admin/jobs?withoutOffers=1" }, { label: "failed payouts", value: failedPayouts, href: "/admin/marketplace-bookings?status=failed" }, { label: "provider approvals", value: pendingApprovals, href: "/admin/providers?status=pending_review" }]; return <section className="mt-5 flex flex-wrap items-center gap-x-3 gap-y-2 rounded-xl border border-[#e3e9ef] bg-white px-4 py-3 text-xs shadow-[0_2px_8px_rgba(28,48,76,.03)]"><strong className="mr-1 text-[#1a2d49]">Needs attention</strong>{items.map((item, index) => <span key={item.label} className="flex items-center gap-1"><Link href={item.href} className={`font-bold ${item.value ? "text-[#c47a00]" : "text-[#16864a]"}`}>{item.value} {item.label}</Link>{index < items.length - 1 && <span className="text-[#cbd3dc]">·</span>}</span>)}</section>; }
function Funnel({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { return <div className="grid grid-cols-[125px_1fr_35px_35px] items-center gap-2 text-xs"><span>{label}</span><span className="h-5 rounded bg-[#edf1f5]"><span className={`block h-5 rounded ${color}`} style={{ width: `${total ? Math.max(2, value / total * 100) : 0}%` }} /></span><b>{value}</b><span className="text-right text-[#718099]">{percent(value, total)}</span></div>; }
function Chart({ jobs, quotes, bookings, visibleJobIds, quotedJobIds, from, days }: { jobs: OverviewJob[]; quotes: OverviewQuote[]; bookings: OverviewBooking[]; visibleJobIds: Set<string>; quotedJobIds: Set<string>; from: Date; days: number }) { const hourly = days === 1; const count = hourly ? new Date().getHours() + 1 : days; const points = Array.from({ length: count }, (_, index) => { const date = new Date(from); if (hourly) date.setHours(index, 0, 0, 0); else date.setDate(from.getDate() + index); const matches = (value: string) => { const event = new Date(value); return hourly ? event.toISOString().slice(0, 10) === date.toISOString().slice(0, 10) && event.getHours() === index : event.toISOString().slice(0, 10) === date.toISOString().slice(0, 10); }; return { label: hourly ? `${String(index).padStart(2, "0")}:00` : date.toLocaleDateString("en-GB", { day: "numeric", month: "short" }), jobs: jobs.filter((job) => matches(job.created_at)).length, quotes: quotes.filter((quote) => matches(quote.created_at) && quotedJobIds.has(quote.job_id) && visibleJobIds.has(quote.job_id)).length, bookings: bookings.filter((booking) => matches(booking.created_at)).length }; }); const max = Math.max(1, ...points.flatMap((point) => [point.jobs, point.quotes, point.bookings])); const x = (index: number) => 30 + index * 660 / Math.max(1, points.length - 1); const y = (value: number) => 175 - value / max * 140; const line = (key: "jobs" | "quotes" | "bookings") => points.map((point, index) => `${x(index)},${y(point[key])}`).join(" "); return <div><div className="mb-3 flex gap-4 text-[11px] font-bold"><span className="text-[#77b2f4]">● Jobs</span><span className="text-[#3487e8]">● Jobs with ≥1 quote</span><span className="text-[#20ae70]">● Bookings</span></div><svg viewBox="0 0 720 205" className="h-[210px] w-full" role="img" aria-label={hourly ? "Hourly jobs quotes and bookings today" : "Daily jobs quotes and bookings"}><g stroke="#edf0f4"><line x1="30" x2="690" y1="35" y2="35" /><line x1="30" x2="690" y1="90" y2="90" /><line x1="30" x2="690" y1="145" y2="145" /><line x1="30" x2="690" y1="175" y2="175" /></g><polyline fill="none" stroke="#77b2f4" strokeWidth="3" points={line("jobs")} /><polyline fill="none" stroke="#3487e8" strokeWidth="3" points={line("quotes")} /><polyline fill="none" stroke="#20ae70" strokeWidth="3" points={line("bookings")} />{points.map((point, index) => <g key={`${point.label}-${index}`}><title>{`${point.label}: ${point.jobs} jobs, ${point.quotes} jobs with quote, ${point.bookings} bookings`}</title><text x={x(index)} y="199" textAnchor="middle" className="fill-[#8390a1] text-[10px]">{point.label}</text></g>)}</svg></div>; }
function OutcodeTable({ jobs, metrics }: { jobs: OverviewJob[]; metrics: ReturnType<typeof overviewMetrics> }) { return <Card title="Outcode performance"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="border-b text-[10px] uppercase text-[#7a889b]"><tr><th className="py-2">Outcode</th><th>Jobs</th><th>Quote rate</th><th>Booking rate</th><th>Completed</th><th>Open issues</th><th>Status</th></tr></thead><tbody>{metrics.outcodes.map(([code, count]) => { const ids = new Set(jobs.filter((job) => outcodeOf(job.postcode) === code).map((job) => job.id)); const bookings = metrics.genuineBookings.filter((booking) => ids.has(booking.job_id)); const quotes = [...metrics.quotedJobIds].filter((id) => ids.has(id)).length; const done = metrics.completed.filter((booking) => ids.has(booking.job_id)).length; const issues = metrics.activeIssues.filter((issue) => ids.has(relationOne(issue.marketplace_bookings)?.job_id || "")).length; return <tr key={code} className="border-b last:border-0"><td className="py-2 font-black">{code}</td><td>{count}</td><td>{percent(quotes, count)}</td><td>{percent(bookings.length, count)}</td><td>{done}</td><td className={issues ? "font-black text-[#d44b4b]" : ""}>{issues}</td><td className="capitalize">{issues ? "Needs attention" : done ? "Healthy" : "Building"}</td></tr>; })}</tbody></table>{!metrics.outcodes.length && <Empty />}</div></Card>; }
function isGenuineVisibleBooking(booking: OverviewBooking, selectedOutcode: string, jobs: OverviewJob[]) { const job = jobs.find((candidate) => candidate.id === booking.job_id); return isGenuineBooking(booking) && (selectedOutcode === "all" || outcodeOf(job?.postcode) === selectedOutcode); }
function formatHours(hours: number | null) { if (hours == null || !Number.isFinite(hours)) return "—"; return hours < 1 ? `${Math.round(hours * 60)}m` : `${Math.floor(hours)}h ${Math.round(hours % 1 * 60)}m`; }
function Empty() { return <p className="py-3 text-xs text-[#718099]">No data for this view.</p>; }
