import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function OffersPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  await requireAdmin(); const query = await searchParams; const admin = createSupabaseAdminClient();
  const { data } = await admin.from("marketplace_quotes").select("id,job_id,provider_id,bidder_user_id,amount_pence,message,status,created_at,marketplace_jobs(service,service_subtype,postcode),cleaner_profiles(display_name,business_name)").order("created_at", { ascending: false }).limit(250);
  const q = (query.q || "").toLowerCase(); const rows = (data || []).filter((offer) => { const job = Array.isArray(offer.marketplace_jobs) ? offer.marketplace_jobs[0] : offer.marketplace_jobs; const provider = Array.isArray(offer.cleaner_profiles) ? offer.cleaner_profiles[0] : offer.cleaner_profiles; return (!query.status || offer.status === query.status) && (!q || `${job?.service || ""} ${job?.service_subtype || ""} ${job?.postcode || ""} ${provider?.display_name || provider?.business_name || offer.bidder_user_id || ""}`.toLowerCase().includes(q)); });
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Offers</h1><p className="mt-1 text-[#657089]">Marketplace offers and their current state.</p></div><form className="flex gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search offers" className="min-h-11 rounded-xl border px-4" /><select name="status" defaultValue={query.status || ""} className="min-h-11 rounded-xl border px-3"><option value="">All states</option>{Array.from(new Set((data || []).map((offer) => offer.status))).map((status) => <option key={status} value={status}>{status}</option>)}</select><button className="rounded-xl bg-[#071638] px-4 font-black text-white">Filter</button></form></div><div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-[#f7f8fa] text-xs uppercase tracking-wide text-[#657089]"><tr><th className="p-4">Provider</th><th className="p-4">Job</th><th className="p-4">Price</th><th className="p-4">Message</th><th className="p-4">State</th><th className="p-4">Created</th></tr></thead><tbody>{rows.map((offer) => { const job = Array.isArray(offer.marketplace_jobs) ? offer.marketplace_jobs[0] : offer.marketplace_jobs; const provider = Array.isArray(offer.cleaner_profiles) ? offer.cleaner_profiles[0] : offer.cleaner_profiles; return <tr key={offer.id} className="border-b last:border-0"><td className="p-4 font-black">{provider?.display_name || provider?.business_name || offer.bidder_user_id || offer.provider_id || "Provider"}</td><td className="p-4">{job?.service_subtype || job?.service || "Job"}<br /><span className="text-xs text-[#657089]">{job?.postcode}</span></td><td className="p-4 font-black">£{Math.round(offer.amount_pence / 100)}</td><td className="max-w-xs p-4 text-[#526078]">{offer.message || "—"}</td><td className="p-4 capitalize">{offer.status}</td><td className="p-4">{new Date(offer.created_at).toLocaleDateString("en-GB")}</td></tr>})}</tbody></table>{!rows.length && <p className="p-8 text-center text-[#657089]">No matching offers.</p>}</div></div>;
}
