import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function JobsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; category?: string; offers?: string }> }) {
  await requireAdmin(); const query = await searchParams; const admin = createSupabaseAdminClient();
  const { data } = await admin.from("marketplace_jobs").select("id,public_token,service,service_subtype,postcode,budget_amount,status,created_at,contact_name,marketplace_customers(display_name,email),marketplace_quotes(count),marketplace_bookings(payment_status,amount_pence,paid_at)").order("created_at", { ascending: false }).limit(250);
  const statuses = Array.from(new Set((data || []).map((job) => job.status))).sort(); const categories = Array.from(new Set((data || []).map((job) => job.service))).sort(); const q = (query.q || "").toLowerCase();
  const rows = (data || []).filter((job) => { const count = Array.isArray(job.marketplace_quotes) ? Number(job.marketplace_quotes[0]?.count || 0) : 0; const customer = Array.isArray(job.marketplace_customers) ? job.marketplace_customers[0] : job.marketplace_customers; return (!q || `${job.service} ${job.service_subtype || ""} ${job.postcode} ${customer?.display_name || ""} ${customer?.email || ""}`.toLowerCase().includes(q)) && (!query.status || job.status === query.status) && (!query.category || job.service === query.category) && (query.offers !== "none" || count === 0); });
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Jobs</h1><p className="mt-1 text-[#657089]">All marketplace jobs, offers and payment state.</p></div><form className="flex flex-wrap gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search jobs, customer, postcode" className="min-h-11 rounded-xl border px-4" /><select name="status" defaultValue={query.status || ""} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><select name="category" defaultValue={query.category || ""} className="min-h-11 rounded-xl border px-3"><option value="">All categories</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select><button className="min-h-11 rounded-xl bg-[#071638] px-4 font-black text-white">Filter</button></form></div><div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="border-b bg-[#f7f8fa] text-xs uppercase tracking-wide text-[#657089]"><tr><th className="p-4">Job</th><th className="p-4">Customer</th><th className="p-4">Location</th><th className="p-4">Budget</th><th className="p-4">Offers</th><th className="p-4">Payment</th><th className="p-4">Status</th><th className="p-4">Created</th></tr></thead><tbody>{rows.map((job) => { const customer = Array.isArray(job.marketplace_customers) ? job.marketplace_customers[0] : job.marketplace_customers; const count = Array.isArray(job.marketplace_quotes) ? Number(job.marketplace_quotes[0]?.count || 0) : 0; const booking = Array.isArray(job.marketplace_bookings) ? job.marketplace_bookings[0] : job.marketplace_bookings; return <tr key={job.id} className="border-b last:border-0 hover:bg-[#f7f8fa]"><td className="p-4"><Link href={`/admin/jobs/${job.id}`} className="font-black capitalize text-[#167d3c]">{(job.service_subtype || job.service).replaceAll("-", " ")}</Link><p className="text-xs text-[#657089]">{job.service}</p></td><td className="p-4">{customer?.display_name || customer?.email || job.contact_name || "Customer"}</td><td className="p-4">{job.postcode}</td><td className="p-4">{job.budget_amount == null ? "Open budget" : `£${Number(job.budget_amount).toFixed(2).replace(/\.00$/, "")}`}</td><td className="p-4 font-black">{count}</td><td className="p-4 capitalize">{booking?.payment_status || "No booking"}</td><td className="p-4 capitalize">{job.status.replaceAll("_", " ")}</td><td className="p-4">{new Date(job.created_at).toLocaleDateString("en-GB")}</td></tr>})}</tbody></table>{!rows.length && <p className="p-8 text-center text-[#657089]">No matching jobs.</p>}</div></div>;
}
