export const PILOT_PRICING_VERSION="slough-pilot-2026-07-v1";
export const pilotPricingConfig={hourlyRatePence:2200,minimumMinutes:120,roundToMinutes:30,baseMinutes:60,bedroomMinutes:30,bathroomMinutes:25,serviceMinutes:{regular_cleaning:0,deep_cleaning:90,end_of_tenancy:150} as const,frequencyDiscountBasisPoints:{one_off:0,weekly:1000,fortnightly:500,monthly:0} as const,extras:{inside_oven:{label:"Inside oven",minutes:60},inside_fridge:{label:"Inside fridge",minutes:30},inside_windows:{label:"Inside windows",minutes:45},laundry:{label:"Laundry",minutes:30},ironing:{label:"Ironing",minutes:60}} as const,manualReview:{maxBedrooms:6,maxBathrooms:4,maxMinutes:600,rangeUpperBasisPoints:2000}} as const;
export type PilotService=keyof typeof pilotPricingConfig.serviceMinutes;export type PilotFrequency=keyof typeof pilotPricingConfig.frequencyDiscountBasisPoints;export type PilotExtra=keyof typeof pilotPricingConfig.extras;
export type PilotPriceInput={service:PilotService;frequency:PilotFrequency;propertyType:string;bedrooms:number;bathrooms:number;extras:readonly PilotExtra[];serviceAreaStatus:string};
export type PriceLine={key:string;label:string;amountPence:number};
export type PilotQuote={pricingVersion:string;pricingMode:"instant"|"manual_review";requiresManualReview:boolean;estimatedDurationMinutes:number;estimatedPricePence:number;estimatedPriceMaxPence:number|null;breakdown:PriceLine[]};
export function calculatePilotQuote(input:PilotPriceInput):PilotQuote{const beds=Math.max(0,Math.min(20,Math.floor(Number(input.bedrooms)||0))),baths=Math.max(1,Math.min(20,Number(input.bathrooms)||1));let minutes=pilotPricingConfig.baseMinutes+beds*pilotPricingConfig.bedroomMinutes+baths*pilotPricingConfig.bathroomMinutes+pilotPricingConfig.serviceMinutes[input.service];for(const extra of input.extras)minutes+=pilotPricingConfig.extras[extra].minutes;minutes=Math.max(pilotPricingConfig.minimumMinutes,Math.ceil(minutes/pilotPricingConfig.roundToMinutes)*pilotPricingConfig.roundToMinutes);const gross=Math.round(minutes/60*pilotPricingConfig.hourlyRatePence),discountBp=pilotPricingConfig.frequencyDiscountBasisPoints[input.frequency],discount=Math.round(gross*discountBp/10000),total=gross-discount;const extras=input.extras.map(key=>{const item=pilotPricingConfig.extras[key];return{key,label:item.label,amountPence:Math.round(item.minutes/60*pilotPricingConfig.hourlyRatePence)}});const requiresManualReview=input.serviceAreaStatus!=="eligible"||beds>pilotPricingConfig.manualReview.maxBedrooms||baths>pilotPricingConfig.manualReview.maxBathrooms||minutes>pilotPricingConfig.manualReview.maxMinutes;const breakdown:PriceLine[]=[{key:"cleaning_time",label:`Estimated cleaning time (${formatDuration(minutes)})`,amountPence:gross},...extras.map(x=>({...x,amountPence:0}))];if(discount)breakdown.push({key:"frequency_discount",label:`${input.frequency==="weekly"?"Weekly":"Fortnightly"} discount`,amountPence:-discount});return{pricingVersion:PILOT_PRICING_VERSION,pricingMode:requiresManualReview?"manual_review":"instant",requiresManualReview,estimatedDurationMinutes:minutes,estimatedPricePence:total,estimatedPriceMaxPence:requiresManualReview?Math.round(total*(10000+pilotPricingConfig.manualReview.rangeUpperBasisPoints)/10000):null,breakdown}}
export function formatMoney(pence:number){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100)}
export function formatDuration(minutes:number){const hours=Math.floor(minutes/60),remainder=minutes%60;return remainder?`${hours} hr ${remainder} min`:`${hours} hr`}
export function isPilotService(value:string):value is PilotService{return value in pilotPricingConfig.serviceMinutes}export function isPilotFrequency(value:string):value is PilotFrequency{return value in pilotPricingConfig.frequencyDiscountBasisPoints}export function isPilotExtra(value:string):value is PilotExtra{return value in pilotPricingConfig.extras}
