import Link from "next/link";
import { requireBusinessUser } from "@/lib/business/auth";
export default async function Page({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const { supabase, accountId } = await requireBusinessUser();
  const { view } = await searchParams;
  let query = supabase.from("operational_issues").select("id,issue_type,severity,description,status,blocking,created_at,work_items(id,turnover_date,properties(nickname))").eq("account_id", accountId).order("created_at",{ascending:false});
  query = view === "resolved" ? query.eq("status", "resolved") : query.in("status", ["open","acknowledged","waiting_for_owner"]);
  const { data } = await query;
  return <div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="hidden text-sm font-extrabold text-[#2d67b2] sm:block">EXCEPTIONS</p><h1 className="text-2xl font-extrabold tracking-[-.03em] sm:mt-1 sm:text-4xl">Issues</h1></div><nav className="flex gap-1 rounded-lg bg-[#eef2f7] p-1 text-sm font-bold"><Link href="/business/issues" className={`rounded-md px-3 py-2 ${view !== "resolved" ? "bg-white shadow-sm" : ""}`}>Open</Link><Link href="/business/issues?view=resolved" className={`rounded-md px-3 py-2 ${view === "resolved" ? "bg-white shadow-sm" : ""}`}>Resolved</Link></nav></div><p className="mt-2 text-sm text-[#657089]">Blocking issues must be resolved before a property can be marked ready.</p><div className="mt-5 overflow-hidden rounded-xl border bg-white">{data?.length ? <div className="divide-y">{data.map(issue => { const wi = Array.isArray(issue.work_items) ? issue.work_items[0] : issue.work_items; const property = Array.isArray(wi?.properties) ? wi.properties[0] : wi?.properties; return <Link href={`/business/turnovers/${wi?.id}`} key={issue.id} className="grid gap-2 p-4 hover:bg-[#f8fafc] sm:grid-cols-[1fr_140px_110px] sm:p-5"><div><div className="flex items-center gap-2"><h2 className="font-extrabold">{issue.issue_type}</h2>{issue.blocking && <span className="text-xs font-extrabold text-red-700">BLOCKING</span>}</div><p className="mt-1 text-sm text-[#657089]">{property?.nickname} · {issue.description}</p></div><span className="text-sm font-bold capitalize">{issue.severity} severity</span><span className="text-sm font-bold capitalize">{issue.status.replaceAll("_"," ")}</span></Link>})}</div> : <div className="p-8 text-center"><h2 className="text-lg font-extrabold">{view === "resolved" ? "No resolved issues" : "No open issues"}</h2><p className="mt-2 text-sm text-[#657089]">Issues reported during a turnover will appear here.</p></div>}</div></div>;
}
