import Link from "next/link";
import { redirect } from "next/navigation";
import ProviderHeader from "@/app/components/marketplace/ProviderHeader";
import { marketplaceServices } from "@/app/data/marketplace";
import { canProviderBrowseJobs, getMarketplaceProvider, getSignedInUser } from "@/lib/marketplace/provider-access";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { destinationForAccount, getCurrentAccountContext } from "@/lib/auth/account-role";

function shortJobDetail(answers: unknown) {
  if (!answers || typeof answers !== "object" || Array.isArray(answers)) return "";
  return Object.entries(answers as Record<string, unknown>).filter(([, value]) => value !== null && value !== "").slice(0, 2).map(([key, value]) => `${key.replaceAll("_", " ")}: ${Array.isArray(value) ? value.join(", ") : String(value)}`).join(" · ");
}

export default async function WorkPage({ searchParams }: { searchParams: Promise<{ category?: string; sort?: string }> }) {
  const query = await searchParams;
  const account = await getCurrentAccountContext();
  if (account.role !== "provider") redirect(destinationForAccount(account) || "/");
  const provider = await getMarketplaceProvider();
  if (!provider) {
    const user = await getSignedInUser();
    redirect(user ? "/pro/login?error=not-approved" : "/pro/login");
  }
  if (provider.providerStatus === "action_required") redirect("/work/onboarding");
  if (["pending_review", "suspended"].includes(provider.providerStatus)) {
    return <WorkspaceShell><ProviderStatusCard provider={provider} /></WorkspaceShell>;
  }
  const admin = createSupabaseAdminClient();
  const { data: profile } = await admin.from("marketplace_providers").select("service_area,marketplace_provider_services(category_slug,active),marketplace_provider_service_areas(postcode_district,active)").eq("user_id", provider.user.id).maybeSingle();
  const activeServices = new Set((profile?.marketplace_provider_services || []).filter((item) => item.active).map((item) => item.category_slug));
  const activeAreas = (profile?.marketplace_provider_service_areas || []).filter((item) => item.active).map((item) => item.postcode_district);
  if (!canProviderBrowseJobs(provider, activeServices.size)) return <WorkspaceShell><ProviderStatusCard provider={provider} /></WorkspaceShell>;
  const supabase = await createSupabaseServerClient();
  const { data: matches } = await supabase.rpc("get_marketplace_browse_opportunities");
  const ids = (matches || []).map((job: { id: string }) => job.id);
  const { data: jobs } = ids.length ? await admin.from("marketplace_jobs").select("id,public_token,service,service_subtype,postcode,budget_amount,requested_timing,optional_note,pricing_answers,created_at,status").in("id", ids).order("created_at", { ascending: false }) : { data: [] };
  const filtered = (jobs || []).filter((job) => !query.category || job.service === query.category).sort((a, b) => query.sort === "oldest" ? String(a.created_at).localeCompare(String(b.created_at)) : String(b.created_at).localeCompare(String(a.created_at)));
  const availableCategories = marketplaceServices.filter((service) => activeServices.has(service.slug));
  return <WorkspaceShell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black text-[#159548]">PRIVATE PROVIDER WORK</p><h1 className="mt-2 text-4xl font-black">Jobs near you</h1><p className="mt-2 text-[#657089]">Matching {activeAreas.join(", ") || profile?.service_area || "your service area"} · {filtered.length} available</p></div><Link href="/work/profile" className="min-h-11 rounded-xl border border-[#dbe1ea] px-4 py-3 text-sm font-black">Edit profile</Link></div><form className="mt-6 flex flex-wrap gap-2"><select name="category" defaultValue={query.category || ""} className="min-h-11 rounded-xl border border-[#dbe1ea] bg-white px-3 text-sm font-black"><option value="">All services</option>{availableCategories.map((service) => <option key={service.slug} value={service.slug}>{service.shortName}</option>)}</select><select name="sort" defaultValue={query.sort || "newest"} className="min-h-11 rounded-xl border border-[#dbe1ea] bg-white px-3 text-sm font-black"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select><button className="min-h-11 rounded-xl bg-[#061b3f] px-4 text-sm font-black text-white">Apply</button></form><div className="mt-7 grid gap-4 lg:grid-cols-2">{filtered.map((job) => <article key={job.id} className="rounded-3xl border border-[#e7ebef] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#159548]">{job.service}</p><h2 className="mt-2 text-xl font-black capitalize">{(job.service_subtype || job.service).replaceAll("-", " ")}</h2></div><span className="whitespace-nowrap text-sm font-black text-[#167d3c]">{job.budget_amount == null ? "Open budget" : `£${Number(job.budget_amount).toFixed(2).replace(/\.00$/, "")}`}</span></div><p className="mt-3 text-sm text-[#657089]">{job.postcode} · {job.requested_timing || "Flexible timing"}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#39465b]">{job.optional_note || shortJobDetail(job.pricing_answers) || "Customer has not added a description."}</p><p className="mt-4 text-xs font-bold text-[#8390a1]">Posted {new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(job.created_at))}</p><Link href={`/work/jobs/${job.id}`} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#23a955] px-5 font-black text-[#061b3f]">View job</Link></article>)}{!filtered.length && <EmptyState title="No matching jobs right now. We’ll show new jobs here when they match your services and area." action="Edit services and area" href="/work/profile" />}</div></WorkspaceShell>;
}

function WorkspaceShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><ProviderHeader /><section className="mx-auto max-w-5xl px-5 py-10 sm:px-8">{children}</section></main>; }
function EmptyState({ title, action, href }: { title: string; action: string; href: string }) { return <div className="rounded-3xl border border-dashed border-[#cfd8d2] bg-white p-8 text-center text-[#657089]"><p className="mx-auto max-w-xl leading-7">{title}</p><Link href={href} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#23a955] px-5 font-black text-[#061b3f]">{action}</Link></div>; }
function ProviderStatusCard({ provider }: { provider: Awaited<ReturnType<typeof getMarketplaceProvider>> }) { if (!provider) return null; const status = provider.providerStatus; const stripe = provider.stripeStatus; const pending = status === "pending_review"; const title = pending ? "Your profile is being reviewed" : status === "suspended" ? "Provider access is suspended" : status === "approved" && stripe !== "ready" ? "One last step" : "Finish setting up your profile"; const body = pending ? "Your application is with Quickola for approval. You’ll be able to send quotes once your profile is approved." : status === "approved" ? "Your profile is approved, but payout setup is still needed before you can send quotes." : status === "suspended" ? "Quoting is disabled while this profile is suspended. Contact Quickola if you need help." : "Complete your basic profile and choose services before entering the provider workspace."; const review = status === "suspended" ? "Suspended" : pending ? "Awaiting approval" : status === "approved" ? "Approved" : "Setup incomplete"; const payout = stripe === "ready" ? "Ready" : stripe === "verification_pending" ? "Verifying" : "Not set up"; return <div className="rounded-3xl border border-[#e7ebef] bg-white p-8"><p className="text-xs font-black uppercase tracking-[.14em] text-[#159548]">PROVIDER STATUS</p><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-3 max-w-xl leading-7 text-[#657089]">{body}</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm font-black text-[#526078]"><span>Review · {review}</span><span>Payouts · {payout}</span></div>{pending && <div className="mt-6 rounded-2xl bg-[#f5fbf6] p-5 text-sm leading-6 text-[#39465b]"><p className="font-black text-[#167d3c]">What happens next?</p><p className="mt-2">We’ll let you know when your profile is approved.</p></div>}{status === "approved" && stripe !== "ready" && <Link href="/work/onboarding?setup=1" className="mt-7 inline-flex min-h-11 items-center rounded-xl bg-[#23a955] px-5 font-black text-[#061b3f]">Continue setup</Link>}{status !== "approved" && status !== "pending_review" && status !== "suspended" && <Link href="/work/onboarding" className="mt-7 inline-flex min-h-11 items-center rounded-xl bg-[#23a955] px-5 font-black text-[#061b3f]">Finish setup</Link>}</div>; }
