import Link from "next/link";
import ProviderHeader from "@/app/components/marketplace/ProviderHeader";
import { startProviderPayoutSetup } from "./actions";

export default function PendingReview({ stripeStatus }: { stripeStatus: string }) {
  const payoutsReady = stripeStatus === "ready";
  const verificationPending = stripeStatus === "verification_pending";
  return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><ProviderHeader /><section className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><div className="rounded-3xl border border-[#e7ebef] bg-white p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.15em] text-[#159548]">PROVIDER APPLICATION</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Your profile has been submitted</h1><p className="mt-3 max-w-2xl leading-7 text-[#657089]">Thanks — we have everything we need. Quickola will now review your provider profile before you can start sending quotes.</p><div className="mt-8 grid gap-3 rounded-2xl bg-[#f7f8fa] p-5 font-bold"><p className="text-[#167d3c]">✓ Profile submitted</p>{payoutsReady ? <p className="text-[#167d3c]">✓ Payouts connected</p> : verificationPending ? <p className="text-[#8a5a00]">⏳ Payout details submitted — Stripe is reviewing them</p> : <div><p className="text-[#8a5a00]">Action needed: Finish payout setup</p><form action={startProviderPayoutSetup} className="mt-3"><button className="min-h-11 rounded-xl bg-[#23a955] px-4 font-black text-[#061b3f]">Continue Stripe setup</button></form></div>}<p className="text-[#8a5a00]">⏳ Quickola review</p></div><h2 className="mt-8 text-xl font-black">What happens next?</h2><p className="mt-2 leading-7 text-[#657089]">We&apos;ll review your profile and let you know when you&apos;re approved. Once approved, you&apos;ll be able to view suitable jobs and send customers quotes.</p><p className="mt-5 text-sm leading-6 text-[#657089]">You don&apos;t need to submit anything again unless we contact you for more information.</p><Link href="/work" className="mt-7 inline-flex min-h-11 items-center rounded-xl border border-[#dbe1ea] px-5 font-black">Back to provider home</Link></div></section></main>;
}
