import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params; const admin = createSupabaseAdminClient();
  const [{ data: job }, { data: offers }] = await Promise.all([
    admin.from("marketplace_jobs").select("*,marketplace_customers(display_name,email,mobile),marketplace_job_photos(id,storage_path),marketplace_bookings(id,quote_id,conversation_id,amount_pence,currency,platform_fee_pence,payment_status,stripe_checkout_session_id,stripe_payment_intent_id,paid_at,status)").eq("id", id).maybeSingle(),
    admin.from("marketplace_quotes").select("id,provider_id,bidder_user_id,amount_pence,availability_text,message,status,created_at,marketplace_providers(display_name,business_name)").eq("job_id", id).order("created_at", { ascending: true }),
  ]);
  if (!job) notFound(); const customer = Array.isArray(job.marketplace_customers) ? job.marketplace_customers[0] : job.marketplace_customers; const booking = Array.isArray(job.marketplace_bookings) ? job.marketplace_bookings[0] : job.marketplace_bookings;
  return <div className="mx-auto max-w-4xl"><Link href="/admin/jobs" className="text-sm font-black text-[#167d3c]">← Jobs</Link><div className="mt-4 rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-[#159548]">{job.service}</p><h1 className="mt-2 text-3xl font-black capitalize">{(job.service_subtype || job.service).replaceAll("-", " ")}</h1><p className="mt-2 text-[#657089]">{job.postcode} · {job.requested_timing || "Flexible timing"}</p></div><span className="rounded-full bg-[#eef8f1] px-3 py-1 text-sm font-black capitalize text-[#167d3c]">{job.status.replaceAll("_", " ")}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info label="Customer" value={customer?.display_name || customer?.email || job.contact_name || "Customer"} /><Info label="Budget" value={job.budget_amount == null ? "Open budget" : `£${Number(job.budget_amount).toFixed(2).replace(/\.00$/, "")}`} /><Info label="Created" value={new Date(job.created_at).toLocaleString("en-GB")} /></div>{job.optional_note && <p className="mt-6 whitespace-pre-wrap leading-7 text-[#39465b]">{job.optional_note}</p>}<section className="mt-8 border-t pt-6"><h2 className="text-2xl font-black">Offers ({offers?.length || 0})</h2><div className="mt-4 grid gap-3">{offers?.map((offer) => { const provider = Array.isArray(offer.marketplace_providers) ? offer.marketplace_providers[0] : offer.marketplace_providers; return <article key={offer.id} className="rounded-2xl bg-[#f7f8fa] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{provider?.display_name || provider?.business_name || offer.bidder_user_id || offer.provider_id || "Provider"}</p><p className="mt-1 text-sm capitalize text-[#657089]">{offer.status} · {offer.availability_text || "Flexible"}</p></div><p className="text-2xl font-black">£{Math.round(offer.amount_pence / 100)}</p></div>{offer.message && <p className="mt-3 text-sm leading-6 text-[#526078]">{offer.message}</p>}</article>})}{!offers?.length && <p className="text-[#657089]">No offers yet.</p>}</div></section></div></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f7f8fa] p-4"><p className="text-xs font-black uppercase tracking-wide text-[#707b8d]">{label}</p><p className="mt-2 font-black">{value}</p></div>; }
