"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import { getCustomerSignUpRedirect } from "@/lib/auth-redirects";
import { safeInternalNextPath } from "@/lib/app-url";

export default function CustomerAuthForm() {
  const params = useSearchParams(); const router = useRouter();
  const draft = /^[0-9a-f-]{36}$/i.test(params.get("draft") || "") ? params.get("draft")! : "";
  const requestedNext = params.get("next");
  const next = safeInternalNextPath(params.get("next"), "/my-jobs");
  const [mode, setMode] = useState<"signin" | "signup">(params.get("mode") === "signup" ? "signup" : "signin"); const [emailOpen, setEmailOpen] = useState(params.get("mode") === "signup" || params.get("confirmed") === "1" || Boolean(params.get("error"))); const [pending, setPending] = useState(false); const [message, setMessage] = useState(params.get("confirmed") === "1" ? "Email confirmed. Sign in to post your job." : params.get("error") === "oauth" ? "Google sign-in was cancelled or could not be completed. Please try again." : params.get("error") === "profile" ? "Your account was verified, but we couldn’t finish setting up your customer profile. Please try again." : params.get("error") ? "We couldn’t complete that confirmation. Please try again." : "");
  async function continueWithGoogle() { setPending(true); setMessage(""); const redirectTo = new URL("/auth/callback", window.location.origin); if (draft) redirectTo.searchParams.set("draft", draft); if (requestedNext && next) redirectTo.searchParams.set("next", next); const { error } = await createSupabaseBrowserClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: redirectTo.toString() } }); if (error) { setMessage("Google sign-in is not available yet. Use email instead or contact support."); setPending(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const email = String(form.get("email") || ""); const password = String(form.get("password") || ""); const auth = createSupabaseBrowserClient({ authForm: true });
    const result = mode === "signup" ? await auth.auth.signUp({ email, password, options: { emailRedirectTo: getCustomerSignUpRedirect(draft) , data: { account_kind: "quickola_customer" } } }) : await auth.auth.signInWithPassword({ email, password });
    if (result.error) { setMessage("We couldn’t continue. Check your details and try again."); setPending(false); return; }
    if (mode === "signup" && !result.data.session) { setMessage("Check your email to confirm your account, then return here to post your job."); setPending(false); return; }
    router.replace(draft ? `/auth/customer/publish?draft=${draft}` : requestedNext ? next : next === "/my-jobs" ? "/portal" : next);
  }
  return <div className="grid gap-5 rounded-3xl bg-white p-7 shadow-lg"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#159548]">Quickola account</p><h1 className="mt-2 text-3xl font-black text-[#061b3f]">{draft ? "Save & post your job" : mode === "signup" ? "Create your Quickola account" : "Sign in to Quickola"}</h1><p className="mt-2 text-sm leading-6 text-[#657089]">{draft ? "Continue with Google to post your job and receive quotes." : "View your jobs and offers."}</p></div><button type="button" onClick={continueWithGoogle} disabled={pending} className="flex min-h-12 items-center justify-center gap-3 rounded-xl border border-[#dbe1ea] bg-white font-black text-[#061b3f] shadow-sm disabled:opacity-60"><GoogleIcon />{pending ? "Opening Google…" : "Continue with Google"}</button>{!emailOpen && <button type="button" onClick={() => setEmailOpen(true)} className="text-sm font-bold text-[#167d3c]">Use email instead</button>}{emailOpen && <form onSubmit={submit} className="grid gap-4 border-t border-[#e9edf1] pt-5"><label className="font-bold text-[#061b3f]">Email<input name="email" type="email" required defaultValue={params.get("email") || ""} className="mt-2 w-full rounded-xl border border-[#dbe1ea] px-4 py-3" /></label><label className="font-bold text-[#061b3f]">Password<input name="password" type="password" required minLength={6} className="mt-2 w-full rounded-xl border border-[#dbe1ea] px-4 py-3" /></label>{message && <p role="status" className="rounded-xl bg-[#f2f7f4] p-3 text-sm font-bold text-[#315d43]">{message}</p>}<button disabled={pending} className="min-h-12 rounded-xl bg-[#23a955] font-black text-white disabled:opacity-60">{pending ? "Working…" : mode === "signup" ? "Create account & post" : draft ? "Continue & post job" : "Continue with email"}</button><button type="button" onClick={() => setMode(mode === "signin" ? "signup" : "signin")} className="text-sm font-bold text-[#167d3c]">{mode === "signin" ? "New to Quickola? Create an account" : "Already have an account? Sign in"}</button></form>}{message && !emailOpen && <p role="status" className="rounded-xl bg-[#fff3e7] p-3 text-sm font-bold text-[#974c00]">{message}</p>}</div>;
}

function GoogleIcon() { return <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24"><path fill="#4285F4" d="M21.35 12.27c0-.72-.06-1.25-.2-1.8H12v3.41h5.37a4.58 4.58 0 0 1-1.99 3v2.5h3.22c1.89-1.74 2.75-4.3 2.75-7.11Z"/><path fill="#34A853" d="M12 21.75c2.7 0 4.97-.9 6.63-2.44l-3.22-2.5c-.9.6-2.05.96-3.41.96-2.62 0-4.84-1.77-5.64-4.15H3.03v2.58A10 10 0 0 0 12 21.75Z"/><path fill="#FBBC05" d="M6.36 13.62A5.98 5.98 0 0 1 6.05 12c0-.56.1-1.1.31-1.62V7.8H3.03A9.99 9.99 0 0 0 2 12c0 1.61.39 3.13 1.03 4.2l3.33-2.58Z"/><path fill="#EA4335" d="M12 6.23c1.47 0 2.79.5 3.83 1.5l2.87-2.87C16.96 3.2 14.7 2.25 12 2.25a10 10 0 0 0-8.97 5.54l3.33 2.59C7.16 8 9.38 6.23 12 6.23Z"/></svg>; }
