import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { requireBusinessUser } from "@/lib/business/auth";
import TurnoverStatus from "../../components/TurnoverStatus";
import { assignWorker, cancelAssignment, resolveIssue, updateIssue } from "../../str-actions";
import { currentAssignment, turnoverActionReason } from "@/lib/turnovers/presentation";
import CopyCleanerJobLink from "../../cleaners/CopyCleanerJobLink";
import { buildAbsoluteAppUrl } from "@/lib/app-url";
import { formatDisplayName } from "@/lib/display-name";
import { collapseActivityEvents, formatActivityEvent } from "@/lib/activity-presentation";
import ReassignCleanerForm from "./ReassignCleanerForm";

const related = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, accountId } = await requireBusinessUser();
  const [{ data: item }, { data: availableWorkers }] = await Promise.all([
    supabase.from("work_items").select("*,properties(nickname,address_line_1,city,postcode,bedrooms,bathrooms,default_checkout_time,default_checkin_time,estimated_turnover_minutes),assignments(status,assigned_at,response_due_at,workers(id,display_name,company_name)),checklist_tasks(id,label,mandatory,completed,photo_required,note_required,note,section_title),evidence_submissions(id,evidence_type,storage_path,caption,created_at),operational_issues(id,issue_type,severity,description,status,blocking,created_at),activity_events(id,event_type,description,created_at,metadata,work_item_id,properties(nickname),workers(display_name))").eq("id", id).eq("account_id", accountId).maybeSingle(),
    supabase.from("workers").select("id,display_name,company_name").eq("account_id", accountId).eq("status", "active").order("display_name"),
  ]);
  if (!item) notFound();
  const property = related(item.properties);
  const assignment = currentAssignment(item.assignments);
  const worker = related(assignment?.workers || null) as { id?: string; display_name?: string; company_name?: string | null } | null;
  const tasks = item.checklist_tasks || [], completed = tasks.filter((task: {completed:boolean}) => task.completed).length;
  const reasons = item.readiness_result?.blocking_reasons || [];
  const evidencePaths = item.evidence_submissions.map((file: {storage_path:string}) => file.storage_path);
  const { data: signedEvidence } = evidencePaths.length
    ? await supabase.storage.from("turnover-evidence").createSignedUrls(evidencePaths, 900)
    : { data: [] };
  const evidence = item.evidence_submissions.map((file: {id:string;storage_path:string;evidence_type:string;caption:string|null;created_at:string}, index:number) => ({
    ...file, signedUrl: signedEvidence?.[index]?.signedUrl || null,
  }));
  const waiting=item.status==="awaiting_response";
  const preStart=["unassigned","awaiting_response","accepted","en_route","arrived"].includes(item.status);
  const workerName=formatDisplayName(worker?.display_name) || "The cleaner";
  return <div className="portal-page max-w-6xl">
    <Link href="/business/turnovers" className="text-sm font-bold text-[#526078]">← Turnovers</Link>
    <header className="mt-4 flex flex-col gap-4 border-b border-[#dfe4eb] pb-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-extrabold text-[#2d67b2]">{new Intl.DateTimeFormat("en-GB",{dateStyle:"long"}).format(new Date(item.turnover_date))}</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.03em]">{property?.nickname}</h1><p className="mt-2 text-[#657089]">{property?.address_line_1}, {property?.city}, {property?.postcode}</p></div><TurnoverStatus status={item.status} /></header>
    {item.status === "ready" ? <section className="mt-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-extrabold text-emerald-800">PROPERTY READY</p><h2 className="mt-1 text-lg font-extrabold text-emerald-950">{property?.nickname} is guest-ready</h2><p className="mt-1 text-sm text-emerald-900">Verified {new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.ready_at))} · {workerName} · {completed} mandatory tasks · {item.evidence_submissions.length} evidence files</p></section> : waiting ? <section className="mt-5 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3"><h2 className="font-extrabold text-blue-950">Cleaner response requested</h2><p className="mt-0.5 text-sm text-blue-900">{workerName} has been asked to complete this turnover.</p></section> : <section className="mt-5 rounded-xl border border-amber-100 bg-amber-50 p-4"><h2 className="font-extrabold text-amber-950">{turnoverActionReason(item)}</h2><p className="mt-1 text-sm text-amber-900">{reasons.length ? `Property cannot be marked ready: ${reasons.join("; ")}.` : "Readiness will be evaluated when completion is submitted."}</p></section>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_.8fr]">
      <div className="grid gap-6">
        <section className="portal-card"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-extrabold">Schedule</h2><span className="text-xs font-bold text-[#657089]">{item.estimated_duration_minutes === property?.estimated_turnover_minutes ? "Using property defaults" : "Overridden for this turnover"}</span></div><dl className="mt-4 grid gap-4 sm:grid-cols-3">{[["Guest checkout",item.guest_checkout_at],["Cleaner access",item.access_start_at],["Next check-in",item.next_checkin_at]].map(([label,value]) => <div key={label}><dt className="text-xs font-bold text-[#748096]">{label.toUpperCase()}</dt><dd className="mt-1 font-bold">{new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/London"}).format(new Date(value))}</dd></div>)}</dl></section>
        {waiting ? <details className="portal-card p-4"><summary className="grid cursor-pointer list-none grid-cols-[1fr_auto_auto] items-center gap-4"><span><strong className="block">Cleaning checklist</strong><span className="mt-1 block text-sm text-[#657089]">The cleaner will complete these after accepting.</span></span><span className="text-sm font-bold text-[#657089]">{tasks.length} tasks</span><span className="text-sm font-extrabold text-[#16467e]">View checklist</span></summary><div className="mt-3 divide-y border-t">{tasks.map((task: {id:string;label:string;mandatory:boolean;section_title:string}) => <div key={task.id} className="py-3"><p className="font-bold">{task.label}</p><p className="text-xs text-[#748096]">{task.section_title}{task.mandatory ? " · Required" : ""}</p></div>)}</div></details> : <section className="portal-card p-5"><div className="flex justify-between"><h2 className="text-lg font-extrabold">Checklist</h2><p className="text-sm font-bold text-[#657089]">{completed} of {tasks.length}</p></div><div className="mt-4 divide-y">{tasks.length ? tasks.map((task: {id:string;label:string;completed:boolean;mandatory:boolean;section_title:string}) => <div key={task.id} className="flex gap-3 py-3"><span aria-hidden="true" className={task.completed ? "text-emerald-600" : "text-[#a2abba]"}>{task.completed ? "●" : "○"}</span><div><p className="font-bold">{task.label}</p><p className="text-xs text-[#748096]">{task.section_title}{task.mandatory ? " · Required" : ""}</p></div></div>) : <p className="py-3 text-sm text-[#657089]">No checklist tasks were copied. Configure the property standard before the next turnover.</p>}</div></section>}
        {preStart ? <section className="portal-card p-4"><h2 className="font-extrabold">Evidence</h2><p className="mt-1 text-sm text-[#657089]">Evidence can be submitted after the cleaner starts the turnover.</p></section> : <section className="portal-card p-5"><div><h2 className="text-lg font-extrabold">Evidence</h2><p className="mt-1 text-sm text-[#657089]">{evidence.length} securely stored files · links expire after 15 minutes</p></div>{evidence.length?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{evidence.map((file:{id:string;signedUrl:string|null;evidence_type:string;caption:string|null;created_at:string})=><figure key={file.id} className="overflow-hidden rounded-lg border bg-[#f4f6f9]">{file.signedUrl?<a href={file.signedUrl} target="_blank" rel="noreferrer" className="block outline-none focus-visible:ring-4 focus-visible:ring-[#2d67b2]/25"><Image src={file.signedUrl} alt={file.caption||`${file.evidence_type.replaceAll("_"," ")} evidence`} width={480} height={360} className="aspect-[4/3] w-full object-cover"/></a>:<div className="grid aspect-[4/3] place-items-center p-3 text-center text-xs font-bold text-[#59677d]">Preview unavailable</div>}<figcaption className="p-2 text-xs font-semibold capitalize text-[#59677d]">{file.caption||file.evidence_type.replaceAll("_"," ")}</figcaption></figure>)}</div>:<p className="mt-3 text-sm text-[#657089]">No evidence uploaded yet.</p>}</section>}
      </div>
      <aside className="grid content-start gap-4">
        <section className="portal-card p-5"><h2 className="text-lg font-extrabold">Assignment</h2><p className="mt-3 font-bold">{assignment ? workerName : "No cleaner assigned"}</p><p className="mt-1 text-sm text-[#657089]">{waiting ? "Awaiting cleaner response" : assignment?.status?.replaceAll("_"," ") || "Unassigned"}</p>{assignment && item.status !== "cancelled" && <div className="mt-4"><CopyCleanerJobLink jobLink={buildAbsoluteAppUrl(`/cleaner/turnovers/${id}`)} /></div>}{!["ready","cancelled","evidence_submitted"].includes(item.status)&&(assignment?<ReassignCleanerForm turnoverId={id} currentWorkerId={worker?.id} workers={(availableWorkers||[]).map(candidate=>({...candidate,display_name:formatDisplayName(candidate.display_name)}))}/>:<form action={assignWorker} className="mt-4 border-t pt-4"><input type="hidden" name="turnoverId" value={id}/><label className="text-sm font-bold">Assign cleaner<select name="workerId" required defaultValue="" className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="" disabled>Select cleaner</option>{availableWorkers?.map(candidate=><option key={candidate.id} value={candidate.id}>{formatDisplayName(candidate.display_name)}{candidate.company_name?` · ${candidate.company_name}`:""}</option>)}</select></label><button className="mt-2 min-h-10 rounded-lg border px-4 text-sm font-extrabold text-[#16467e]">Assign</button></form>)}{assignment&&<form action={cancelAssignment} className="mt-1"><input type="hidden" name="turnoverId" value={id}/><button className="min-h-10 text-sm font-bold text-red-700">Cancel assignment</button></form>}</section>
        <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-extrabold">Issues</h2><div className="mt-3 grid gap-3">{item.operational_issues.length ? item.operational_issues.map((issue: {id:string;issue_type:string;description:string;status:string;blocking:boolean;severity:string}) => <article key={issue.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><p className="font-extrabold">{issue.issue_type}</p>{issue.blocking && <span className="text-xs font-extrabold text-red-700">BLOCKING</span>}</div><p className="mt-1 text-sm text-[#657089]">{issue.description}</p><p className="mt-2 text-xs font-bold capitalize text-[#59677d]">{issue.status.replaceAll("_"," ")} · {issue.severity} severity</p>{!["resolved","closed"].includes(issue.status) && <div className="mt-3 grid gap-3"><form action={updateIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><input type="hidden" name="issueAction" value={issue.blocking?"downgrade":"acknowledge"}/><label className="text-sm font-bold">{issue.blocking?"Reason to make non-blocking":"Owner response"}<textarea name="ownerResponse" required className="mt-1 min-h-20 w-full rounded-lg border p-2"/></label><button className="mt-2 min-h-10 rounded-lg border px-3 text-sm font-bold">{issue.blocking?"Make non-blocking":"Acknowledge"}</button></form><form action={resolveIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><label className="text-sm font-bold">Resolution<input name="resolution" required className="mt-1 min-h-10 w-full rounded-lg border px-3"/></label><button className="mt-2 min-h-10 rounded-lg bg-[#071f49] px-3 text-sm font-bold text-white">Resolve issue</button></form></div>}</article>) : <p className="text-sm text-[#657089]">No open issues.</p>}</div></section>
        <section className="portal-card p-5"><h2 className="text-lg font-extrabold">Activity</h2><ol className="mt-3 border-l pl-4">{collapseActivityEvents(item.activity_events||[]).map((event) => {const text=formatActivityEvent({...event,work_items:{properties:property,assignments:item.assignments}});return <li key={event.id} className="pb-4"><p className="text-sm font-bold">{text.title}</p>{text.context&&<p className="text-xs text-[#657089]">{text.context}</p>}<time className="text-xs text-[#748096]">{new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.created_at))}</time></li>})}</ol></section>
      </aside>
    </div>
  </div>;
}
