import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusinessUser } from "@/lib/business/auth";
import TurnoverStatus from "../../components/TurnoverStatus";
import { assignWorker, cancelAssignment, resendWorkerInvitation, resolveIssue, updateIssue } from "../../str-actions";
import { currentAssignment } from "@/lib/turnovers/presentation";
import { getOperatorState } from "@/lib/turnovers/operator-lifecycle";
import { formatDisplayName } from "@/lib/display-name";
import { formatDisplayAddress } from "@/lib/display-address";
import { collapseActivityEvents, formatActivityEvent } from "@/lib/activity-presentation";
import ReassignCleanerForm from "./ReassignCleanerForm";
import CleanerCreationDialog from "./CleanerCreationDialog";
import ChecklistTaskDialog from "./ChecklistTaskDialog";

const related = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;
const clock = (value: string) => new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(value));
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short" }).format(new Date(`${value}T12:00:00Z`));
export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams?: Promise<{ workerAdded?: string; workerId?: string; taskAdded?: string }> }) {
  const { id } = await params;
  const query = searchParams ? await searchParams : {};
  const { supabase, accountId } = await requireBusinessUser();
  const [{ data: item }, { data: availableWorkers }] = await Promise.all([
    supabase.from("work_items").select("*,properties(nickname,address_line_1,city,postcode),assignments(status,assigned_at,response_due_at,workers(id,display_name,company_name)),checklist_tasks(id,label,section_title,mandatory,completed,photo_required,note_required),evidence_submissions(id,evidence_type,storage_path,caption,created_at),operational_issues(id,issue_type,severity,description,status,blocking,created_at),activity_events(id,event_type,description,created_at,metadata,work_item_id,properties(nickname),workers(display_name))").eq("id", id).eq("account_id", accountId).maybeSingle(),
    supabase.from("workers").select("id,display_name,company_name").eq("account_id", accountId).eq("status", "active").order("display_name"),
  ]);
  if (!item) notFound();
  const property = related(item.properties);
  const assignment = currentAssignment(item.assignments);
  const dueAt = (assignment as { response_due_at?: string } | undefined)?.response_due_at;
  const worker = related(assignment?.workers || null) as { id?: string; display_name?: string; company_name?: string | null } | null;
  const workerName = formatDisplayName(worker?.display_name) || "—";
  const propertyName = formatDisplayName(property?.nickname || item.property_public_name) || "—";
  const state = getOperatorState(item.status);
  const tasks = item.checklist_tasks || [];
  const completed = tasks.filter((t: { completed: boolean }) => t.completed).length;
  const progressPercent = tasks.length ? Math.round((completed / tasks.length) * 100) : 0;
  const issues = item.operational_issues || [];
  const openIssues = issues.filter((i: { status: string }) => !["resolved", "closed"].includes(i.status));
  const active = !["ready", "cancelled"].includes(item.status);
  const address = formatDisplayAddress([property?.address_line_1, property?.city, property?.postcode], item.property_general_area || "—");
  const events = collapseActivityEvents(item.activity_events || []).filter((e) => ["turnover_accepted", "turnover_arrived", "turnover_in_progress", "action_required", "property_ready", "issue_reported"].some((key) => e.event_type.includes(key))).slice(0, 3);
  const sections = new Map<string, { done: number; total: number; tasks: typeof tasks }>();
  for (const task of tasks as Array<{ section_title: string; completed: boolean }>) {
    const current = sections.get(task.section_title) || { done: 0, total: 0, tasks: [] as typeof tasks };
    current.total += 1;
    if (task.completed) current.done += 1;
    current.tasks.push(task);
    sections.set(task.section_title, current);
  }
  const requestedWorkerId = query.workerAdded === "1" ? query.workerId : "";
  const newWorkerId = availableWorkers?.some((candidate) => candidate.id === requestedWorkerId) ? requestedWorkerId : "";
  return <div className="portal-page max-w-6xl">
    <Link href="/business/turnovers" className="text-sm font-bold text-[#526078]">← Cleans</Link>
    <header className="mt-4 rounded-xl border bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h1 className="text-2xl font-extrabold sm:text-3xl">{propertyName}</h1><p className="mt-2 text-sm text-[#657089]">{dateLabel(item.turnover_date)} · Clean {clock(item.access_start_at)}–{clock(item.window_end_at)} · Guest check-in {clock(item.next_checkin_at || item.window_end_at)}</p><p className="mt-1 text-sm text-[#657089]">{address}</p></div><TurnoverStatus status={item.status}/></div><div className={`mt-5 grid grid-cols-2 gap-4 border-t pt-4 ${item.status === "unassigned" ? "sm:grid-cols-3" : "sm:grid-cols-4"}`}><div><p className="text-xs font-bold text-[#748096]">CLEANER</p><p className="mt-1 font-extrabold">{item.status === "unassigned" ? "Not assigned" : workerName}</p></div>{item.status !== "unassigned" && <div><p className="text-xs font-bold text-[#748096]">STATUS</p><p className="mt-1 font-extrabold">{state.label}</p></div>}<div><p className="text-xs font-bold text-[#748096]">CHECKLIST</p><p className="mt-1 font-extrabold">{completed}/{tasks.length}</p></div><div><p className="text-xs font-bold text-[#748096]">ISSUES</p><p className="mt-1 font-extrabold">{openIssues.length ? `${openIssues.length} open` : "None"}</p></div></div></header>
    {!assignment && active && <section className="mt-4 rounded-xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold text-[#071f49]">Assign a cleaner</h2><p className="mt-1 text-sm text-[#657089]">Choose who will complete this clean.</p></div></div>{newWorkerId && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm font-bold text-emerald-900">Cleaner added. Select them below to assign this clean.</p>}{availableWorkers?.length ? <form action={assignWorker} className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><input type="hidden" name="turnoverId" value={id}/><label className="w-full font-bold text-[#071f49] sm:max-w-[400px]">Select cleaner<select name="workerId" required defaultValue={newWorkerId} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="" disabled>Select cleaner</option>{availableWorkers.map((candidate) => <option key={candidate.id} value={candidate.id}>{formatDisplayName(candidate.display_name)}</option>)}</select></label><div className="flex flex-wrap items-center gap-3"><button className="min-h-11 w-full rounded-lg bg-[#071f49] px-4 font-extrabold text-white sm:w-auto">Assign cleaner</button><CleanerCreationDialog turnoverId={id} compact/></div></form> : <div className="mt-4 flex flex-col items-start gap-3"><p className="text-sm font-bold text-[#071f49]">No cleaners added yet</p><p className="text-sm text-[#657089]">Add your first cleaner to assign this clean.</p><CleanerCreationDialog turnoverId={id}/></div>}</section>}
    {assignment && active && <section className="mt-5 rounded-xl border bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-extrabold">Cleaner assigned</h2><p className="mt-1 font-extrabold">{workerName}</p><p className="mt-1 text-sm text-[#657089]">{item.status === "awaiting_response" && dueAt ? `${state.label} · Reply due ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(dueAt))}` : state.label}</p></div>{worker?.id && <ReassignCleanerForm turnoverId={id} currentWorkerId={worker.id} workers={availableWorkers || []}/>}</div>{item.status === "awaiting_response" && worker?.id && <form action={resendWorkerInvitation} className="mt-4"><button name="workerId" value={worker.id} className="min-h-11 rounded-lg bg-[#071f49] px-4 font-extrabold text-white">Resend invitation</button></form>}</section>}
    {active && <section className="mt-5 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-extrabold">Cleaning progress</h2><div className="flex items-center gap-3"><span className="font-extrabold">{completed}/{tasks.length}</span><ChecklistTaskDialog turnoverId={id} sections={Array.from(sections.keys())}/></div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#e8edf3]" role="progressbar" aria-label="Checklist progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progressPercent}><div className="h-full rounded-full bg-[#2d67b2]" style={{ width: `${progressPercent}%` }}/></div>{sections.size > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2">{Array.from(sections.entries()).map(([section, result]) => <details key={section} className="group rounded-lg bg-[#f4f6f9] text-sm"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3 rounded-lg px-3 py-2 font-bold outline-none transition-colors hover:bg-[#eaf0f6] focus-visible:ring-4 focus-visible:ring-[#2d67b2]/20"><span>{section}</span><span className="flex items-center gap-2"><strong>{result.done}/{result.total}</strong><span aria-hidden="true" className="text-lg leading-none transition-transform group-open:rotate-90">›</span></span></summary><div className="border-t border-white px-3 pb-2">{result.tasks.map((task: { id: string; label: string; completed: boolean }) => <div key={task.id} className="flex items-start gap-2 py-2"><span className={task.completed ? "text-emerald-700" : "text-[#657089]"}>{task.completed ? "✓" : "○"}</span><span>{task.label}</span></div>)}</div></details>)}</div>}</section>}
    {openIssues.length > 0 && <section className="mt-5 rounded-xl border border-red-100 bg-red-50 p-5"><h2 className="text-lg font-extrabold text-red-950">Issues</h2><div className="mt-3 grid gap-3">{openIssues.map((issue: { id: string; issue_type: string; description: string; status: string; blocking: boolean; severity: string }) => <article key={issue.id} className="rounded-lg border border-red-100 bg-white p-3"><p className="font-extrabold">{issue.issue_type}{issue.blocking ? " · Blocking" : ""}</p><p className="mt-1 text-sm text-[#657089]">{issue.description}</p><p className="mt-2 text-xs font-bold capitalize">{issue.status.replaceAll("_", " ")} · {issue.severity}</p><div className="mt-3 flex flex-wrap gap-2"><form action={resolveIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><input name="resolution" required placeholder="Resolution" className="min-h-10 rounded-lg border px-2"/><button className="min-h-10 rounded-lg bg-[#071f49] px-3 text-sm font-bold text-white">Resolve</button></form><form action={updateIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><input type="hidden" name="issueAction" value="acknowledge"/><input name="ownerResponse" required placeholder="Response" className="min-h-10 rounded-lg border px-2"/><button className="min-h-10 rounded-lg border px-3 text-sm font-bold">Acknowledge</button></form></div></article>)}</div></section>}
    {item.evidence_submissions.length > 0 && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-extrabold">Evidence ({item.evidence_submissions.length})</summary><div className="mt-3 grid gap-2 text-sm">{item.evidence_submissions.map((e: { id: string; evidence_type: string; caption: string | null }) => <p key={e.id}>{e.caption || e.evidence_type.replaceAll("_", " ")}</p>)}</div></details>}
    {events.length > 0 && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-extrabold">Recent activity</summary><ol className="mt-3 divide-y">{events.map((event) => { const text = formatActivityEvent({ ...event, work_items: { properties: property, assignments: item.assignments } }); return <li key={event.id} className="py-2"><p className="text-sm font-bold">{text.title}</p><time className="text-xs text-[#748096]">{new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(event.created_at))}</time></li>; })}</ol><Link href={`/business/activity?turnover=${id}`} className="mt-3 block text-sm font-extrabold text-[#16467e]">View full history</Link></details>}
    {active && assignment && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-extrabold">More assignment actions</summary><div className="mt-4 grid gap-3"><form action={cancelAssignment}><input type="hidden" name="turnoverId" value={id}/><button className="min-h-10 text-sm font-bold text-red-700">Cancel assignment</button></form></div></details>}
  </div>;
}
