import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusinessUser } from "@/lib/business/auth";
import TurnoverStatus from "../../components/TurnoverStatus";
import { assignWorker, cancelAssignment, resendWorkerInvitation, resolveIssue, updateIssue } from "../../str-actions";
import { currentAssignment } from "@/lib/turnovers/presentation";
import { getOperatorState } from "@/lib/turnovers/operator-lifecycle";
import { formatDisplayName } from "@/lib/display-name";
import { collapseActivityEvents, formatActivityEvent } from "@/lib/activity-presentation";

const related = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;
const clock = (value: string) => new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(value));
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, accountId } = await requireBusinessUser();
  const [{ data: item }, { data: availableWorkers }] = await Promise.all([
    supabase.from("work_items").select("*,properties(nickname,address_line_1,city,postcode),assignments(status,assigned_at,response_due_at,workers(id,display_name,company_name)),checklist_tasks(id,label,section_title,mandatory,completed,photo_required,note_required),evidence_submissions(id,evidence_type,storage_path,caption,created_at),operational_issues(id,issue_type,severity,description,status,blocking,created_at),activity_events(id,event_type,description,created_at,metadata,work_item_id,properties(nickname),workers(display_name))").eq("id", id).eq("account_id", accountId).maybeSingle(),
    supabase.from("workers").select("id,display_name,company_name").eq("account_id", accountId).eq("status", "active").order("display_name"),
  ]);
  if (!item) notFound();
  const property = related(item.properties); const assignment = currentAssignment(item.assignments); const dueAt = (assignment as { response_due_at?: string } | undefined)?.response_due_at; const worker = related(assignment?.workers || null) as { id?: string; display_name?: string } | null; const workerName = formatDisplayName(worker?.display_name) || "No cleaner assigned"; const state = getOperatorState(item.status); const tasks = item.checklist_tasks || []; const completed = tasks.filter((t: { completed: boolean }) => t.completed).length; const issues = item.operational_issues || []; const openIssues = issues.filter((i: { status: string }) => !["resolved", "closed"].includes(i.status)); const active = !["ready", "cancelled"].includes(item.status); const events = collapseActivityEvents(item.activity_events || []).filter((e) => ["turnover_accepted", "turnover_arrived", "turnover_in_progress", "action_required", "property_ready", "issue_reported"].some((key) => e.event_type.includes(key))).slice(0, 3);
  const sections = new Map<string, { done: number; total: number }>();
  for (const task of tasks as Array<{ section_title: string; completed: boolean }>) { const current = sections.get(task.section_title) || { done: 0, total: 0 }; current.total += 1; if (task.completed) current.done += 1; sections.set(task.section_title, current); }
  return <div className="portal-page max-w-6xl">
    <Link href="/business/turnovers" className="text-sm font-bold text-[#526078]">← Turnovers</Link>
    <header className="mt-4 rounded-xl border bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-[#657089]">Guest check-in {clock(item.next_checkin_at || item.window_end_at)}</p><h1 className="mt-1 text-3xl font-extrabold">{property?.nickname || item.property_public_name}</h1><p className="mt-1 text-[#657089]">{property ? `${property.address_line_1}, ${property.city}, ${property.postcode}` : item.property_general_area}</p></div><TurnoverStatus status={item.status}/></div><div className="mt-5 grid grid-cols-2 gap-4 border-t pt-4 sm:grid-cols-4"><div><p className="text-xs font-bold text-[#748096]">CLEANER</p><p className="mt-1 font-extrabold">{workerName}</p></div><div><p className="text-xs font-bold text-[#748096]">STATUS</p><p className="mt-1 font-extrabold">{state.label}</p></div><div><p className="text-xs font-bold text-[#748096]">CHECKLIST</p><p className="mt-1 font-extrabold">{completed}/{tasks.length}</p></div><div><p className="text-xs font-bold text-[#748096]">ISSUES</p><p className="mt-1 font-extrabold">{openIssues.length ? `${openIssues.length} open` : "None"}</p></div></div>{state.message && <p className="mt-4 rounded-lg bg-[#eef5ff] p-3 font-extrabold text-[#16467e]">{state.message}{item.status === "in_progress" && item.actual_started_at ? ` · Started ${clock(item.actual_started_at)}` : ""}</p>}</header>
    {item.status === "unassigned" && <section className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-xl font-extrabold text-amber-950">Cleaner needed</h2><p className="mt-1 text-sm text-amber-900">This turnover has not been assigned yet.</p><form action={assignWorker} className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="turnoverId" value={id}/><select name="workerId" required defaultValue="" className="min-h-11 rounded-lg border bg-white px-3"><option value="" disabled>Select cleaner</option>{availableWorkers?.map((candidate) => <option key={candidate.id} value={candidate.id}>{formatDisplayName(candidate.display_name)}</option>)}</select><button className="min-h-11 rounded-lg bg-[#071f49] px-4 font-extrabold text-white">Assign cleaner</button></form></section>}
    {item.status === "awaiting_response" && <section className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-5"><h2 className="text-xl font-extrabold text-blue-950">Cleaner invited / awaiting response</h2><p className="mt-1 text-sm text-blue-900">{workerName}{dueAt ? ` · Reply due ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(dueAt))}` : ""}</p>{worker?.id && <form action={resendWorkerInvitation} className="mt-4"><button name="workerId" value={worker.id} className="min-h-11 rounded-lg bg-[#071f49] px-4 font-extrabold text-white">Resend invitation</button></form>}</section>}
    {active && <section className="mt-5 rounded-xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold">Cleaning progress</h2><span className="font-extrabold">{completed}/{tasks.length}</span></div>{sections.size > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2">{Array.from(sections.entries()).map(([section, result]) => <div key={section} className="flex justify-between rounded-lg bg-[#f4f6f9] px-3 py-2 text-sm"><span>{section}</span><strong>{result.done}/{result.total}</strong></div>)}</div>}<details className="mt-4"><summary className="cursor-pointer text-sm font-extrabold text-[#16467e]">View full checklist</summary><div className="mt-3 divide-y">{tasks.map((task: { id: string; label: string; section_title: string; completed: boolean }) => <div key={task.id} className="py-2 text-sm"><span className={task.completed ? "text-emerald-700" : "text-[#657089]"}>{task.completed ? "✓" : "○"} {task.label}</span><span className="ml-2 text-xs text-[#748096]">{task.section_title}</span></div>)}</div></details></section>}
    {openIssues.length > 0 && <section className="mt-5 rounded-xl border border-red-100 bg-red-50 p-5"><h2 className="text-lg font-extrabold text-red-950">Issues</h2><div className="mt-3 grid gap-3">{openIssues.map((issue: { id: string; issue_type: string; description: string; status: string; blocking: boolean; severity: string }) => <article key={issue.id} className="rounded-lg border border-red-100 bg-white p-3"><p className="font-extrabold">{issue.issue_type}{issue.blocking ? " · Blocking" : ""}</p><p className="mt-1 text-sm text-[#657089]">{issue.description}</p><p className="mt-2 text-xs font-bold capitalize">{issue.status.replaceAll("_", " ")} · {issue.severity}</p><div className="mt-3 flex flex-wrap gap-2"><form action={resolveIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><input name="resolution" required placeholder="Resolution" className="min-h-10 rounded-lg border px-2"/><button className="min-h-10 rounded-lg bg-[#071f49] px-3 text-sm font-bold text-white">Resolve</button></form><form action={updateIssue}><input type="hidden" name="issueId" value={issue.id}/><input type="hidden" name="turnoverId" value={id}/><input type="hidden" name="issueAction" value="acknowledge"/><input name="ownerResponse" required placeholder="Response" className="min-h-10 rounded-lg border px-2"/><button className="min-h-10 rounded-lg border px-3 text-sm font-bold">Acknowledge</button></form></div></article>)}</div></section>}
    {item.evidence_submissions.length > 0 && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-extrabold">Evidence ({item.evidence_submissions.length})</summary><div className="mt-3 grid gap-2 text-sm">{item.evidence_submissions.map((e: { id: string; evidence_type: string; caption: string | null }) => <p key={e.id}>{e.caption || e.evidence_type.replaceAll("_", " ")}</p>)}</div></details>}
    {events.length > 0 && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-extrabold">Recent activity</summary><ol className="mt-3 divide-y">{events.map((event) => { const text = formatActivityEvent({ ...event, work_items: { properties: property, assignments: item.assignments } }); return <li key={event.id} className="py-2"><p className="text-sm font-bold">{text.title}</p><time className="text-xs text-[#748096]">{new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(event.created_at))}</time></li>; })}</ol><Link href={`/business/activity?turnover=${id}`} className="mt-3 block text-sm font-extrabold text-[#16467e]">View full history</Link></details>}
    {active && <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-extrabold">More assignment actions</summary><div className="mt-4 grid gap-3">{assignment && <form action={cancelAssignment}><input type="hidden" name="turnoverId" value={id}/><button className="min-h-10 text-sm font-bold text-red-700">Cancel assignment</button></form>}{assignment && <p className="text-sm text-[#657089]">Reassignment is available from the cleaner management area.</p>}</div></details>}
  </div>;
}
