"use client";
import { useState } from "react";

type Address = { line1: string; line2: string; city: string; county: string; postcode: string; country: string };
export default function AddressLookup() {
  const [postcode, setPostcode] = useState(""); const [addresses, setAddresses] = useState<Address[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function lookup() { setLoading(true); setMessage(""); try { const response = await fetch(`/api/address-lookup?postcode=${encodeURIComponent(postcode)}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setAddresses(body.addresses || []); if (!body.addresses?.length) setMessage("No matching addresses were found. Enter the address manually."); } catch (error) { setMessage(error instanceof Error ? error.message : "Address lookup is unavailable."); } finally { setLoading(false); } }
  function select(index: number) { const address = addresses[index]; const form = document.querySelector<HTMLFormElement>('form[action]'); if (!form) return; const set = (name: string, value: string) => { const element = form.elements.namedItem(name) as HTMLInputElement | null; if (element) { element.value = value; element.dispatchEvent(new Event("input", { bubbles: true })); } }; set("addressLine1", address.line1); set("addressLine2", address.line2); set("city", address.city); set("postcode", address.postcode); set("county", address.county); set("country", address.country); const nickname = form.elements.namedItem("nickname") as HTMLInputElement | null; if (nickname && !nickname.value.trim()) set("nickname", address.line1); setAddresses([]); setMessage("Address selected. You can correct any field below."); }
  return <div className="rounded-lg border bg-slate-50 p-4"><label className="font-bold">Find a UK address<div className="mt-1 flex gap-2"><input value={postcode} onChange={(event) => setPostcode(event.target.value)} autoComplete="postal-code" className="min-h-12 min-w-0 flex-1 rounded-lg border bg-white px-3" placeholder="Postcode" /><button type="button" onClick={lookup} disabled={loading} className="min-h-12 rounded-lg bg-[#071f49] px-4 font-bold text-white disabled:opacity-60">{loading ? "Finding…" : "Find address"}</button></div></label>{addresses.length > 0 && <label className="mt-3 block font-bold">Select address<select className="mt-1 min-h-12 w-full rounded-lg border bg-white px-3" defaultValue="" onChange={(event) => select(Number(event.target.value))}><option value="" disabled>Choose an address</option>{addresses.map((address, index) => <option key={`${address.line1}-${index}`} value={index}>{address.line1}, {address.city}, {address.postcode}</option>)}</select></label>}{message && <p role="status" className="mt-2 text-sm font-semibold text-[#59677d]">{message}</p>}<p className="mt-2 text-xs text-[#657089]">Or enter the address manually below.</p></div>;
}
