import Link from "next/link";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/admin/auth";
import { createMarketplaceProviderInvitation, resendMarketplaceProviderInvitation, revokeMarketplaceProviderInvitation } from "@/app/admin/actions";

type Provider = { user_id: string; display_name: string | null; business_name: string | null; phone: string | null; base_town: string | null; provider_status: string | null; stripe_status: string | null; marketplace_active: boolean | null; created_at: string; submitted_at: string | null; marketplace_provider_services?: Array<{ job_type_slug: string; active: boolean }>; marketplace_provider_service_areas?: Array<{ postcode_district: string; active: boolean }> };
const statusLabel = (value: string | null) => ({ pending_review: "Pending", approved: "Verified", rejected: "Rejected", suspended: "Suspended", action_required: "Action required", draft: "Pending" }[value || "draft"] || String(value).replaceAll("_", " ")); // Needs review maps to Pending.
const statusTone = (value: string | null) => value === "approved" ? "bg-[#e7f6ec] text-[#177b42]" : ["suspended", "rejected"].includes(value || "") ? "bg-[#fdeaea] text-[#b33a3a]" : "bg-[#fff4dc] text-[#9a6900]";
const active = (p: Provider) => p.provider_status === "approved" && p.stripe_status === "ready" && p.marketplace_active === true;

export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string; success?: string; error?: string }> }) {
  await requireAdmin(); const query = await searchParams; const page = Math.max(1, Number(query.page || 1) || 1); const admin = createSupabaseAdminClient();
  const [{ data: providerData, count: providerCount }, { data: invites }, { data: offers }, { data: bookings }, { data: adminRows }] = await Promise.all([
    admin.from("cleaner_profiles").select("user_id,display_name,business_name,phone,base_town,provider_status,stripe_status,marketplace_active,created_at,submitted_at,marketplace_provider_services(category_slug,job_type_slug,active),marketplace_provider_service_areas(postcode_district,active)", { count: "exact" }).order("created_at", { ascending: false }).range((page - 1) * 50, page * 50 - 1),
    admin.from("marketplace_provider_invitations").select("id,email,invited_name,phone,category_slug,service_area,status,expires_at,sent_at,last_send_error,created_at").order("created_at", { ascending: false }),
    admin.from("marketplace_quotes").select("provider_id").limit(1000), admin.from("marketplace_bookings").select("provider_id,status").limit(1000), admin.from("admin_users").select("user_id").eq("active", true),
  ]);
  const adminIds = new Set((adminRows || []).map((row) => row.user_id)); const all = (providerData || []).filter((provider) => !adminIds.has(provider.user_id)) as Provider[]; const needle = (query.q || "").trim().toLowerCase();
  const matches = (p: Provider) => !needle || [p.display_name, p.business_name, p.base_town, p.phone].some((value) => String(value || "").toLowerCase().includes(needle));
  const inTab = (p: Provider) => query.status === "pending" || query.status === "needs_review" || query.status === "incomplete" ? ["pending_review", "draft", "action_required"].includes(p.provider_status || "") || (p.provider_status === "approved" && !active(p)) : query.status === "approved" || query.status === "active" ? p.provider_status === "approved" : query.status === "rejected" ? p.provider_status === "rejected" : query.status === "suspended" ? p.provider_status === "suspended" : true;
  const rows = all.filter((p) => matches(p) && inTab(p)); const countFor = (predicate: (p: Provider) => boolean) => all.filter(predicate).length; const counts = { all: countFor(() => true), pending: countFor((p) => ["pending_review", "draft", "action_required"].includes(p.provider_status || "") || (p.provider_status === "approved" && !active(p))), approved: countFor((p) => p.provider_status === "approved"), rejected: countFor((p) => p.provider_status === "rejected"), suspended: countFor((p) => p.provider_status === "suspended") };
  const tabs = [["", "All", counts.all], ["pending", "Pending", counts.pending], ["approved", "Verified", counts.approved], ["rejected", "Rejected", counts.rejected], ["suspended", "Suspended", counts.suspended]] as const; const tabHref = (status: string) => `/admin/providers?${status ? `status=${status}&` : ""}${query.q ? `q=${encodeURIComponent(query.q)}&` : ""}`;
  const offerCount = (id: string) => (offers || []).filter((offer) => offer.provider_id === id).length; const completedCount = (id: string) => (bookings || []).filter((booking) => booking.provider_id === id && booking.status === "completed").length; const totalPages = Math.max(1, Math.ceil((providerCount || all.length) / 50));
  return <div className="mx-auto max-w-[1260px]"><header className="flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-[25px] font-black tracking-[-.04em]">Providers</h1><p className="mt-1 text-sm text-[#718099]">Manage service providers and handymen</p></div><div className="flex items-center gap-2"><button type="button" disabled className="hidden min-h-9 rounded-lg border border-[#e2e8ee] bg-white px-3 text-xs font-bold text-[#758399] sm:block">Export</button><Link href="#add-provider" className="min-h-9 rounded-lg bg-[#159b50] px-3 py-2 text-xs font-black text-white">+ Add Provider</Link></div></header>
    <nav className="mt-6 flex flex-wrap gap-2" aria-label="Provider status filters">{tabs.map(([key, text, count]) => <Link key={text} href={tabHref(key)} className={`rounded-md border px-3 py-2 text-xs font-bold ${query.status === key || (!query.status && !key) ? "border-[#dce6e1] bg-[#eef7f1] text-[#177b42]" : "border-[#e5eaf0] bg-white text-[#697991]"}`}>{text} <span className="ml-1 text-[11px] opacity-70">{count}</span></Link>)}</nav>
    <form className="mt-4 flex max-w-sm gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search name, town or phone" className="min-h-9 w-full rounded-lg border border-[#e2e8ee] bg-white px-3 text-xs outline-none focus:border-[#159b50]" /><button className="min-h-9 rounded-lg bg-[#112b4b] px-3 text-xs font-bold text-white">Search</button></form>
    {(query.success || query.error) && <p className={`mt-4 rounded-lg p-3 text-xs font-bold ${query.error ? "bg-red-50 text-red-800" : "bg-[#eaf7ee] text-[#177b42]"}`}>{query.error ? "The provider action could not be completed." : "Provider action completed."}</p>}
    <section className="mt-4 overflow-hidden rounded-lg border border-[#e5eaf0] bg-white shadow-[0_2px_8px_rgba(28,48,76,.03)]"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-[#e8edf2] bg-[#fafbfc] text-[10px] uppercase tracking-[.08em] text-[#7a889b]"><tr><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Rating</th><th className="px-4 py-3">Jobs completed</th><th className="px-4 py-3">Plan / fee tier</th><th className="px-4 py-3">Joined</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map((p) => <tr key={p.user_id} className="hover:bg-[#fbfcfd]"><td className="px-4 py-3"><Link href={`/admin/providers/${p.user_id}`} className="flex items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e8f4ec] text-[11px] font-black text-[#177b42]">{(p.display_name || p.business_name || "P").slice(0, 1).toUpperCase()}</span><span><strong className="block text-[12px] font-black text-[#1d304c]">{p.display_name || p.business_name || "Unnamed provider"}</strong><small className="mt-0.5 block text-[10px] text-[#8190a3]">{p.phone || p.base_town || "No contact details"}</small></span></Link></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusTone(p.provider_status)}`}>{statusLabel(p.provider_status)}</span></td><td className="px-4 py-3 text-[#7c899b]">—</td><td className="px-4 py-3 font-bold text-[#263752]">{completedCount(p.user_id)}</td><td className="px-4 py-3 text-[#7c899b]">—</td><td className="px-4 py-3 text-[#62728a]">{new Date(p.created_at).toLocaleDateString("en-GB")}</td><td className="px-4 py-3 text-right"><details className="relative inline-block"><summary className="cursor-pointer list-none rounded-md px-2 py-1 text-lg leading-none text-[#74839a] hover:bg-[#f0f4f7]">⋯</summary><div className="absolute right-0 z-10 mt-1 w-36 rounded-md border border-[#e2e8ee] bg-white p-1 text-left shadow-lg"><Link href={`/admin/providers/${p.user_id}`} className="block rounded px-2 py-2 text-xs font-bold hover:bg-[#f5f7f9]">View dossier</Link><span className="block px-2 py-2 text-[10px] text-[#8995a5]">{offerCount(p.user_id)} offers · {completedCount(p.user_id)} completed</span></div></details></td></tr>)}</tbody></table></div>{!rows.length && <p className="p-8 text-center text-sm text-[#718099]">No providers match this filter.</p>}</section>
    <div className="flex flex-wrap items-center justify-between gap-3 py-4 text-xs text-[#758399]"><span>Showing {rows.length ? (page - 1) * 50 + 1 : 0} to {Math.min(page * 50, providerCount || rows.length)} of {providerCount ?? counts.all} providers</span><div className="flex items-center gap-1"><Link href={tabHref(query.status || "") + `page=${Math.max(1, page - 1)}`} className="rounded border border-[#e2e8ee] bg-white px-2 py-1">‹</Link>{[...Array(Math.min(3, totalPages))].map((_, index) => <Link key={index} href={tabHref(query.status || "") + `page=${index + 1}`} className={`rounded border px-2.5 py-1 ${page === index + 1 ? "border-[#159b50] bg-[#eaf7ee] text-[#177b42]" : "border-[#e2e8ee] bg-white"}`}>{index + 1}</Link>)}<Link href={tabHref(query.status || "") + `page=${Math.min(totalPages, page + 1)}`} className="rounded border border-[#e2e8ee] bg-white px-2 py-1">›</Link></div></div>
    <section id="add-provider" className="mt-3 grid gap-4 lg:grid-cols-[1fr_330px]"><div><h2 className="text-sm font-black text-[#20334f]">Invitations</h2><div className="mt-3 grid gap-2">{(invites || []).filter((invite) => !needle || `${invite.invited_name} ${invite.email} ${invite.phone || ""}`.toLowerCase().includes(needle)).slice(0, 5).map((invite) => <article key={invite.id} className="rounded-lg border border-[#e5eaf0] bg-white p-4"><div className="flex justify-between gap-3"><div><p className="text-xs font-black">{invite.invited_name}</p><p className="mt-1 text-[10px] text-[#718099]">{invite.email} · {invite.category_slug || "No category"}</p></div><span className="rounded-full bg-[#f0f3f6] px-2 py-1 text-[10px] font-bold capitalize">{invite.status}</span></div>{invite.status !== "accepted" && invite.status !== "revoked" && <div className="mt-3 flex gap-3"><form action={resendMarketplaceProviderInvitation}><input type="hidden" name="invitationId" value={invite.id} /><button className="text-[11px] font-black text-[#177b42]">Resend</button></form><form action={revokeMarketplaceProviderInvitation}><input type="hidden" name="invitationId" value={invite.id} /><button className="text-[11px] font-black text-red-700">Revoke</button></form></div>}</article>)}</div></div><form action={createMarketplaceProviderInvitation} className="grid h-fit gap-2 rounded-lg border border-[#e5eaf0] bg-white p-4"><h2 className="text-sm font-black">Add provider</h2><label className="text-[11px] font-bold">Name<input name="name" required className="mt-1 min-h-9 w-full rounded-md border px-2 text-xs" /></label><label className="text-[11px] font-bold">Email<input name="email" type="email" required className="mt-1 min-h-9 w-full rounded-md border px-2 text-xs" /></label><label className="text-[11px] font-bold">Phone<input name="phone" type="tel" className="mt-1 min-h-9 w-full rounded-md border px-2 text-xs" /></label><button className="mt-1 min-h-9 rounded-md bg-[#159b50] text-xs font-black text-white">Send invitation</button></form></section>
  </div>;
}
