import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Footer from "@/app/components/Footer";
import MarketplaceHeader from "@/app/components/marketplace/MarketplaceHeader";
import HomepageHero from "@/app/components/marketplace/HomepageHero";
import { marketplaceServices } from "@/app/data/marketplace";
import { getApprovedMarketplaceProvider } from "@/lib/marketplace/provider-access";
import { redirect } from "next/navigation";

export const metadata: Metadata = { title: "Quickola | Local help around the house", description: "Tell us what you need. Local people send you their prices, and you choose who you want." };
const ideas = [["Clean my 2-bed flat", "cleaning"], ["Cut my lawn", "gardening"], ["Trim my hedge", "gardening"], ["Put up shelves", "handyman"], ["Move a sofa", "removals"], ["Clear old furniture", "waste-removal"]];
const steps = ["Tell us what you need", "Local people send offers", "Choose who you want"];
const priorityServices = ["cleaning", "gardening", "handyman", "plumbing", "electrical", "removals", "furniture-assembly", "painting"];

export default async function Home({ searchParams }: { searchParams?: Promise<{ service?: string; job?: string; postcode?: string; location?: string; jobError?: string }> }) {
  const query = searchParams ? await searchParams : {};
  if (await getApprovedMarketplaceProvider()) redirect("/work");
  const error = query.jobError === "validation" ? "Check your job details and postcode." : query.jobError === "persistence" ? "We could not save your job yet. Please try again." : query.jobError === "delivery" ? "We could not send your request. Please try again." : "";
  return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><MarketplaceHeader /><HomepageHero initialService={query.service} initialPostcode={query.postcode} initialLocation={query.location} initialJob={query.job} error={error} /><section className="bg-white px-5 py-7 sm:px-8"><div className="mx-auto max-w-[1120px]"><h2 className="text-xl font-black">Local help you can choose.</h2><div className="mt-4 grid gap-3 text-[17px] font-extrabold sm:grid-cols-3"><p>✓ See offers before choosing</p><p>✓ Choose the person you prefer</p><p>✓ Only accept when you’re happy</p></div></div></section><section className="px-5 py-12 sm:px-8 sm:py-14"><div className="mx-auto max-w-[1120px]"><p className="text-sm font-black uppercase tracking-[.14em] text-[#23a955]">Popular services</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em] sm:text-5xl">What do you need help with?</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{priorityServices.map((slug) => { const service = marketplaceServices.find((item) => item.slug === slug); return service ? <Link key={service.slug} href={`/?service=${service.slug}#job-composer`} className="group rounded-2xl bg-white p-4 ring-1 ring-[#e9edf1] transition hover:-translate-y-1 focus-visible:ring-4 focus-visible:ring-[#23a955]"><div className="grid h-16 place-items-center rounded-xl bg-[#f0f7f2] p-3"><Image src={service.image} alt="" width={48} height={48} className="h-auto w-10 object-contain" /></div><h3 className="mt-3 text-base font-black group-hover:text-[#167d3c]">{service.name === "Removals" ? "Moving help" : service.name}</h3></Link> : null; })}</div></div></section><section className="bg-white px-5 py-12 sm:px-8 sm:py-14"><div className="mx-auto max-w-[1120px]"><p className="text-sm font-black uppercase tracking-[.14em] text-[#23a955]">Popular job ideas</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">People use Quickola for jobs like…</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ideas.map(([label, service]) => <Link key={label} href={`/?service=${service}#job-composer`} className="flex min-h-16 items-center rounded-2xl bg-[#f7f8fa] px-5 text-base font-black ring-1 ring-[#e9edf1] focus-visible:ring-4 focus-visible:ring-[#23a955]">{label}</Link>)}</div></div></section><section className="bg-[#061b3f] px-5 py-12 text-white sm:px-8 sm:py-14" id="how-it-works"><div className="mx-auto max-w-[1120px]"><p className="text-sm font-black uppercase tracking-[.14em] text-[#23dc63]">HOW QUICKOLA WORKS</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em] sm:text-5xl">Three simple steps</h2><ol className="mt-8 grid gap-4 md:grid-cols-3">{steps.map((title, index) => <li key={title} className="rounded-2xl bg-white/8 p-6 ring-1 ring-white/10"><p className="text-2xl font-black text-[#23dc63]">{index + 1}</p><h3 className="mt-5 text-xl font-black">{title}</h3></li>)}</ol></div></section><Footer /></main>;
}
