import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { bookingFinancialBreakdown, financialEvents, financialSummary, statusLabel, type AdminFinanceBooking, type AdminFinanceRefund, type FinanceEvent, type FinanceEventType } from "@/lib/marketplace/admin-finance";

type View = "all" | "payments" | "transfers" | "refunds" | "holds" | "failed";
type DateRange = "today" | "7d" | "30d" | "90d" | "all";
const money = (pence: number) => `£${(Math.max(0, Number(pence || 0)) / 100).toFixed(2)}`;
const dateLabel = (value: string) => new Date(value).toLocaleString("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
const normalise = <T,>(value: T | T[] | null | undefined): T | null => Array.isArray(value) ? value[0] || null : value || null;
function rangeStart(range: DateRange) { if (range === "all") return null; const start = new Date(); if (range === "today") start.setHours(0, 0, 0, 0); else start.setDate(start.getDate() - Number(range.replace("d", ""))); return start; }
function inRange(date: string, start: Date | null) { return !start || new Date(date) >= start; }
function typeLabel(type: FinanceEventType) { return type === "payment" ? "Customer payment" : type === "refund" ? "Customer refund" : type === "transfer" ? "Provider transfer" : "Payout hold"; }
function typeTone(type: FinanceEventType) { return type === "payment" ? "bg-[#eaf3ff] text-[#1d67b1]" : type === "refund" ? "bg-[#fff5e8] text-[#9a6511]" : type === "transfer" ? "bg-[#e8f7ed] text-[#177b42]" : "bg-[#fffaf0] text-[#795b13]"; }
function formatReference(value?: string | null) { return value ? value.length > 18 ? `${value.slice(0, 8)}…${value.slice(-6)}` : value : "—"; }

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ view?: string; range?: string; outcode?: string; q?: string; page?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const view = (["all", "payments", "transfers", "refunds", "holds", "failed"] as View[]).includes(query.view as View) ? query.view as View : "all";
  const range = (["today", "7d", "30d", "90d", "all"] as DateRange[]).includes(query.range as DateRange) ? query.range as DateRange : "30d";
  const start = rangeStart(range);
  const db = createSupabaseAdminClient();
  let bookingsQuery = db.from("marketplace_bookings").select("id,job_id,amount_pence,refunded_amount_pence,payment_status,status,paid_at,created_at,updated_at,provider_transfer_status,provider_transfer_amount_pence,provider_transferred_at,payout_hold_status,payout_hold_reason,stripe_payment_intent_id,stripe_transfer_id,marketplace_jobs(service,service_subtype,postcode),marketplace_customers(display_name,email),marketplace_providers(user_id,display_name,business_name)").order("updated_at", { ascending: false }).limit(1000);
  let refundsQuery = db.from("marketplace_refunds").select("id,booking_id,amount_pence,status,stripe_refund_id,stripe_payment_intent_id,created_at,confirmed_at,failure_reason").order("created_at", { ascending: false }).limit(2000);
  if (start) {
    bookingsQuery = bookingsQuery.gte("updated_at", start.toISOString());
    refundsQuery = refundsQuery.gte("created_at", start.toISOString());
  }
  const [{ data: bookingData }, { data: refundData }] = await Promise.all([bookingsQuery, refundsQuery]);
  const bookings = (bookingData || []) as AdminFinanceBooking[];
  const refunds = (refundData || []) as AdminFinanceRefund[];
  const events = financialEvents(bookings, refunds).filter((event) => inRange(event.date, start));
  const eventBookingIds = new Set(events.map((event) => event.bookingId));
  const periodBookings = bookings.filter((booking) => eventBookingIds.has(booking.id));
  const summary = financialSummary(periodBookings, refunds);
  const failedTransfers = bookings.filter((booking) => booking.provider_transfer_status === "failed");
  const heldBookings = bookings.filter((booking) => booking.payout_hold_status === "held");
  const refundProblems = refunds.filter((refund) => ["pending", "failed", "indeterminate"].includes(refund.status));
  const pendingPayments = bookings.filter((booking) => booking.payment_status === "pending_payment");
  const outcodes = [...new Set(bookings.map((booking) => normalise(booking.marketplace_jobs)?.postcode?.split(" ")[0]).filter(Boolean) as string[])].sort();
  const search = (query.q || "").trim().toLowerCase();
  const filteredEvents = events.filter((event) => {
    if (query.outcode && normalise(event.booking.marketplace_jobs)?.postcode?.split(" ")[0] !== query.outcode) return false;
    if (view === "payments" && event.type !== "payment") return false;
    if (view === "transfers" && event.type !== "transfer") return false;
    if (view === "refunds" && event.type !== "refund") return false;
    if (view === "holds" && event.type !== "hold") return false;
    if (view === "failed" && !(["failed", "indeterminate"].includes(event.status) || event.booking.provider_transfer_status === "failed")) return false;
    if (!search) return true;
    const job = normalise(event.booking.marketplace_jobs); const customer = normalise(event.booking.marketplace_customers); const provider = normalise(event.booking.marketplace_providers);
    return [event.booking.id, event.booking.job_id, event.reference, event.refund?.stripe_refund_id, event.booking.stripe_payment_intent_id, event.booking.stripe_transfer_id, job?.service, job?.service_subtype, job?.postcode, customer?.display_name, customer?.email, provider?.display_name, provider?.business_name].filter(Boolean).some((value) => String(value).toLowerCase().includes(search));
  });
  const page = Math.max(1, Number(query.page || 1)); const pageSize = 40; const pageCount = Math.max(1, Math.ceil(filteredEvents.length / pageSize)); const currentPage = Math.min(page, pageCount); const visibleEvents = filteredEvents.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const link = (changes: Record<string, string | undefined>) => { const params = new URLSearchParams({ view, range, ...(query.outcode ? { outcode: query.outcode } : {}), ...(query.q ? { q: query.q } : {}), ...changes }); for (const [key, value] of Object.entries(changes)) if (!value) params.delete(key); return `/admin/payments?${params.toString()}`; };
  const attention = [{ label: "Pending payments", count: pendingPayments.length, href: link({ view: "payments" }) }, { label: "Failed transfers", count: failedTransfers.length, href: link({ view: "failed" }) }, { label: "Transfers on hold", count: heldBookings.length, href: link({ view: "holds" }) }, { label: "Refund problems", count: refundProblems.length, href: link({ view: "refunds" }) }, { label: "Financial mismatches", count: summary.mismatches, href: link({ view: "all" }) }];
  return <main className="mx-auto max-w-[1420px] pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.12em] text-[#159548]">MONEY OPERATIONS</p><h1 className="mt-1 text-3xl font-black text-[#071638]">Financial activity</h1><p className="mt-1 text-[#657089]">A read-only view of customer payments, refunds, Quickola revenue, and provider transfers.</p></div><form className="flex flex-wrap gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search customer, provider, job or Stripe ID" className="min-h-11 w-72 rounded-xl border border-[#dfe5ea] px-3 text-sm" /><select name="range" defaultValue={range} className="min-h-11 rounded-xl border border-[#dfe5ea] px-3 text-sm">{[["today", "Today"], ["7d", "7 days"], ["30d", "30 days"], ["90d", "90 days"], ["all", "All time"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select name="outcode" defaultValue={query.outcode || ""} className="min-h-11 rounded-xl border border-[#dfe5ea] px-3 text-sm"><option value="">All outcodes</option>{outcodes.map((outcode) => <option key={outcode} value={outcode}>{outcode}</option>)}</select><button className="min-h-11 rounded-xl bg-[#071638] px-4 text-sm font-black text-white">Apply</button></form></div>
    <section className="mt-5 rounded-2xl border border-[#e8dcae] bg-[#fffdf5] p-4"><div className="flex flex-wrap items-center gap-x-5 gap-y-2"><p className="text-xs font-black uppercase tracking-[.12em] text-[#795b13]">Needs attention</p>{attention.map((item) => <Link key={item.label} href={item.href} className={`text-sm ${item.count ? "font-black text-[#8f3030]" : "text-[#657089]"}`}>{item.count} {item.label.toLowerCase()}</Link>)}</div></section>
    <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{[["Gross customer payments", money(summary.grossPence), "in"], ["Refunded", money(summary.refundedPence), "out"], ["Net customer payments", money(summary.netPence), "net"], ["Quickola revenue", money(summary.revenuePence), "fee"], ["Provider earnings", money(summary.providerEarningsPence), "earn"], ["Pending provider transfers", money(summary.pendingProviderPence), "pending"], ["Transferred to providers", money(summary.transferredPence), "paid"], ["On hold", money(summary.onHoldPence), "hold"]].map(([label, value, tone]) => <div key={label} className="rounded-2xl border border-[#e7ebef] bg-white p-4"><p className="text-[11px] font-bold leading-4 text-[#657089]">{label}</p><p className={`mt-2 text-xl font-black ${tone === "out" || tone === "hold" ? "text-[#795b13]" : tone === "paid" ? "text-[#177b42]" : "text-[#071638]"}`}>{value}</p></div>)}</section>
    <p className="mt-3 text-xs text-[#718099]">Quickola revenue is the existing 10% marketplace fee on net customer-paid value. Stripe processing fees are not included because actual fee data is not persisted. No live Stripe calls are made here.</p>
    <nav className="mt-7 flex gap-2 overflow-x-auto border-b border-[#e7ebef] pb-2">{([["all", "All activity"], ["payments", "Customer payments"], ["transfers", "Provider transfers"], ["refunds", "Refunds"], ["holds", "On hold"], ["failed", "Failed"]] as [View, string][]).map(([value, label]) => <Link key={value} href={link({ view: value, page: undefined })} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-black ${view === value ? "bg-[#071638] text-white" : "text-[#526078] hover:bg-[#f1f4f7]"}`}>{label}</Link>)}</nav>
    <section className="mt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black text-[#071638]">Financial activity</h2><p className="mt-1 text-sm text-[#657089]">{filteredEvents.length} persisted event{filteredEvents.length === 1 ? "" : "s"}; dates use the financial event, not the booking creation date.</p></div>{pageCount > 1 && <div className="flex gap-2"><Link href={link({ page: String(Math.max(1, currentPage - 1)) })} className="rounded-lg border px-3 py-2 text-sm font-black">Previous</Link><span className="px-2 py-2 text-sm text-[#657089]">Page {currentPage} of {pageCount}</span><Link href={link({ page: String(Math.min(pageCount, currentPage + 1)) })} className="rounded-lg border px-3 py-2 text-sm font-black">Next</Link></div>}</div><div className="mt-4 overflow-hidden rounded-2xl border border-[#e7ebef] bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b bg-[#f7f8fa] text-[11px] uppercase tracking-wide text-[#657089]"><tr><th className="p-4">Date</th><th className="p-4">Type</th><th className="p-4">Job</th><th className="p-4">Customer / provider</th><th className="p-4 text-right">Amount</th><th className="p-4">Status</th><th className="p-4">Reference</th></tr></thead><tbody>{visibleEvents.map((event) => <LedgerRow key={event.id} event={event} />)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{visibleEvents.map((event) => <LedgerCard key={event.id} event={event} />)}</div>{!visibleEvents.length && <p className="p-10 text-center text-sm text-[#657089]">No persisted financial activity matches this view.</p>}</div></section>
    <p className="mt-5 text-xs text-[#718099]">This console is read-only. Use the linked booking detail for existing guarded operational actions; no refund, hold, transfer, or retry action is created here.</p>
  </main>;
}

function LedgerRow({ event }: { event: FinanceEvent }) { const job = normalise(event.booking.marketplace_jobs); const customer = normalise(event.booking.marketplace_customers); const provider = normalise(event.booking.marketplace_providers); const breakdown = bookingFinancialBreakdown(event.booking); return <tr className="border-b last:border-0 hover:bg-[#fbfdfc]"><td className="p-4 whitespace-nowrap text-[#526078]" title={event.date}>{dateLabel(event.date)}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-[11px] font-black ${typeTone(event.type)}`}>{typeLabel(event.type)}</span></td><td className="p-4"><Link href={`/admin/marketplace-bookings/${event.bookingId}`} className="font-black text-[#167d3c]">{job?.service_subtype || job?.service || "Marketplace job"}</Link><p className="text-xs text-[#718099]">{job?.postcode || "No postcode"}</p></td><td className="p-4"><span className="block font-bold">{customer?.display_name || customer?.email || "Customer"}</span><span className="text-xs text-[#718099]">{event.type === "transfer" || event.type === "hold" ? provider?.business_name || provider?.display_name || "Provider" : "Quickola platform"}</span></td><td className={`p-4 text-right font-black ${event.direction === "in" ? "text-[#177b42]" : "text-[#071638]"}`} aria-label={`${event.direction === "in" ? "Incoming" : "Outgoing"} ${money(event.amountPence)}`}>{event.direction === "in" ? "+" : "−"}{money(event.amountPence)}{event.type === "hold" && <span className="block text-[10px] font-bold text-[#795b13]">{money(breakdown.providerEarningsPence)} eligible</span>}</td><td className="p-4 capitalize">{statusLabel(event.status)}</td><td className="p-4 font-mono text-xs text-[#526078]" title={event.reference || undefined}>{formatReference(event.reference)}</td></tr>; }

function LedgerCard({ event }: { event: FinanceEvent }) { const job = normalise(event.booking.marketplace_jobs); const customer = normalise(event.booking.marketplace_customers); const provider = normalise(event.booking.marketplace_providers); return <Link href={`/admin/marketplace-bookings/${event.bookingId}`} className="rounded-xl border border-[#e7ebef] p-4"><div className="flex items-start justify-between gap-3"><span className={`rounded-full px-2 py-1 text-[11px] font-black ${typeTone(event.type)}`}>{typeLabel(event.type)}</span><span className={`text-lg font-black ${event.direction === "in" ? "text-[#177b42]" : "text-[#071638]"}`}>{event.direction === "in" ? "+" : "−"}{money(event.amountPence)}</span></div><p className="mt-3 font-black">{job?.service_subtype || job?.service || "Marketplace job"}</p><p className="text-sm text-[#526078]">{customer?.display_name || customer?.email || "Customer"} · {provider?.business_name || provider?.display_name || "Provider"}</p><div className="mt-3 flex justify-between text-xs text-[#718099]"><span>{dateLabel(event.date)}</span><span className="font-bold capitalize">{statusLabel(event.status)}</span></div><p className="mt-2 font-mono text-[11px] text-[#718099]">{formatReference(event.reference)}</p></Link>; }
