import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { resolveMarketplacePaymentState, type MarketplacePaymentAllocation, type MarketplacePaymentBooking } from "@/lib/marketplace/payment-state";

type Booking = MarketplacePaymentBooking & { id: string; job_id: string; created_at: string; completed_at?: string | null; customer_completed_at?: string | null; marketplace_jobs?: { service?: string | null; service_subtype?: string | null } | Array<{ service?: string | null; service_subtype?: string | null }> | null; marketplace_customers?: { display_name?: string | null; email?: string | null } | Array<{ display_name?: string | null; email?: string | null }> | null; marketplace_providers?: { display_name?: string | null; business_name?: string | null } | Array<{ display_name?: string | null; business_name?: string | null }> | null };
type Allocation = MarketplacePaymentAllocation & { booking_id: string };
const money = (pence: number | null) => pence == null ? "Unavailable" : `£${(Math.max(0, Number(pence)) / 100).toFixed(2)}`;
const one = <T,>(value: T | T[] | null | undefined) => Array.isArray(value) ? value[0] || null : value || null;

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ q?: string; flow?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const db = createSupabaseAdminClient();
  const [{ data: bookingData }, { data: allocationData }] = await Promise.all([
    db.from("marketplace_bookings").select("id,job_id,amount_pence,refunded_amount_pence,payment_status,status,payment_flow,provider_transfer_status,provider_transfer_amount_pence,payout_hold_status,completed_at,customer_completed_at,created_at,marketplace_jobs(service,service_subtype),marketplace_customers(display_name,email),marketplace_providers(display_name,business_name)").order("created_at", { ascending: false }).limit(1000),
    db.from("marketplace_payout_allocations").select("booking_id,gross_amount_pence,quickola_fee_pence,stripe_fee_pence,provider_net_pence,payout_status,stripe_payout_id,payout_eligible_at").limit(2000),
  ]);
  const allocations = new Map((allocationData || []).map((allocation) => [allocation.booking_id, allocation as Allocation]));
  const search = (query.q || "").trim().toLowerCase();
  const rows = (bookingData || []).filter((booking) => {
    const job = one(booking.marketplace_jobs); const customer = one(booking.marketplace_customers); const provider = one(booking.marketplace_providers);
    const flowMatches = !query.flow || booking.payment_flow === query.flow;
    return flowMatches && (!search || `${booking.id} ${booking.job_id} ${job?.service} ${job?.service_subtype} ${customer?.display_name} ${customer?.email} ${provider?.display_name} ${provider?.business_name}`.toLowerCase().includes(search));
  }).map((booking) => ({ booking: booking as Booking, state: resolveMarketplacePaymentState(booking, allocations.get(booking.id)) }));
  const paidRows = rows.filter(({ booking }) => ["paid", "partially_refunded"].includes(booking.payment_status || ""));
  const total = (pick: (state: ReturnType<typeof resolveMarketplacePaymentState>) => number) => paidRows.reduce((sum, row) => sum + pick(row.state), 0);
  return <main className="mx-auto max-w-[1420px] pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.12em] text-[#159548]">MONEY OPERATIONS</p><h1 className="mt-1 text-3xl font-black text-[#071638]">Payments</h1><p className="mt-1 text-[#657089]">One clear financial view for platform transfers and direct charges.</p></div><form className="flex flex-wrap gap-2"><input name="q" defaultValue={query.q || ""} placeholder="Search booking, customer or provider" className="min-h-11 w-72 rounded-xl border border-[#dfe5ea] px-3 text-sm" /><select name="flow" defaultValue={query.flow || ""} className="min-h-11 rounded-xl border border-[#dfe5ea] px-3 text-sm"><option value="">All flows</option><option value="platform_transfer">Platform transfer</option><option value="direct_charge">Direct charge</option></select><button className="min-h-11 rounded-xl bg-[#071638] px-4 text-sm font-black text-white">Apply</button></form></div><section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Customer paid" value={money(total((state) => state.customerPaid))} /><Metric label="Quickola fees" value={money(total((state) => state.quickolaFee))} /><Metric label="Provider net" value={money(total((state) => state.providerNet || 0))} /><Metric label="Pending payout" value={money(paidRows.filter(({ state }) => state.payoutLabel === "Pending payout" || state.payoutLabel === "Awaiting completion").reduce((sum, row) => sum + (row.state.providerNet || 0), 0))} /></section><section className="mt-7 overflow-hidden rounded-2xl border border-[#e7ebef] bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1300px] text-left text-sm"><thead className="border-b bg-[#f7f8fa] text-[11px] uppercase tracking-wide text-[#657089]"><tr><th className="p-4">Booking / job</th><th className="p-4">Customer</th><th className="p-4">Provider</th><th className="p-4 text-right">Gross</th><th className="p-4 text-right">Quickola fee</th><th className="p-4 text-right">Stripe fee</th><th className="p-4 text-right">Provider net</th><th className="p-4">Flow</th><th className="p-4">Payment</th><th className="p-4">Completion</th><th className="p-4">Payout eligible</th><th className="p-4">Payout</th></tr></thead><tbody>{rows.map(({ booking, state }) => <AdminRow key={booking.id} booking={booking} state={state} allocation={allocations.get(booking.id)} />)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{rows.map(({ booking, state }) => <AdminCard key={booking.id} booking={booking} state={state} />)}</div>{!rows.length && <p className="p-10 text-center text-sm text-[#657089]">No bookings match this view.</p>}</section><p className="mt-4 text-xs text-[#718099]">Stripe fees show Unavailable unless the actual fee is persisted on the direct-charge allocation.</p></main>;
}

function AdminRow({ booking, state, allocation }: { booking: Booking; state: ReturnType<typeof resolveMarketplacePaymentState>; allocation?: Allocation }) { const job = one(booking.marketplace_jobs); const customer = one(booking.marketplace_customers); const provider = one(booking.marketplace_providers); return <tr className="border-b last:border-0 hover:bg-[#fbfdfc]"><td className="p-4"><Link href={`/admin/marketplace-bookings/${booking.id}`} className="font-black text-[#167d3c]">{job?.service_subtype || job?.service || "Marketplace job"}</Link><p className="text-xs text-[#718099]">{booking.id.slice(0, 8)} · {booking.job_id.slice(0, 8)}</p></td><td className="p-4">{customer?.display_name || customer?.email || "Customer"}</td><td className="p-4">{provider?.business_name || provider?.display_name || "Provider"}</td><td className="p-4 text-right font-black">{money(state.customerPaid)}</td><td className="p-4 text-right">{money(state.quickolaFee)}</td><td className="p-4 text-right">{money(state.stripeFee)}</td><td className="p-4 text-right font-black">{money(state.providerNet)}</td><td className="p-4"><span className="rounded-full bg-[#eef3f7] px-2 py-1 text-xs font-black">{state.flow === "direct_charge" ? "Direct charge" : "Platform transfer"}</span></td><td className="p-4">{state.paymentLabel}</td><td className="p-4">{dateLabel(booking.customer_completed_at || booking.completed_at)}</td><td className="p-4">{dateLabel(allocation?.payout_eligible_at)}</td><td className="p-4">{state.payoutLabel}</td></tr>; }
function AdminCard({ booking, state }: { booking: Booking; state: ReturnType<typeof resolveMarketplacePaymentState> }) { const job = one(booking.marketplace_jobs); const customer = one(booking.marketplace_customers); const provider = one(booking.marketplace_providers); return <Link href={`/admin/marketplace-bookings/${booking.id}`} className="rounded-xl border border-[#e7ebef] p-4"><div className="flex justify-between gap-3"><p className="font-black">{job?.service_subtype || job?.service || "Marketplace job"}</p><span className="text-xs font-black">{state.payoutLabel}</span></div><p className="mt-2 text-sm text-[#526078]">{customer?.display_name || customer?.email || "Customer"} · {provider?.business_name || provider?.display_name || "Provider"}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt>Gross</dt><dd className="font-black">{money(state.customerPaid)}</dd></div><div><dt>Provider net</dt><dd className="font-black">{money(state.providerNet)}</dd></div><div><dt>Flow</dt><dd className="font-black">{state.flow === "direct_charge" ? "Direct charge" : "Platform transfer"}</dd></div><div><dt>Payment</dt><dd className="font-black">{state.paymentLabel}</dd></div></dl></Link>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#e7ebef] bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#657089]">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>; }
function dateLabel(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "—"; }
