import Constants from "expo-constants";
import { supabase } from "./supabase";
import type { ChecklistTask, CleanerProperty, CleanerReport, Evidence, Job, MarketplaceOpportunity, WalkthroughScan, Worker } from "./types";

const jobFields = "id,account_id,property_public_name,property_general_area,cleaning_type,turnover_date,access_start_at,next_checkin_at,status,required_evidence_count,assignments!inner(worker_id,status),properties(nickname,address_line_1,city,postcode,bedrooms,bathrooms,access_notes,key_instructions,key_return_instructions,parking_notes,floor_lift_notes,cleaning_notes,linen_requirements,towel_requirements,bed_configuration,consumables_instructions,waste_instructions)";
const detailFields = `${jobFields},checklist_tasks(id,section_title,label,description,mandatory,blocking,completed,response_type,response,photo_required,note_required,note),evidence_submissions(id,work_item_id,checklist_task_id,issue_id,evidence_type,storage_path),operational_issues(id,status,blocking)`;

export async function getWorker(userId: string) { const { data, error } = await supabase.from("workers").select("id,display_name,email,mobile,status,invitation_status,account_id").eq("user_id", userId).eq("status", "active").eq("invitation_status", "accepted").maybeSingle(); if (error) throw error; return data as Worker | null; }
const standaloneJobFields = "id,account_id,standalone_cleaner_user_id,property_public_name,property_general_area,cleaning_type,turnover_date,access_start_at,window_end_at,next_checkin_at,status,required_evidence_count,host_name,host_email,host_phone,assignments(worker_id,status),properties(nickname,address_line_1,city,postcode,bedrooms,bathrooms,access_notes,key_instructions,key_return_instructions,parking_notes,floor_lift_notes,cleaning_notes,linen_requirements,towel_requirements,bed_configuration,consumables_instructions,waste_instructions)";
export async function getJobs(workerId: string | null, tab: "today" | "upcoming" | "in_progress" | "completed", standaloneUserId?: string) {
  let query = workerId ? supabase.from("work_items").select(jobFields).eq("assignments.worker_id", workerId).in("assignments.status", ["pending", "accepted"]).order("access_start_at", { ascending: true }) : supabase.from("work_items").select(standaloneJobFields).eq("standalone_cleaner_user_id", standaloneUserId || "").order("access_start_at", { ascending: true });
  if (tab === "today") query = query.in("status", ["awaiting_response", "accepted", "en_route", "arrived", "in_progress", "action_required"]);
  if (tab === "upcoming") query = query.in("status", ["awaiting_response", "accepted", "en_route", "arrived"]);
  if (tab === "in_progress") query = query.in("status", ["in_progress", "action_required", "evidence_submitted"]);
  if (tab === "completed") query = query.eq("status", "ready").order("turnover_date", { ascending: false });
  const { data, error } = await query; if (error) throw error; return (data || []) as unknown as Job[];
}
export async function getMarketplaceOpportunities() { const { data, error } = await supabase.rpc("get_marketplace_opportunities"); if (error) throw error; return (data || []) as MarketplaceOpportunity[]; }
export async function submitMarketplaceQuote(input: { jobId: string; amountPence: number; availabilityType: string; availabilityText?: string; message?: string }) { const { data, error } = await supabase.rpc("submit_marketplace_quote", { target_job: input.jobId, quote_amount: input.amountPence, quote_availability: input.availabilityType, quote_availability_text: input.availabilityText || null, quote_message: input.message || null }); if (error) throw error; const { data: sessionData } = await supabase.auth.getSession(); const baseUrl = (Constants.expoConfig?.extra as { EXPO_PUBLIC_APP_URL?: string } | undefined)?.EXPO_PUBLIC_APP_URL || process.env.EXPO_PUBLIC_APP_URL; if (sessionData.session?.access_token && baseUrl && data && typeof data === "object" && "id" in data) void fetch(`${baseUrl}/api/marketplace/quote-notification`, { method: "POST", headers: { Authorization: `Bearer ${sessionData.session.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ jobId: input.jobId, quoteId: (data as { id: string }).id }) }).catch(() => undefined); return data; }
export async function getJob(id: string, workerId: string | null, standaloneUserId?: string) { const query = workerId ? supabase.from("work_items").select(detailFields).eq("id", id).eq("assignments.worker_id", workerId).maybeSingle() : supabase.from("work_items").select(`${standaloneJobFields},checklist_tasks(id,section_title,label,description,mandatory,blocking,completed,response_type,response,photo_required,note_required,note),evidence_submissions(id,work_item_id,checklist_task_id,issue_id,evidence_type,storage_path),operational_issues(id,status,blocking,issue_type,severity,description)`).eq("id", id).eq("standalone_cleaner_user_id", standaloneUserId || "").maybeSingle(); const { data, error } = await query; if (error) throw error; return data as unknown as Job | null; }
export async function transition(id: string, next: string) { const { error } = await supabase.rpc("transition_work_item", { target_work_item: id, next_status: next }); if (error) throw error; }
export async function createCleanerProperty(input: { name: string; address: string; bedrooms: number; bathrooms: number; postcode?: string; hostName?: string; hostEmail?: string; hostPhone?: string; notes?: string; accessNotes?: string; parkingNotes?: string; linenNotes?: string }) { const { data, error } = await supabase.rpc("create_cleaner_property", { property_name: input.name, property_address: input.address, property_bedrooms: input.bedrooms, property_bathrooms: input.bathrooms, property_postcode: input.postcode || null, property_host_name: input.hostName || null, property_host_email: input.hostEmail || null, property_host_phone: input.hostPhone || null, property_notes: input.notes || null, property_access_notes: input.accessNotes || null, property_parking_notes: input.parkingNotes || null, property_linen_notes: input.linenNotes || null }); if (error) throw error; return data as CleanerProperty; }
export async function getCleanerProperties() { const { data, error } = await supabase.from("properties").select("id,nickname,address_line_1,city,postcode,bedrooms,bathrooms,host_name,host_email,host_phone,internal_notes,access_notes,parking_notes,linen_requirements").eq("standalone_cleaner_user_id", (await supabase.auth.getUser()).data.user?.id || "").order("created_at", { ascending: false }); if (error) throw error; return (data || []) as CleanerProperty[]; }
export async function createCleanerWorkItem(input: { propertyId: string; creationKey: string; date: string; start: string; end: string; guestCheckin?: string; notes?: string; hostName?: string; hostEmail?: string; hostPhone?: string }) { const { data, error } = await supabase.rpc("create_cleaner_work_item", { target_property: input.propertyId, p_creation_key: input.creationKey, clean_date: input.date, clean_start: input.start, clean_end: input.end, guest_checkin: input.guestCheckin || null, clean_notes: input.notes || null, clean_host_name: input.hostName || null, clean_host_email: input.hostEmail || null, clean_host_phone: input.hostPhone || null }); if (error) throw error; return data as { id: string }; }
export async function createCleanerIssue(workItemId: string, title: string, description: string, severity: string) { const { data, error } = await supabase.rpc("create_cleaner_issue", { target_work_item: workItemId, issue_title: title, issue_description: description, issue_severity: severity }); if (error) throw error; return data; }
export async function createCompletionReport(workItemId: string) { const { data, error } = await supabase.rpc("create_work_item_completion_report", { target_work_item: workItemId }); if (error) throw error; return data as { id: string }; }
export async function createReportShare(reportId: string) { const { data, error } = await supabase.rpc("create_work_item_report_share", { target_report: reportId }); if (error) throw error; return data as string; }
export async function getWalkthroughScan(workItemId: string | null, scanId?: string) { let query = supabase.from("cleaner_walkthrough_scans").select("id,work_item_id,status,source_storage_path,frame_count,issue_count,resolved_issue_count,provider,model,error_message,created_at,completed_at,cleaner_walkthrough_issues(id,scan_id,work_item_id,frame_index,frame_storage_path,category,confidence,description,resolution_status,resolution_note)"); query = scanId ? query.eq("id", scanId) : query.eq("work_item_id", workItemId || ""); const { data: scan, error } = await query.order("created_at", { ascending: false }).limit(1).maybeSingle(); if (error) throw error; if (!scan) return null; return { ...scan, issues: scan.cleaner_walkthrough_issues || [] } as unknown as WalkthroughScan; }
export async function uploadWalkthroughVideo(job: Job, userId: string, uri: string) { const path = `${userId}/${job.id}/walkthrough-${Date.now()}.mp4`; const body = await (await fetch(uri)).arrayBuffer(); const { error } = await supabase.storage.from("cleaner-walkthroughs").upload(path, body, { contentType: "video/mp4", upsert: false }); if (error) throw error; const { data, error: scanError } = await supabase.rpc("create_cleaner_walkthrough_scan", { target_work_item: job.id, source_path: path }); if (scanError) { await supabase.storage.from("cleaner-walkthroughs").remove([path]); throw scanError; } return data as WalkthroughScan; }
function walkthroughDebug(stage: string, details: Record<string, unknown> = {}) { if (__DEV__) console.log("walkthrough_debug", { stage, ...details }); }
function safeWalkthroughError(error: unknown) { const value = error as { name?: string; message?: string; code?: string; status?: number }; return { errorName: value?.name || "Error", message: String(value?.message || error || "Unknown error").replace(/Bearer\s+\S+/gi, "Bearer [redacted]").replace(/https?:\/\/\S+/gi, "[url]").slice(0, 240), ...(value?.code ? { code: value.code } : {}), ...(value?.status ? { status: value.status } : {}) }; }
export async function createInstantWalkthroughScan() { walkthroughDebug("scan_creation_request"); const { data, error } = await supabase.rpc("create_instant_cleaner_walkthrough_scan"); if (error) { walkthroughDebug("scan_creation_failed", safeWalkthroughError(error)); if (error.code === "PGRST202" || /create_instant_cleaner_walkthrough_scan|work_item_id|mode/i.test(error.message)) throw new Error("instant_walkthrough_migration_required"); throw error; } walkthroughDebug("scan_creation_succeeded", { hasScanId: Boolean(data && (data as WalkthroughScan).id) }); return data as WalkthroughScan; }
export async function uploadInstantWalkthroughVideo(scan: WalkthroughScan, userId: string, uri: string) { const path = `${userId}/${scan.id}/walkthrough.mp4`; walkthroughDebug("video_upload_read_start", { hasVideoUri: Boolean(uri) }); const fileResponse = await fetch(uri); if (!fileResponse.ok) throw new Error(`video_file_read_failed_${fileResponse.status}`); const body = await fileResponse.arrayBuffer(); walkthroughDebug("video_upload_start", { hasVideoBytes: body.byteLength > 0 }); const { error } = await supabase.storage.from("cleaner-walkthroughs").upload(path, body, { contentType: "video/mp4", upsert: false }); if (error) { walkthroughDebug("video_upload_failed", safeWalkthroughError(error)); throw error; } walkthroughDebug("video_upload_succeeded"); const { data, error: updateError } = await supabase.from("cleaner_walkthrough_scans").update({ source_storage_path: path, status: "processing" }).eq("id", scan.id).eq("cleaner_user_id", userId).select("id,work_item_id,status,source_storage_path,frame_count,issue_count,resolved_issue_count,provider,model,error_message,created_at,completed_at").single(); if (updateError) { walkthroughDebug("scan_source_update_failed", safeWalkthroughError(updateError)); await supabase.storage.from("cleaner-walkthroughs").remove([path]); throw updateError; } return { ...data, issues: [] } as WalkthroughScan; }
export async function resolveWalkthroughIssue(issueId: string, resolution: "fixed" | "not_an_issue", note?: string) { const { data, error } = await supabase.rpc("resolve_cleaner_walkthrough_issue", { target_issue: issueId, next_resolution: resolution, note: note || null }); if (error) throw error; return data; }
export async function analyseWalkthroughFrames(scanId: string, frames: Array<{ frameIndex: number; dataUrl: string }>) { const extra = Constants.expoConfig?.extra as { EXPO_PUBLIC_APP_URL?: string } | undefined; const baseUrl = extra?.EXPO_PUBLIC_APP_URL || process.env.EXPO_PUBLIC_APP_URL || "http://10.0.2.2:3000"; walkthroughDebug("auth_session_start"); const { data: { session }, error: sessionError } = await supabase.auth.getSession(); if (sessionError) { walkthroughDebug("auth_session_failed", safeWalkthroughError(sessionError)); throw new Error("walkthrough_auth_session_failed"); } if (!session?.access_token) { const error = new Error("walkthrough_auth_missing"); walkthroughDebug("auth_session_failed", safeWalkthroughError(error)); throw error; } walkthroughDebug("auth_session_ready"); const url = `${baseUrl}/api/cleaner/walkthrough/analyse`; walkthroughDebug("analysis_request_start", { url, method: "POST" }); let response: Response; try { response = await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ scanId, frames }) }); } catch (error) { walkthroughDebug("analysis_request_failed", safeWalkthroughError(error)); throw error; } let body: { error?: string; framesChecked?: number }; try { body = await response.json() as { error?: string; framesChecked?: number }; } catch (error) { walkthroughDebug("analysis_response_invalid", { status: response.status, ...safeWalkthroughError(error) }); throw new Error(`walkthrough_analysis_response_invalid_${response.status}`); } walkthroughDebug("analysis_response", { status: response.status, ...(body.error ? { errorCode: body.error } : {}) }); if (!response.ok) { const error = new Error(body.error || "walkthrough_analysis_failed") as Error & { walkthroughStage?: string }; error.walkthroughStage = "analysis_response"; throw error; } return body; }
export async function getCleanerReports() { const { data, error } = await supabase.from("work_item_completion_reports").select("id,work_item_id,report_reference,report_data,created_at").order("created_at", { ascending: false }); if (error) throw error; return (data || []) as CleanerReport[]; }
export async function getCleanerReport(id: string) { const { data, error } = await supabase.from("work_item_completion_reports").select("id,work_item_id,report_reference,report_data,created_at").eq("id", id).maybeSingle(); if (error) throw error; return data as CleanerReport | null; }
export async function getReportEvidenceUrls(paths: string[]) { if (!paths.length) return []; const { data, error } = await supabase.storage.from("turnover-evidence").createSignedUrls(paths, 600); if (error) throw error; return data || []; }
export async function createHostInvitation(name: string, email?: string, phone?: string) { const { data, error } = await supabase.rpc("create_cleaner_host_invitation", { invitation_name: name, invitation_email: email || null, invitation_phone: phone || null }); if (error) throw error; return Array.isArray(data) ? data[0] : data; }
export async function getCleanerClients() {
  const userId = (await supabase.auth.getUser()).data.user?.id || "";
  const { data: invitations, error: invitationError } = await supabase.from("cleaner_host_invitations").select("id,host_name,host_email,host_phone,status,property_id,created_at").eq("cleaner_user_id", userId).order("created_at", { ascending: false });
  if (invitationError) throw invitationError;
  const { data: properties, error: propertyError } = await supabase.from("properties").select("id,nickname,address_line_1,city,postcode,host_name,host_email,host_phone").eq("standalone_cleaner_user_id", userId).order("created_at", { ascending: false });
  if (propertyError) throw propertyError;
  const { data: jobs, error: jobError } = await supabase.from("work_items").select("id,property_public_name,turnover_date,status,host_name,host_email,host_phone").eq("standalone_cleaner_user_id", userId).order("turnover_date", { ascending: false });
  if (jobError) throw jobError;
  return (invitations || []).map((invitation) => ({ invitation, properties: (properties || []).filter((property) => matchesClient(property, invitation)), jobs: (jobs || []).filter((job) => matchesClient(job, invitation)) }));
}
function matchesClient(value: { host_name?: string | null; host_email?: string | null; host_phone?: string | null }, invitation: { host_name: string; host_email?: string | null; host_phone?: string | null }) {
  return Boolean((invitation.host_email && value.host_email && invitation.host_email.toLowerCase() === value.host_email.toLowerCase()) || (invitation.host_phone && value.host_phone && invitation.host_phone === value.host_phone) || (value.host_name && value.host_name.toLowerCase() === invitation.host_name.toLowerCase()));
}
export async function saveTask(task: ChecklistTask, jobId: string, response: string | null, note: string | null) { const { error } = await supabase.rpc("cleaner_update_checklist_task", { target_task: task.id, target_work_item: jobId, next_response: response, next_note: note }); if (error) throw error; }
export async function uploadEvidence({ job, userId, file, taskId, issueId, type, response, note }: { job: Job; userId: string; file: { uri: string; name: string; type: string; size?: number }; taskId?: string; issueId?: string; type: "completion_photo" | "key_return" | "issue_photo"; response?: string | null; note?: string | null }) {
  if (taskId) {
    const { data: existing, error: existingError } = await supabase.from("evidence_submissions").select("id,work_item_id,checklist_task_id,evidence_type,storage_path").eq("work_item_id", job.id).eq("checklist_task_id", taskId).eq("evidence_type", type).not("storage_path", "is", null).limit(1).maybeSingle();
    if (existingError) throw existingError;
    if (existing) return existing as Evidence;
  }
  const extension = file.name.split(".").pop()?.replace(/[^a-z0-9]/gi, "").toLowerCase() || "jpg";
  const nonce = `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
  const path = `${job.account_id}/${job.id}/${nonce}.${extension}`;
  const fileResponse = await fetch(file.uri); const body = await fileResponse.arrayBuffer();
  const { error: uploadError } = await supabase.storage.from("turnover-evidence").upload(path, body, { contentType: file.type, upsert: false });
  if (uploadError) throw uploadError;
  const { data, error } = await supabase.from("evidence_submissions").insert({ account_id: job.account_id, work_item_id: job.id, checklist_task_id: taskId || null, issue_id: issueId || null, uploader_id: userId, storage_path: path, evidence_type: type }).select("id,work_item_id,checklist_task_id,issue_id,evidence_type,storage_path").single();
  if (error || !data) { await supabase.storage.from("turnover-evidence").remove([path]); throw error || new Error("Evidence was not confirmed"); }
  if (taskId) { const task = (job.checklist_tasks || []).find((item) => item.id === taskId); if (task && !task.completed) await saveTask(task, job.id, response ?? task.response, note ?? task.note); }
  await supabase.rpc("evaluate_work_item_readiness", { target_work_item: job.id });
  return data as Evidence;
}
