export type CleanStatus = "awaiting_response" | "accepted" | "en_route" | "arrived" | "in_progress" | "action_required" | "evidence_submitted" | "ready" | "declined" | "cancelled";
export type WalkthroughIssue = { id: string; scan_id: string; work_item_id: string; frame_index: number; frame_storage_path?: string | null; category: string; confidence: "low" | "medium" | "high"; description: string; resolution_status: "unresolved" | "fixed" | "not_an_issue"; resolution_note?: string | null };
export type WalkthroughScan = { id: string; work_item_id: string; status: "recording" | "uploading" | "processing" | "review_required" | "resolved" | "completed" | "failed"; source_storage_path?: string | null; frame_count: number; issue_count: number; resolved_issue_count: number; provider?: string | null; model?: string | null; error_message?: string | null; created_at: string; completed_at?: string | null; issues: WalkthroughIssue[] };

export type Worker = { id: string; display_name: string; email: string | null; mobile: string | null; status: string; invitation_status: string; account_id: string };
export type StandaloneCleaner = { user_id: string; role: "cleaner"; display_name: string; business_name: string | null; service_area: string | null; onboarding_completed_at: string | null; interested_in_marketplace_work: boolean; workspace_account_id?: string | null };
export type Property = { nickname: string | null; address_line_1?: string | null; city?: string | null; postcode?: string | null; bedrooms?: number | null; bathrooms?: number | null; access_notes?: string | null; key_instructions?: string | null; key_return_instructions?: string | null; parking_notes?: string | null; floor_lift_notes?: string | null; cleaning_notes?: string | null; linen_requirements?: string | null; towel_requirements?: string | null; bed_configuration?: string | null; consumables_instructions?: string | null; waste_instructions?: string | null };
export type CleanerProperty = Property & { id: string; host_name?: string | null; host_email?: string | null; host_phone?: string | null; internal_notes?: string | null };
export type Assignment = { worker_id: string; status: "pending" | "accepted" | "declined" | "cancelled" };
export type ChecklistTask = { id: string; section_title: string; label: string; description: string | null; mandatory: boolean; blocking: boolean; completed: boolean; response_type: "checkbox" | "yes_no" | "pass_fail"; response: string | null; photo_required: boolean; note_required: boolean; note: string | null };
export type Evidence = { id: string; work_item_id: string; checklist_task_id: string | null; issue_id?: string | null; evidence_type: string; storage_path: string };
export type Job = { id: string; account_id: string; property_public_name: string; property_general_area: string; cleaning_type: string; turnover_date: string; access_start_at: string; next_checkin_at: string; window_end_at?: string; status: CleanStatus; required_evidence_count: number; host_name?: string | null; host_email?: string | null; host_phone?: string | null; standalone_cleaner_user_id?: string | null; properties: Property | Property[] | null; assignments: Assignment | Assignment[] | null; checklist_tasks?: ChecklistTask[]; evidence_submissions?: Evidence[]; operational_issues?: { id: string; status: string; blocking: boolean; issue_type?: string; severity?: string; description?: string }[] };
export type ReportChecklistTask = ChecklistTask & { task_id?: string | null };
export type ReportEvidence = { id?: string; storage_path?: string | null; task_id?: string | null; checklist_task_id?: string | null; evidence_type?: string | null; signedUrl?: string };
export type ReportIssue = { id?: string; title?: string | null; description?: string | null; severity?: string | null; status?: string | null };
export type ReportData = { property_name?: string | null; address?: string | null; cleaner_name?: string | null; cleaning_date?: string | null; cleaning_start?: string | null; cleaning_end?: string | null; completed_at?: string | null; checklist?: ReportChecklistTask[]; evidence?: ReportEvidence[]; issues?: ReportIssue[]; ai_walkthrough?: { status?: string; frames_checked?: number; potential_issues?: number; resolved_issues?: number; completed_at?: string | null } | null };
export type CleanerReport = { id: string; work_item_id: string; report_reference: string; report_data: ReportData; created_at: string };
export type MarketplaceOpportunity = { id: string; category_slug: string; job_type_slug: string; structured_answers: Record<string, string | number>; postcode_district: string; requested_timing: string | null; optional_note: string | null; photo_count: number; status: string };

export const statusLabel: Record<string, string> = { awaiting_response: "Assigned", accepted: "Accepted", en_route: "En route", arrived: "Arrived", in_progress: "Cleaning", action_required: "Action required", evidence_submitted: "Submitted", ready: "Done", declined: "Declined", cancelled: "Cancelled" };
export const primaryAction: Record<string, { label: string; next: string } | undefined> = { awaiting_response: { label: "Accept clean", next: "accepted" }, accepted: { label: "I’m en route", next: "en_route" }, en_route: { label: "I’ve arrived", next: "arrived" }, arrived: { label: "Start cleaning", next: "in_progress" }, in_progress: { label: "Finish clean", next: "evidence_submitted" } };

export function related<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] || null : value || null; }
export function displayName(value: string | null | undefined, fallback = "") { const text = value?.trim(); if (!text || ["null", "undefined", "ma"].includes(text.toLowerCase())) return fallback; return text.split(/\s+/).map((word) => word.length > 1 && word === word.toLowerCase() ? word.replace(/[A-Za-z]+/g, (part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()) : word).join(" "); }
export function addressFor(property: Property | null, fallback: string) { const values = [property?.address_line_1, property?.city, property?.postcode, fallback].map((value) => value?.trim()).filter((value): value is string => Boolean(value && !["null", "undefined", "ma"].includes(value.toLowerCase()))); const unique: string[] = []; values.forEach((value) => { if (!unique.some((item) => item.toLowerCase() === value.toLowerCase())) unique.push(value); }); return unique.slice(0, 3).map((value) => value.split(/\s+/).map((word) => /^[A-Za-z]{1,3}\d/.test(word) ? word.toUpperCase() : word.length > 1 && word === word.toLowerCase() ? word.replace(/[A-Za-z]+/g, (part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()) : word).join(" ")).join(", ") || "Location not provided"; }
export function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)); }
export function formatTime(value: string) { return new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
