import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import MarketplaceHeader from "@/app/components/marketplace/MarketplaceHeader";
import { ACTIVE_PUBLIC_SEO_LOCATIONS, getLocation, getLocationServiceSeo, getService, isActivePublicSeoLocation, marketplaceServices } from "@/app/data/marketplace";

export async function generateMetadata({ params }: { params: Promise<{ service: string; location: string }> }): Promise<Metadata> { const { service: serviceSlug, location: locationSlug } = await params; const service = getService(serviceSlug); const location = getLocation(locationSlug); if (!service || !location) return {}; const seo = getLocationServiceSeo(service, location); return { title: seo.title, description: seo.description, alternates: { canonical: `/services/${service.slug}/${location.slug}` }, robots: isActivePublicSeoLocation(location.slug) ? { index: true, follow: true } : { index: false, follow: true } }; }
export function generateStaticParams() { return marketplaceServices.flatMap((service) => ACTIVE_PUBLIC_SEO_LOCATIONS.map((location) => ({ service: service.slug, location }))); }

export default async function LocalServicePage({ params }: { params: Promise<{ service: string; location: string }> }) { const { service: serviceSlug, location: locationSlug } = await params; const service = getService(serviceSlug); const location = getLocation(locationSlug); if (!service || !location) notFound(); return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><MarketplaceHeader /><div className="mx-auto max-w-[1120px] px-5 py-10 sm:px-8"><nav className="text-sm font-bold text-[#707b8d]" aria-label="Breadcrumb"><Link href="/">Home</Link> <span aria-hidden="true">→</span> <Link href="/services">Services</Link> <span aria-hidden="true">→</span> {service.name} in {location.name}</nav><section className="mt-8 rounded-3xl bg-[#061b3f] px-6 py-12 text-white sm:px-10"><p className="text-xs font-black uppercase tracking-[.16em] text-[#23dc63]">LOCAL SERVICE</p><h1 className="mt-4 text-4xl font-black tracking-[-.06em] sm:text-6xl">{service.name} services in {location.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">Need help with your {service.name.toLowerCase()}? Tell us what needs doing and local professionals can respond.</p><Link href={`/?service=${service.slug}&location=${location.name}#job-composer`} className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-[#23dc63] px-6 font-black text-[#061b3f]">Post a {service.name.toLowerCase()} job</Link></section><section className="grid gap-8 py-12 lg:grid-cols-2"><div><h2 className="text-3xl font-black tracking-[-.04em]">A useful brief starts with the basics.</h2><p className="mt-4 leading-7 text-[#707b8d]">Include the property or job location, what you need done, when it matters and any access details. Photos can help explain the work where appropriate.</p></div><div className="rounded-2xl bg-white p-6 ring-1 ring-[#e9edf1]"><h2 className="text-xl font-black">Related services</h2><div className="mt-4 grid gap-2">{marketplaceServices.filter((item) => item.slug !== service.slug).slice(0, 4).map((item) => <Link key={item.slug} href={`/services/${item.slug}/${location.slug}`} className="font-extrabold text-[#167d3c]">{item.name} in {location.name} →</Link>)}</div></div></section></div></main>; }
