import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import MarketplaceHeader from "@/app/components/marketplace/MarketplaceHeader";
import ServiceLandingPage from "@/app/components/marketplace/ServiceLandingPage";
import { ACTIVE_PUBLIC_SEO_LOCATIONS, getLocation, getLocationServiceSeo, getService, isActivePublicSeoLocation, marketplaceServices } from "@/app/data/marketplace";

export async function generateMetadata({ params }: { params: Promise<{ service: string; location: string }> }): Promise<Metadata> { const { service: serviceSlug, location: locationSlug } = await params; const service = getService(serviceSlug); const location = getLocation(locationSlug); if (!service || !location) return {}; const seo = getLocationServiceSeo(service, location); return { title: seo.title, description: seo.description, alternates: { canonical: `/services/${service.slug}/${location.slug}` }, robots: isActivePublicSeoLocation(location.slug) ? { index: true, follow: true } : { index: false, follow: true } }; }
export function generateStaticParams() { return marketplaceServices.flatMap((service) => ACTIVE_PUBLIC_SEO_LOCATIONS.map((location) => ({ service: service.slug, location }))); }
export default async function LocalServicePage({ params }: { params: Promise<{ service: string; location: string }> }) { const { service: serviceSlug, location: locationSlug } = await params; const service = getService(serviceSlug); const location = getLocation(locationSlug); if (!service || !location) notFound(); return <main className="service-page-content min-h-screen bg-[#f7f8fa] text-[#061b3f]"><MarketplaceHeader /><div className="mx-auto max-w-[1120px] px-5 py-10 sm:px-8"><nav className="text-sm font-bold text-[#707b8d]" aria-label="Breadcrumb"><Link href="/">Home</Link> <span aria-hidden="true">→</span> <Link href="/services">Services</Link> <span aria-hidden="true">→</span> {service.name} in {location.name}</nav></div><ServiceLandingPage service={service} location={location} /></main>; }
