import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import MarketplaceHeader from "@/app/components/marketplace/MarketplaceHeader";
import { getService, marketplaceLocations } from "@/app/data/marketplace";

export async function generateMetadata({ params }: { params: Promise<{ service: string }> }): Promise<Metadata> { const service = getService((await params).service); return service ? { title: service.seoTitle, description: service.seoDescription } : {}; }
export function generateStaticParams() { return ["cleaning", "gardening", "handyman", "furniture-assembly", "plumbing", "electrical", "removals", "waste-removal", "painting", "tv-mounting", "smart-home", "window-cleaning"].map((service) => ({ service })); }

export default async function ServicePage({ params }: { params: Promise<{ service: string }> }) { const service = getService((await params).service); if (!service) notFound(); return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><MarketplaceHeader /><section className="bg-[#061b3f] px-5 py-14 text-white sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[1120px] gap-10 lg:grid-cols-[1fr_260px] lg:items-center"><div><Link href="/services" className="text-sm font-bold text-white/60">← All services</Link><h1 className="mt-5 text-5xl font-black tracking-[-.06em] sm:text-6xl">{service.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">{service.detail}</p><Link href={`/?service=${service.slug}#job-composer`} className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-[#23dc63] px-6 font-black text-[#061b3f]">Get a Quickola estimate</Link></div><div className="grid h-52 place-items-center rounded-3xl bg-white/8 p-10 ring-1 ring-white/10"><Image src={service.image} alt="" width={140} height={140} className="h-full w-full object-contain" /></div></div></section><section className="px-5 py-12 sm:px-8 sm:py-16"><div className="mx-auto max-w-[1120px]"><p className="text-xs font-black uppercase tracking-[.16em] text-[#23a955]">Popular jobs</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">What do you need doing?</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{service.jobs.filter((item) => item.active).map((item) => <Link key={item.slug} href={`/?service=${service.slug}&job=${item.slug}#job-composer`} className="rounded-2xl bg-white p-5 ring-1 ring-[#e9edf1] hover:ring-[#23a955]"><h3 className="font-black">{item.name}</h3><p className="mt-2 text-sm leading-6 text-[#707b8d]">{item.shortDescription}</p><span className="mt-4 block text-sm font-black text-[#167d3c]">Get an estimate →</span></Link>)}</div><aside className="mt-10 rounded-2xl bg-white p-6 ring-1 ring-[#e9edf1]"><h2 className="text-xl font-black">Explore local areas</h2><div className="mt-4 flex flex-wrap gap-2">{marketplaceLocations.slice(0, 3).map((location) => <Link key={location.slug} href={`/services/${service.slug}/${location.slug}`} className="rounded-xl bg-[#eef8f1] px-4 py-3 text-sm font-extrabold text-[#167d3c]">{service.name} in {location.name} →</Link>)}</div></aside></div></section></main>; }
