import Link from "next/link";
import { requireBusinessUser } from "@/lib/business/auth";
import { formatDisplayName } from "@/lib/display-name";
import { currentAssignment } from "@/lib/turnovers/presentation";
import { getOperatorState } from "@/lib/turnovers/operator-lifecycle";
import TurnoverStatus from "../components/TurnoverStatus";

const one = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;
const time = (value: string) => new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(value));
const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short" }).format(new Date(value));
export default async function Page() {
  const { supabase, accountId } = await requireBusinessUser();
  const { data } = await supabase.from("work_items").select("id,property_public_name,turnover_date,guest_checkout_at,next_checkin_at,window_end_at,status,properties(nickname),assignments(status,assigned_at,response_due_at,workers(display_name)),operational_issues(status,blocking)").eq("account_id", accountId).order("access_start_at").limit(250);
  const items = data || []; const active = items.filter((item) => !["ready", "cancelled"].includes(item.status)); const readyToday = items.filter((item) => item.status === "ready" && item.turnover_date === new Date().toISOString().slice(0, 10)); const unassigned = items.filter((item) => item.status === "unassigned"); const openIssues = items.filter((item) => (item.operational_issues || []).some((issue: { status: string }) => !["resolved", "closed"].includes(issue.status))); const declined = items.filter((item) => item.status === "declined"); const attention = [...unassigned, ...openIssues, ...declined].filter((item, index, list) => list.findIndex((candidate) => candidate.id === item.id) === index); const upcoming = active.filter((item) => item.turnover_date >= new Date().toISOString().slice(0, 10)).slice(0, 5); const completed = items.filter((item) => item.status === "ready").slice(0, 5);
  return <div className="portal-page"><header className="portal-header"><div><h1 className="portal-title">Cleaning overview</h1><p className="portal-subtitle">See what needs attention and how each clean is progressing.</p></div><Link href="/business/turnovers/new" className="portal-action">＋ Add clean</Link></header>
    <section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Upcoming", active.length, "/business/turnovers"], ["Needs attention", attention.length, "/business/turnovers?view=attention"], ["Ready today", readyToday.length, "/business/turnovers?view=completed"], ["Unassigned", unassigned.length, "/business/turnovers?view=attention"]].map(([label, value, href]) => <Link key={String(label)} href={String(href)} className="portal-card p-4"><p className="text-xs font-extrabold text-[#657089]">{label}</p><strong className="mt-1 block text-3xl">{value}</strong></Link>)}</section>
    {attention.length > 0 && <section className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-extrabold text-amber-950">Needs attention</h2><div className="mt-3 grid gap-2">{attention.slice(0, 3).map((item) => { const property = one(item.properties); const state = getOperatorState(item.status); const issue = (item.operational_issues || []).find((entry: { status: string }) => !["resolved", "closed"].includes(entry.status)); return <Link href={`/business/turnovers/${item.id}`} key={item.id} className="rounded-lg bg-white p-3"><p className="font-extrabold">{property?.nickname || item.property_public_name} {state.attention}</p><p className="mt-1 text-sm text-[#657089]">{date(item.turnover_date)} · Guest check-in {time(item.next_checkin_at || item.window_end_at)}</p><p className="mt-2 text-sm font-extrabold text-[#16467e]">{item.status === "unassigned" ? "Assign cleaner →" : issue ? `${issue.status === "open" ? "Open issue" : "Issue needs review"} →` : state.message}</p></Link>; })}</div></section>}
    <section className="mt-5 portal-panel"><div className="portal-panel-head"><h2 className="text-lg font-extrabold">Upcoming cleans</h2><Link href="/business/turnovers" className="text-sm font-extrabold text-[#16467e]">View all</Link></div><div className="divide-y">{upcoming.length ? upcoming.map((item) => { const property = one(item.properties); const assignment = currentAssignment(item.assignments); const worker = one(assignment?.workers || null); return <Link href={`/business/turnovers/${item.id}`} key={item.id} className="block p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-extrabold">{property?.nickname || item.property_public_name}</p><p className="mt-1 text-sm text-[#657089]">{date(item.turnover_date)} · Guest check-in {time(item.next_checkin_at || item.window_end_at)}</p></div><TurnoverStatus status={item.status}/></div><p className="mt-2 text-xs font-bold text-[#657089]">{worker?.display_name ? formatDisplayName(worker.display_name) : getOperatorState(item.status).message}</p></Link>; }) : <p className="p-6 text-sm text-[#657089]">No upcoming cleans.</p>}</div></section>
    {completed.length > 0 && <section className="mt-5 portal-panel"><div className="portal-panel-head"><h2 className="text-lg font-extrabold">Recently completed</h2><Link href="/business/turnovers?view=completed" className="text-sm font-extrabold text-[#16467e]">View all</Link></div><div className="divide-y">{completed.map((item) => { const property = one(item.properties); const assignment = currentAssignment(item.assignments); const worker = one(assignment?.workers || null); return <Link href={`/business/turnovers/${item.id}`} key={item.id} className="flex items-center justify-between gap-3 p-4"><span><strong>{property?.nickname || item.property_public_name}</strong><span className="mt-1 block text-sm text-[#657089]">Property ready · {worker?.display_name ? formatDisplayName(worker.display_name) : "Cleaner"}</span></span><TurnoverStatus status="ready"/></Link>; })}</div></section>}
  </div>;
}
