import Link from "next/link";
import MobileBottomNav from "@/app/components/marketplace/MobileBottomNav";

type Conversation = { id: string; job_id: string; provider_id?: string | null; bidder_user_id?: string | null };
type Job = { id: string; service?: string; service_subtype?: string; postcode?: string };
type Profile = { user_id: string; display_name?: string; business_name?: string; profile_photo_url?: string | null };
type Quote = { job_id: string; provider_id?: string | null; bidder_user_id?: string | null; amount_pence: number; status: string };
type Message = { conversation_id: string; body: string; created_at: string; sender_id: string };
type Booking = { conversation_id: string; payment_status?: string | null };

export default function CustomerMessagesList({ conversations, jobs, profiles, quotes, messages, bookings }: { conversations: Conversation[]; jobs: Job[]; profiles: Profile[]; quotes: Quote[]; messages: Message[]; bookings: Booking[] }) {
  const jobsById = new Map(jobs.map((job) => [job.id, job]));
  const profilesById = new Map(profiles.map((profile) => [profile.user_id, profile]));
  const latestByConversation = new Map<string, Message>();
  for (const message of messages) if (!latestByConversation.has(message.conversation_id)) latestByConversation.set(message.conversation_id, message);
  const bookingByConversation = new Map(bookings.map((booking) => [booking.conversation_id, booking]));

  return <main className="min-h-screen bg-[#f7f8fa] text-[#061b3f]"><section className="mx-auto max-w-3xl px-5 pb-[calc(6.5rem+env(safe-area-inset-bottom))] py-10 sm:px-8 md:pb-10"><p className="text-sm font-black uppercase tracking-[.14em] text-[#159548]">MESSAGES</p><h1 className="mt-2 text-4xl font-black">Messages</h1><p className="mt-2 text-[#526078]">Conversations about your Quickola jobs.</p><div className="mt-7 grid gap-3">{conversations.map((conversation) => { const job = jobsById.get(conversation.job_id); const providerId = conversation.provider_id || conversation.bidder_user_id; const profile = providerId ? profilesById.get(providerId) : undefined; const quote = quotes.find((item) => item.job_id === conversation.job_id && (item.provider_id || item.bidder_user_id) === providerId); const latest = latestByConversation.get(conversation.id); const title = (job?.service_subtype || job?.service || "Quickola job").replaceAll("-", " "); const providerName = profile?.business_name || profile?.display_name || "Your provider"; const booked = bookingByConversation.get(conversation.id)?.payment_status === "paid"; return <Link key={conversation.id} href={`/messages/${conversation.id}`} className="group block rounded-2xl border border-[#e7ebef] bg-white p-5 transition hover:border-[#b9d9c2] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#23a955]/30"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#eef8f1] text-lg font-black text-[#167d3c]" aria-hidden="true">{profile?.profile_photo_url ? <img src={profile.profile_photo_url} alt="" className="h-full w-full object-cover" /> : providerName.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-black">{providerName}</h2><p className="mt-1 truncate text-sm font-bold text-[#526078]">{title}{booked ? " · Booked" : ""}{quote ? ` · £${Math.round(quote.amount_pence / 100)}` : ""}</p></div><span aria-hidden="true" className="text-2xl leading-5 text-[#167d3c]">›</span></div><p className="mt-3 line-clamp-2 text-sm text-[#39465b]">{latest?.body || "No messages yet"}</p>{latest?.created_at && <time dateTime={latest.created_at} className="mt-2 block text-xs font-bold text-[#526078]">{new Date(latest.created_at).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}</time>}</div></div></Link>; })}{!conversations.length && <p className="rounded-2xl border border-dashed bg-white p-8 text-[#526078]">No messages yet. When someone contacts you, you’ll see it here.</p>}</div></section><div className="md:hidden"><MobileBottomNav active="messages" /></div></main>;
}
