import { createHash } from "node:crypto";
import { notFound } from "next/navigation";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

function tokenHash(rawToken: string) { return createHash("sha256").update(rawToken).digest("hex"); }
function safeError(error: unknown) { const value = error as { message?: string; code?: string; status?: number }; return { message: value?.message, code: value?.code, status: value?.status }; }

export default async function PublicReport({ params }: { params: Promise<{ token: string }> }) {
  const rawToken = (await params).token.trim();
  if (!rawToken || rawToken.length > 128 || !/^[A-Za-z0-9_-]+$/.test(rawToken)) { console.warn("report_share_invalid_token"); notFound(); }
  const hash = tokenHash(rawToken);
  let admin;
  try { admin = createSupabaseAdminClient(); } catch (error: unknown) { console.error("report_share_lookup_failed", safeError(error)); throw error; }
  const { data: share, error: shareError } = await admin.from("work_item_report_shares").select("report_id,expires_at,revoked_at").eq("token_hash", hash).maybeSingle();
  if (shareError) { console.error("report_share_lookup_failed", { message: shareError.message, code: shareError.code, status: shareError.status }); throw shareError; }
  if (!share) { console.warn("report_share_invalid_token"); notFound(); }
  if (share.revoked_at) { console.warn("report_share_revoked"); notFound(); }
  if (!share.expires_at || new Date(share.expires_at) <= new Date()) { console.warn("report_share_expired"); notFound(); }
  const { data: report, error: reportError } = await admin.from("work_item_completion_reports").select("report_data,created_at").eq("id", share.report_id).maybeSingle();
  if (reportError) { console.error("report_share_lookup_failed", { message: reportError.message, code: reportError.code, status: reportError.status }); throw reportError; }
  if (!report) { console.warn("report_share_invalid_token"); notFound(); }
  const data = report.report_data as { property_name?: string; address?: string; cleaning_date?: string; cleaning_start?: string; cleaning_end?: string; completed_at?: string; cleaner_name?: string; checklist?: Array<{ label?: string; section_title?: string; completed?: boolean }>; evidence?: Array<{ type?: string; storage_path?: string }>; issues?: Array<{ title?: string; description?: string; severity?: string }> };
  const paths = (data.evidence || []).map((item) => item.storage_path).filter((path): path is string => Boolean(path)); const { data: signed, error: signedError } = paths.length ? await admin.storage.from("turnover-evidence").createSignedUrls(paths, 600) : { data: [], error: null }; if (signedError) { console.error("report_share_lookup_failed", { message: signedError.message, code: signedError.name, status: undefined }); throw signedError; }
  const date = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "Not recorded"; const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded";
  return <main className="min-h-screen bg-[#f4f6f9] px-5 py-8 text-[#071638] sm:px-8"><div className="mx-auto max-w-3xl"><header className="mb-5"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#2d67b2]">Quickola</p><h1 className="mt-2 text-3xl font-black">Clean report</h1></header><section className="rounded-2xl bg-white p-6 shadow-sm sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wide text-[#2d67b2]">Property</p><h2 className="mt-2 text-2xl font-black">{data.property_name || "Completed clean"}</h2><p className="mt-2 text-[#657089]">{data.address || ""}</p></div><span className="rounded-full bg-[#e8f7ee] px-3 py-2 text-sm font-black text-[#079448]">Completed ✓</span></div><div className="mt-6 grid gap-2 text-sm text-[#657089] sm:grid-cols-2"><p>Completed date · <b className="text-[#071638]">{date(data.cleaning_date)}</b></p><p>Completed at · <b className="text-[#071638]">{dateTime(data.completed_at)}</b></p><p>Cleaning window · <b className="text-[#071638]">{data.cleaning_start ? new Intl.DateTimeFormat("en-GB", { timeStyle: "short" }).format(new Date(data.cleaning_start)) : "—"} – {data.cleaning_end ? new Intl.DateTimeFormat("en-GB", { timeStyle: "short" }).format(new Date(data.cleaning_end)) : "—"}</b></p><p>Cleaner · <b className="text-[#071638]">{data.cleaner_name || "Cleaner"}</b></p></div><section className="mt-9"><h3 className="text-xl font-black">Checklist completed</h3><div className="mt-3 divide-y">{(data.checklist || []).map((task, index) => <div key={`${task.label}-${index}`} className="flex justify-between gap-4 py-3"><span>{task.label}</span><span className="font-bold text-[#079448]">{task.completed ? "Complete" : "Review"}</span></div>)}</div></section><section className="mt-9"><h3 className="text-xl font-black">Evidence</h3><p className="mt-2 text-sm text-[#657089]">{paths.length} photo{paths.length === 1 ? "" : "s"} submitted.</p><div className="mt-3 grid grid-cols-2 gap-3">{signed?.map((item, index) => item.signedUrl ? <a key={item.path || index} href={item.signedUrl} target="_blank" rel="noreferrer"><img src={item.signedUrl} alt="Completion evidence" className="aspect-[4/3] w-full rounded-xl object-cover" /></a> : null)}</div></section><section className="mt-9"><h3 className="text-xl font-black">Issues</h3>{data.issues?.length ? <div className="mt-3 divide-y">{data.issues.map((issue, index) => <article key={`${issue.title}-${index}`} className="py-3"><div className="flex justify-between gap-4"><b>{issue.title}</b><span className="text-sm font-bold capitalize text-[#657089]">{issue.severity}</span></div><p className="mt-1 text-sm text-[#657089]">{issue.description}</p></article>)}</div> : <p className="mt-2 text-sm text-[#657089]">No issues reported.</p>}</section></section><footer className="py-6 text-center text-sm font-bold text-[#657089]">Completed with Quickola</footer></div></main>;
}

export { tokenHash };
