import { createHash } from "node:crypto";
import { notFound } from "next/navigation";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

function tokenHash(rawToken: string) { return createHash("sha256").update(rawToken).digest("hex"); }
function safeError(error: unknown) { const value = error as { message?: string; code?: string; status?: number }; return { message: value?.message, code: value?.code, status: value?.status }; }
function temporaryServerError() { return <main className="grid min-h-screen place-items-center bg-[#f4f6f9] p-6 text-[#071638]"><section className="max-w-md rounded-2xl bg-white p-7 text-center shadow-sm"><h1 className="text-2xl font-black">Report temporarily unavailable</h1><p className="mt-3 text-[#657089]">We couldn’t load this report right now. Please try again shortly.</p></section></main>; }
function lookupStage(stage: "format" | "hash" | "share_row" | "expiry" | "revocation" | "work_item" | "report_data" | "evidence", success: boolean) { console.log("public_report_lookup_stage", { stage, success }); }
function lookupLog(values: { tokenFormatValid: boolean; shareRowFound: boolean; expired: boolean; revoked: boolean; workItemFound: boolean; workItemCompleted: boolean; reportResolvable: boolean; evidenceCount: number; checklistFound?: boolean; issueCount?: number }) { console.log("public_report_lookup_result", values); }
function lookupFailed(stage: string, error: unknown) { const details = safeError(error); console.error("public_report_lookup_failed", { stage, code: details.code, safeMessage: details.message }); return temporaryServerError(); }

export default async function PublicReport({ params }: { params: Promise<{ token: string }> }) {
  const routeToken = (await params).token;
  const rawToken = typeof routeToken === "string" ? routeToken.trim() : "";
  const tokenFormatValid = Boolean(rawToken) && rawToken.length <= 128 && /^[A-Za-z0-9_-]+$/.test(rawToken); console.log("public_report_route_reached", { tokenPresent: Boolean(rawToken), tokenLength: rawToken.length }); lookupStage("format", tokenFormatValid);
  if (!tokenFormatValid) { lookupLog({ tokenFormatValid: false, shareRowFound: false, expired: false, revoked: false, workItemFound: false, workItemCompleted: false, reportResolvable: false, evidenceCount: 0 }); console.warn("report_share_invalid_token"); notFound(); }
  const hash = tokenHash(rawToken);
  lookupStage("hash", Boolean(hash));
  let admin: ReturnType<typeof createSupabaseAdminClient>;
  try { admin = createSupabaseAdminClient(); } catch (error: unknown) { return lookupFailed("configuration", error); }
  console.log("public_report_server_config", { supabaseUrlConfigured: Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL), serviceRoleConfigured: Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY) });
  const { data: share, error: shareError } = await admin.from("work_item_report_shares").select("report_id,expires_at,revoked_at").eq("token_hash", hash).maybeSingle();
  if (shareError) return lookupFailed("share_lookup", shareError);
  lookupStage("share_row", Boolean(share));
  const expired = Boolean(share?.expires_at && new Date(share.expires_at) <= new Date()); const revoked = Boolean(share?.revoked_at);
  lookupStage("expiry", Boolean(share?.expires_at) && !expired);
  if (!share) { lookupLog({ tokenFormatValid: true, shareRowFound: false, expired: false, revoked: false, workItemFound: false, workItemCompleted: false, reportResolvable: false, evidenceCount: 0 }); console.warn("report_share_invalid_token"); notFound(); }
  lookupStage("revocation", !revoked);
  if (revoked) { lookupLog({ tokenFormatValid: true, shareRowFound: true, expired, revoked: true, workItemFound: false, workItemCompleted: false, reportResolvable: false, evidenceCount: 0 }); console.warn("report_share_revoked"); notFound(); }
  if (!share.expires_at || expired) { lookupLog({ tokenFormatValid: true, shareRowFound: true, expired: true, revoked: false, workItemFound: false, workItemCompleted: false, reportResolvable: false, evidenceCount: 0 }); console.warn("report_share_expired"); notFound(); }
  const { data: report, error: reportError } = await admin.from("work_item_completion_reports").select("work_item_id,report_data,created_at").eq("id", share.report_id).maybeSingle();
  if (reportError) return lookupFailed("report_lookup", reportError);
  lookupStage("report_data", Boolean(report));
  if (!report) { lookupLog({ tokenFormatValid: true, shareRowFound: true, expired: false, revoked: false, workItemFound: false, workItemCompleted: false, reportResolvable: false, evidenceCount: 0 }); console.warn("report_share_invalid_token"); notFound(); }
  const { data: workItem, error: workItemError } = await admin.from("work_items").select("id,status").eq("id", report.work_item_id).maybeSingle();
  if (workItemError) return lookupFailed("work_item_lookup", workItemError);
  const workItemFound = Boolean(workItem); const workItemCompleted = workItem?.status === "ready"; const evidenceCount = Array.isArray((report.report_data as { evidence?: unknown[] } | null)?.evidence) ? ((report.report_data as { evidence: unknown[] }).evidence.length) : 0; const reportResolvable = Boolean(workItemFound && workItemCompleted);
  lookupStage("work_item", reportResolvable); const reportData = (report.report_data || {}) as { checklist?: unknown[]; evidence?: unknown[]; issues?: unknown[] }; lookupLog({ tokenFormatValid: true, shareRowFound: true, expired: false, revoked: false, workItemFound, workItemCompleted, reportResolvable, evidenceCount, checklistFound: Array.isArray(reportData.checklist), issueCount: Array.isArray(reportData.issues) ? reportData.issues.length : 0 });
  if (!reportResolvable) { console.warn("report_share_invalid_token"); notFound(); }
  const data = report.report_data as { property_name?: string; address?: string; cleaning_date?: string; cleaning_start?: string; cleaning_end?: string; completed_at?: string; cleaner_name?: string; checklist?: Array<{ label?: string; section_title?: string; completed?: boolean }>; evidence?: Array<{ type?: string; storage_path?: string }>; issues?: Array<{ title?: string; description?: string; severity?: string }> };
  const paths = (data.evidence || []).map((item) => item.storage_path).filter((path): path is string => Boolean(path)); const signedResult = paths.length ? await admin.storage.from("turnover-evidence").createSignedUrls(paths, 600) : { data: [], error: null }; if (signedResult.error) { lookupStage("evidence", false); const details = safeError(signedResult.error); console.error("public_report_lookup_failed", { stage: "evidence", code: details.code, safeMessage: details.message }); } else lookupStage("evidence", true); const signed = signedResult.data || [];
  const date = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "Not recorded"; const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded";
  return <main className="min-h-screen bg-[#f4f6f9] px-5 py-8 text-[#071638] sm:px-8"><div className="mx-auto max-w-3xl"><header className="mb-5"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#2d67b2]">Quickola</p><h1 className="mt-2 text-3xl font-black">Clean report</h1></header><section className="rounded-2xl bg-white p-6 shadow-sm sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wide text-[#2d67b2]">Property</p><h2 className="mt-2 text-2xl font-black">{data.property_name || "Completed clean"}</h2><p className="mt-2 text-[#657089]">{data.address || ""}</p></div><span className="rounded-full bg-[#e8f7ee] px-3 py-2 text-sm font-black text-[#079448]">Completed ✓</span></div><div className="mt-6 grid gap-2 text-sm text-[#657089] sm:grid-cols-2"><p>Completed date · <b className="text-[#071638]">{date(data.cleaning_date)}</b></p><p>Completed at · <b className="text-[#071638]">{dateTime(data.completed_at)}</b></p><p>Cleaning window · <b className="text-[#071638]">{data.cleaning_start ? new Intl.DateTimeFormat("en-GB", { timeStyle: "short" }).format(new Date(data.cleaning_start)) : "—"} – {data.cleaning_end ? new Intl.DateTimeFormat("en-GB", { timeStyle: "short" }).format(new Date(data.cleaning_end)) : "—"}</b></p><p>Cleaner · <b className="text-[#071638]">{data.cleaner_name || "Cleaner"}</b></p></div><section className="mt-9"><h3 className="text-xl font-black">Checklist completed</h3><div className="mt-3 divide-y">{(data.checklist || []).map((task, index) => <div key={`${task.label}-${index}`} className="flex justify-between gap-4 py-3"><span>{task.label}</span><span className="font-bold text-[#079448]">{task.completed ? "Complete" : "Review"}</span></div>)}</div></section><section className="mt-9"><h3 className="text-xl font-black">Evidence</h3><p className="mt-2 text-sm text-[#657089]">{paths.length} photo{paths.length === 1 ? "" : "s"} submitted.</p><div className="mt-3 grid grid-cols-2 gap-3">{signed?.map((item, index) => item.signedUrl ? <a key={item.path || index} href={item.signedUrl} target="_blank" rel="noreferrer"><img src={item.signedUrl} alt="Completion evidence" className="aspect-[4/3] w-full rounded-xl object-cover" /></a> : null)}</div></section><section className="mt-9"><h3 className="text-xl font-black">Issues</h3>{data.issues?.length ? <div className="mt-3 divide-y">{data.issues.map((issue, index) => <article key={`${issue.title}-${index}`} className="py-3"><div className="flex justify-between gap-4"><b>{issue.title}</b><span className="text-sm font-bold capitalize text-[#657089]">{issue.severity}</span></div><p className="mt-1 text-sm text-[#657089]">{issue.description}</p></article>)}</div> : <p className="mt-2 text-sm text-[#657089]">No issues reported.</p>}</section></section><footer className="py-6 text-center text-sm font-bold text-[#657089]">Completed with Quickola</footer></div></main>;
}

export { tokenHash };
