import { useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, Text, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import * as ImageManipulator from "expo-image-manipulator";
import { colors } from "@/lib/theme";

type File = { uri: string; name: string; type: string; size?: number };
export function EvidencePicker({ onUpload, label = "Add photo", disabled = false }: { onUpload: (file: File) => Promise<void>; label?: string; disabled?: boolean }) {
  const [state, setState] = useState<"idle" | "uploading" | "failed" | "uploaded">("idle"); const [selectedFile, setSelectedFile] = useState<File | null>(null);
  async function upload(file: File) { if (state === "uploading") return; setSelectedFile(file); setState("uploading"); try { await onUpload(file); setState("uploaded"); } catch { setState("failed"); } }
  async function choose(source: "camera" | "library") { if (disabled) return; if (source === "camera") { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert("Camera permission needed", "Allow camera access to capture cleaning evidence."); } const result = source === "camera" ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: 0.82 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.82 }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; try { const resized = await ImageManipulator.manipulateAsync(asset.uri, [{ resize: { width: 1800 } }], { compress: 0.82, format: ImageManipulator.SaveFormat.JPEG }); await upload({ uri: resized.uri, name: `evidence-${Date.now()}.jpg`, type: "image/jpeg" }); } catch { setState("failed"); }
  }
  if (state === "uploading") return <View style={row}>{selectedFile && <Image source={{ uri: selectedFile.uri }} style={thumbnail} />}<ActivityIndicator color={colors.blue} /><Text style={text}>Uploading…</Text></View>;
  if (state === "uploaded" && selectedFile) return <View style={uploadedRow}><Image source={{ uri: selectedFile.uri }} style={thumbnail} /><View style={{ flex: 1 }}><Text style={{ color: colors.green, fontWeight: "800" }}>Photo uploaded ✓</Text><Pressable disabled={disabled} onPress={() => { setState("idle"); setSelectedFile(null); }}><Text style={{ color: colors.blue, fontWeight: "800", marginTop: 5 }}>Replace photo</Text></Pressable></View></View>;
  return <View>{selectedFile && <Image source={{ uri: selectedFile.uri }} style={[thumbnail, { marginBottom: 7 }]} />}{state === "failed" && <Text style={{ color: colors.danger, fontSize: 12, marginBottom: 7 }}>Upload failed. Try again.</Text>}<View style={{ flexDirection: "row", gap: 8 }}><Pressable disabled={disabled} onPress={() => state === "failed" && selectedFile ? void upload(selectedFile) : void choose("camera")} style={[button, disabled && { opacity: 0.5 }]}><Text style={buttonText}>{state === "failed" ? "Try again" : "Take photo"}</Text></Pressable><Pressable disabled={disabled} onPress={() => void choose("library")} style={[button, disabled && { opacity: 0.5 }]}><Text style={buttonText}>Choose from gallery</Text></Pressable></View>{state === "idle" && <Text style={{ color: colors.muted, fontSize: 12, marginTop: 6 }}>{label}</Text>}</View>;
}
const button = { minHeight: 44, borderRadius: 9, borderWidth: 1, borderColor: colors.border, alignItems: "center" as const, justifyContent: "center" as const, paddingHorizontal: 12, flex: 1 }; const buttonText = { color: colors.ink, fontSize: 12, fontWeight: "800" as const }; const row = { minHeight: 54, flexDirection: "row" as const, alignItems: "center" as const, gap: 8 }; const uploadedRow = { minHeight: 60, flexDirection: "row" as const, alignItems: "center" as const, gap: 10 }; const thumbnail = { width: 58, height: 58, borderRadius: 8, backgroundColor: "#edf3fb" }; const text = { color: colors.muted, fontSize: 13, fontWeight: "700" as const };
