import { useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import type { ChecklistTask, Job } from "@/lib/types";
import { colors, spacing, typography } from "@/lib/theme";
import { saveTask, uploadEvidence } from "@/lib/api";
import { EvidencePicker } from "./EvidencePicker";
import { Icon } from "./ui";

export function TaskItem({ task, job, userId }: { task: ChecklistTask; job: Job; userId: string }) {
  const client = useQueryClient(); const evidence = job.evidence_submissions || []; const needsPhoto = task.photo_required || /key.*return/i.test(task.label); const hasEvidence = evidence.some((item) => item.checklist_task_id === task.id && Boolean(item.storage_path)); const [response, setResponse] = useState(task.response || ""); const [note, setNote] = useState(task.note || ""); const [message, setMessage] = useState("");
  const canSave = (task.response_type === "checkbox" || Boolean(response)) && (!task.note_required || Boolean(note.trim())); const mutation = useMutation({ mutationFn: () => saveTask(task, job.id, response || null, note || null), onSuccess: () => { setMessage("Saved"); void client.invalidateQueries({ queryKey: ["job", job.id] }); }, onError: () => setMessage("Could not save. Try again.") }); const complete = task.completed && (!needsPhoto || hasEvidence);
  return <View style={[row, complete && { opacity: 0.58 }]}><View style={{ flexDirection: "row", gap: spacing.sm, flex: 1 }}><View style={[check, { backgroundColor: complete ? colors.green : colors.softBlue }]}><Icon name={complete ? "check" : ""} color={complete ? colors.white : colors.blue} size={16} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.ink, fontSize: 15, fontWeight: complete ? "600" : "800" }}>{task.label}</Text>{task.description && !complete && <Text style={[typography.meta, { marginTop: 3 }]}>{task.description}</Text>}{needsPhoto && <Text style={[typography.caption, { color: hasEvidence ? colors.green : colors.blue, marginTop: 5 }]}>{hasEvidence ? "Photo added" : "Photo required"}</Text>}</View></View>{complete ? <Text style={{ color: colors.green, fontSize: 12, fontWeight: "800" }}>Done</Text> : <View style={{ width: "100%", marginTop: spacing.sm }}>{task.response_type !== "checkbox" && <View style={{ flexDirection: "row", gap: 8, marginBottom: 8 }}>{[task.response_type === "yes_no" ? "yes" : "pass", task.response_type === "yes_no" ? "no" : "fail"].map((option) => <Pressable key={option} onPress={() => setResponse(option)} style={{ flex: 1, minHeight: 40, borderRadius: 9, borderWidth: 1, borderColor: response === option ? colors.blue : colors.border, backgroundColor: response === option ? colors.softBlue : colors.white, alignItems: "center", justifyContent: "center" }}><Text style={{ color: colors.ink, fontWeight: "800", textTransform: "capitalize" }}>{option}</Text></Pressable>)}</View>}{task.note_required && <TextInput value={note} onChangeText={setNote} placeholder="Required note" placeholderTextColor={colors.muted} multiline style={input} />}{needsPhoto && !hasEvidence && <EvidencePicker disabled={!canSave} label={!canSave ? "Select the task result first" : "Add task photo"} onUpload={async (file) => { await uploadEvidence({ job, userId, file, taskId: task.id, type: /key.*return/i.test(task.label) ? "key_return" : "completion_photo", response: response || null, note: note || null }); void client.invalidateQueries({ queryKey: ["job", job.id] }); }} />}{!needsPhoto && <Pressable disabled={!canSave || mutation.isPending} onPress={() => mutation.mutate()} style={[saveButton, (!canSave || mutation.isPending) && { opacity: 0.5 }]}><Text style={{ color: colors.white, fontWeight: "800" }}>{mutation.isPending ? "Saving…" : "Complete task"}</Text></Pressable>}{message && <Text style={{ color: message === "Saved" ? colors.green : colors.danger, fontSize: 12, fontWeight: "700", marginTop: 7 }}>{message}</Text>}</View>}</View>;
}
const row = { paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: "#e8ebee" };
const check = { width: 25, height: 25, borderRadius: 13, alignItems: "center" as const, justifyContent: "center" as const };
const input = { minHeight: 68, borderWidth: 1, borderColor: colors.border, borderRadius: 9, padding: spacing.sm, color: colors.ink, textAlignVertical: "top" as const, marginBottom: spacing.sm, backgroundColor: colors.white };
const saveButton = { minHeight: 44, borderRadius: 10, backgroundColor: colors.navy, alignItems: "center" as const, justifyContent: "center" as const, marginTop: spacing.xs };
