"use client";

import { useMemo, useState } from "react";

const TODAY = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London" }).format(new Date());

export default function BookingDetailsForm({ quote }: { quote: Record<string, string> }) {
  const hours = Number(quote.hours || 2);
  const [name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState("");
  const [date,setDate]=useState(""),[time,setTime]=useState(""),[access,setAccess]=useState("I’ll be home"),[notes,setNotes]=useState("");
  const [status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle"),[error,setError]=useState("");
  const windows=useMemo(()=>hours>5?["8:00am start","9:00am start"]:hours>3?["Morning · 8am start","Afternoon · 1pm start"]:["Morning · 8am–12pm","Afternoon · 12pm–4pm","Evening · 4pm–7pm"],[hours]);

  async function submit(event:React.FormEvent){event.preventDefault();if(status==="sending")return;setError("");if(name.trim().length<2){setError("Enter your full name.");return}if(!/^\S+@\S+\.\S+$/.test(email)){setError("Enter a valid email address.");return}const cleanPhone=phone.replace(/\s/g,"");if(!/^(?:\+44|0)7\d{9}$/.test(cleanPhone)){setError("Enter a valid UK mobile number.");return}if(address.trim().length<8){setError("Enter the full property address.");return}if(!date||date<TODAY||!time){setError("Choose a valid future date and arrival time.");return}setStatus("sending");const serviceDetails={...quote,name,email,address,date,time,access,notes};try{const response=await fetch("/api/cumar-intake",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({service:"cleaner",service_label:quote.service||"Cleaning",postcode:quote.postcode,collection_postcode:quote.postcode,customer_phone:cleanPhone,phone:cleanPhone,quote_amount:Number(quote.price),service_details:serviceDetails,price_inputs:quote,price_confidence:"high",price_driver_summary:`${quote.service} · ${quote.bedrooms} bed · ${quote.bathrooms} bath · ${hours} hours`,quote_stage:"booking_requested",needs_followup:true,source:"quickola_booking",source_page:"/book",provider_lane:"cleaning",clean_type:quote.service,clean_frequency:quote.frequency,job_size:`${quote.bedrooms} bedrooms`,job_risk:"low",website:""})});const contentType=response.headers.get("content-type")||"";if(!contentType.includes("application/json"))throw new Error("Booking service is temporarily unavailable.");const data=await response.json();if(!response.ok)throw new Error(data?.error||"Could not submit booking.");setStatus("sent")}catch(e){setError(e instanceof Error?e.message:"Could not submit booking.");setStatus("error")}}

  if(status==="sent")return <div className="rounded-[20px] bg-[#effaf3] p-7 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#079448] text-xl text-white">✓</span><h2 className="mt-4 text-[26px] font-black">Booking request received.</h2><p className="mt-2 text-[14px] font-semibold text-[#536079]">Quickola will confirm your cleaning team and arrival time shortly.</p></div>;
  return <form onSubmit={submit} noValidate className="mt-7 grid gap-4 sm:grid-cols-2">{[["Full name","text",name,setName],["Email","email",email,setEmail],["Mobile number","tel",phone,setPhone],["Full property address","text",address,setAddress],["Preferred date","date",date,setDate]].map(([label,type,value,setter])=><label key={label as string}><span className="mb-2 block text-[12px] font-black">{label as string} *</span><input required type={type as string} value={value as string} autoComplete={type==="email"?"email":type==="tel"?"tel":label==="Full name"?"name":label==="Full property address"?"street-address":undefined} min={type==="date"?TODAY:undefined} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="h-12 w-full rounded-xl border border-[#dce4ed] px-3 outline-none focus:border-[#079448]"/></label>)}<label><span className="mb-2 block text-[12px] font-black">Arrival time *</span><select required value={time} onChange={e=>setTime(e.target.value)} className="h-12 w-full rounded-xl border border-[#dce4ed] px-3"><option value="">Choose a time</option>{windows.map(x=><option key={x}>{x}</option>)}</select><span className="mt-1 block text-[10px] font-bold text-[#7a8598]">Options shown fit your {hours}-hour clean.</span></label><label><span className="mb-2 block text-[12px] font-black">Access</span><select value={access} onChange={e=>setAccess(e.target.value)} className="h-12 w-full rounded-xl border border-[#dce4ed] px-3"><option>I’ll be home</option><option>Key left securely</option><option>Key safe</option><option>Concierge / agent</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-[12px] font-black">Priorities or arrival notes</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="e.g. focus on kitchen first, key safe details…" className="w-full rounded-xl border border-[#dce4ed] p-3" rows={3}/></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-[12px] font-black text-red-700 sm:col-span-2">{error}</p>}<button disabled={status==="sending"} className="h-13 rounded-xl bg-[#079448] px-6 text-[14px] font-black text-white disabled:opacity-50 sm:col-span-2">{status==="sending"?"Booking…":"Book cleaning →"}</button></form>;
}
