import Link from "next/link";
import { requireBusinessUser } from "@/lib/business/auth";

export default async function Page() {
  const { supabase, accountId } = await requireBusinessUser();
  await supabase.rpc("expire_worker_invitations", { target_account: accountId });
  const { data } = await supabase.from("workers").select("id,display_name,company_name,email,mobile,preferred_contact_method,invitation_status,status,assignments(id,status,work_items(turnover_date,status))").eq("account_id", accountId).order("display_name");
  return <div className="mx-auto max-w-6xl"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-extrabold text-[#2d67b2]">YOUR CONTACTS</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">Cleaners</h1><p className="mt-2 text-[#657089]">Invite the cleaners and cleaning contractors you already use.</p></div><Link href="/business/cleaners/new" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#071f49] px-5 font-extrabold text-white">Add cleaner</Link></header>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data?.length ? data.map(worker => <Link key={worker.id} href={`/business/cleaners/${worker.id}`} className="rounded-xl border border-[#dfe4eb] bg-white p-5 outline-none hover:border-[#9aacc4] focus-visible:ring-4 focus-visible:ring-[#2d67b2]/20"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#e9eff8] font-extrabold text-[#16467e]">{worker.display_name.charAt(0).toUpperCase()}</span><span className="rounded-full border bg-[#f8fafc] px-2.5 py-1 text-xs font-extrabold capitalize">{worker.invitation_status.replaceAll("_"," ")}</span></div><h2 className="mt-4 text-lg font-extrabold">{worker.display_name}</h2><p className="text-sm text-[#657089]">{worker.company_name || "Independent cleaner"}</p><p className="mt-4 text-sm font-bold">{worker.email || worker.mobile}</p><p className="mt-1 text-xs text-[#748096]">Prefers {worker.preferred_contact_method}</p></Link>) : <div className="col-span-full rounded-xl border bg-white p-10 text-center"><h2 className="text-xl font-extrabold">No cleaners added</h2><p className="mt-2 text-[#657089]">Invite the cleaner or contractor you already work with.</p><Link href="/business/cleaners/new" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-[#071f49] px-5 font-bold text-white">Add cleaner</Link></div>}</div>
  </div>;
}
