import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function MarketplaceBookingsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireAdmin(); const query = await searchParams; const db = createSupabaseAdminClient();
  const { data: bookings } = await db.from("marketplace_bookings").select("id,job_id,customer_id,provider_id,amount_pence,status,payment_status,created_at,marketplace_jobs(id,service,service_subtype,postcode),marketplace_customers(id,display_name,email),cleaner_profiles(user_id,display_name,business_name)").order("created_at", { ascending: false }).limit(100);
  const rows = (bookings || []).filter((booking) => !query.status || booking.status === query.status);
  const money = (value: number | null) => value == null ? "Awaiting price" : `£${(Number(value) / 100).toFixed(2).replace(/\.00$/, "")}`;
  return <div className="mx-auto max-w-[1380px]"><p className="text-sm font-black uppercase tracking-[.12em] text-[#159548]">OPERATIONS</p><h1 className="mt-1 text-3xl font-black">Marketplace bookings</h1><p className="mt-1 text-[#657089]">Bookings created from accepted marketplace offers.</p><div className="mt-5 flex flex-wrap gap-2">{["", "awaiting_booking_fee", "booked", "en_route", "arrived", "in_progress", "awaiting_customer_completion", "completed", "cancelled"].map((status) => <Link key={status || "all"} href={status ? `/admin/marketplace-bookings?status=${status}` : "/admin/marketplace-bookings"} className="rounded-full border bg-white px-3 py-2 text-sm font-black capitalize">{status ? status.replaceAll("_", " ") : "All"}</Link>)}</div><div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="border-b bg-[#f7f8fa] text-xs uppercase tracking-wide text-[#657089]"><tr><th className="p-4">Job</th><th className="p-4">Customer</th><th className="p-4">Provider</th><th className="p-4">Agreed price</th><th className="p-4">Payment</th><th className="p-4">Booking status</th><th className="p-4">Created</th></tr></thead><tbody>{rows.map((booking) => { const job = Array.isArray(booking.marketplace_jobs) ? booking.marketplace_jobs[0] : booking.marketplace_jobs; const customer = Array.isArray(booking.marketplace_customers) ? booking.marketplace_customers[0] : booking.marketplace_customers; const provider = Array.isArray(booking.cleaner_profiles) ? booking.cleaner_profiles[0] : booking.cleaner_profiles; return <tr key={booking.id} className="border-b last:border-0"><td className="p-4"><Link href={`/admin/marketplace-bookings/${booking.id}`} className="font-black text-[#167d3c]">{job?.service_subtype || job?.service || "Marketplace job"}</Link><p className="text-xs text-[#657089]">{job?.postcode || "No postcode"}</p></td><td className="p-4">{customer?.display_name || customer?.email || "Customer"}</td><td className="p-4">{provider?.display_name || provider?.business_name || "Provider"}</td><td className="p-4 font-black">{money(booking.amount_pence)}</td><td className="p-4 capitalize">{booking.payment_status.replaceAll("_", " ")}</td><td className="p-4 capitalize">{booking.status.replaceAll("_", " ")}</td><td className="p-4">{new Date(booking.created_at).toLocaleString("en-GB")}</td></tr>})}</tbody></table>{!rows.length && <p className="p-8 text-center text-[#657089]">No marketplace bookings match this filter.</p>}</div></div>;
}
