import Stripe from "stripe";
import { getSandboxContext, assertExecutionAllowed, SANDBOX_FIXTURE_EMAILS, SANDBOX_MARKER } from "./sandbox-guard.ts";
import { ScenarioManifest } from "./scenario-manifest.ts";
import { signInSandboxActor, assertFixtureUserIds } from "./sandbox-auth.ts";

const scenarios = ["normal-successful-booking", "job-review-email", "customer-dispute-provider-resolution", "customer-dispute-refund-resolution", "customer-cancellation", "provider-cancellation-policy", "admin-cancellation", "pre-payment-cancellation", "duplicate-webhook", "duplicate-payment-success", "duplicate-transfer", "ambiguous-transfer-recovery", "payout-blocking-matrix", "review-security", "offer-security", "conversation-security", "refund-bounds", "authorization-matrix"] as const;
const requested = process.argv.find((value, index) => process.argv[index - 1] === "--scenario");
const fail = (message: string): never => { throw new Error(`[sandbox] ${message}`); };
const check = (step: string, ok: boolean, detail = "") => { if (!ok) fail(`${step}: ${detail || "assertion failed"}`); console.log(`[normal] ${step} PASS`); };
async function row(admin: ReturnType<typeof getSandboxContext>["admin"], table: string, id: string) { const result = await admin.from(table).select("*").eq("id", id).maybeSingle(); if (result.error || !result.data) fail(`assertion lookup failed for ${table}/${id}`); return result.data; }
async function dispatchEmail(client: { auth: { getSession: () => Promise<{ data: { session: { access_token: string } | null } }> } }, event: string, payload: Record<string, string>) { const sessionResult = await client.auth.getSession(); const accessToken = sessionResult.data.session?.access_token; if (!accessToken) fail("sandbox email dispatch: actor session missing"); const response = await fetch(process.env.SANDBOX_EMAIL_DISPATCH_URL || "http://127.0.0.1:3109/api/sandbox/marketplace-email", { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ event, ...payload }) }); const result = await response.json().catch(() => ({})); if (!response.ok) fail(`sandbox email dispatch ${event}: ${JSON.stringify(result)}`); return result as { status?: string; reason?: string; providerMessageId?: string | null };
}

async function runNormal(options: { scenarioName?: string; attemptPayout?: boolean } = {}) {
  const scenarioName = options.scenarioName || "normal";
  const attemptPayout = options.attemptPayout !== false;
  const context = getSandboxContext({ requireProductionOverride: true }); assertExecutionAllowed();
  const users = await context.admin.auth.admin.listUsers({ page: 1, perPage: 100 }); if (users.error) fail("fixture identity lookup failed");
  const found = Object.values(SANDBOX_FIXTURE_EMAILS).map((email) => users.data.users.find((user) => user.email?.toLowerCase() === email)); if (found.some((user) => !user)) fail("all exact sandbox users must exist");
  const ids = { customer: found[0]!.id, provider: found[1]!.id, admin: found[2]!.id }; const fixturePassword: string = process.env.SANDBOX_FIXTURE_PASSWORD?.trim() || fail("SANDBOX_FIXTURE_PASSWORD is required");
  const actors = await Promise.all(([
    ["customer", ids.customer], ["provider", ids.provider], ["admin", ids.admin],
  ] as const).map(async ([actor]) => signInSandboxActor(actor, fixturePassword)));
  assertFixtureUserIds(actors, ids); const customer = actors[0].client; const provider = actors[1].client; const runId = crypto.randomUUID(); const manifest = new ScenarioManifest(runId); const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!); const stripeObjects: string[] = [];
  console.log(JSON.stringify({ sandbox: true, mode: "execute", supabaseHost: context.supabaseHost, ...ids, scenarioRunId: runId, stripeTestMode: true, connectedAccountSuffix: (process.env.SANDBOX_STRIPE_CONNECTED_ACCOUNT_ID || "").slice(-4) }));
  try {
    const customerRow = await context.admin.from("marketplace_customers").select("id").eq("auth_user_id", ids.customer).maybeSingle(); const customerRecord = customerRow.data; if (customerRow.error || !customerRecord) fail("sandbox customer row missing"); const customerId = customerRecord!.id;
    const job = await context.admin.from("marketplace_jobs").insert({ service: "cleaning", service_subtype: "pressure-washing", postcode: "SL6 5RF", requested_timing: "Sandbox scenario", optional_note: `${SANDBOX_MARKER} ${runId}`, contact_method: "email", contact_value: SANDBOX_FIXTURE_EMAILS.customer, customer_id: customerId, status: "posted" }).select("id,public_token").single(); const createdJob = job.data!; if (job.error || !createdJob) fail(`create job: ${job.error?.message}`); manifest.add("marketplace_jobs", createdJob.id); check("create job", true);
    const providerProfile = await context.admin.from("marketplace_providers").select("user_id,provider_status,marketplace_active").eq("user_id", ids.provider).maybeSingle(); const providerServices = await context.admin.from("marketplace_provider_services").select("provider_id,active").eq("provider_id", ids.provider).eq("active", true); const providerAreas = await context.admin.from("marketplace_provider_service_areas").select("provider_id,active").eq("provider_id", ids.provider).eq("active", true); check("provider eligibility", providerProfile.data?.provider_status === "approved" && providerProfile.data.marketplace_active === true && (providerServices.data?.length || 0) > 0 && (providerAreas.data?.length || 0) > 0);
    const adminJob = await context.admin.from("marketplace_jobs").select("id,customer_id,status").eq("id", createdJob.id).maybeSingle(); const adminJobRow = adminJob.data; check("admin job visibility", adminJobRow?.id === createdJob.id && adminJobRow?.customer_id === customerId && adminJobRow?.status === "posted");
    const offer = await provider.rpc("submit_marketplace_quote", { target_job: createdJob.id, quote_amount: 30000, quote_availability: "flexible", quote_message: `${SANDBOX_MARKER} ${runId}` }); const createdOffer = offer.data; if (offer.error || !createdOffer) fail(`provider offer: ${offer.error?.message}`); manifest.add("marketplace_quotes", createdOffer.id); const offerRow = await row(context.admin, "marketplace_quotes", createdOffer.id); check("provider offer", offerRow.job_id === createdJob.id && (offerRow.provider_id || offerRow.bidder_user_id) === ids.provider && offerRow.amount_pence === 30000 && offerRow.status === "submitted"); const adminOffer = await context.admin.from("marketplace_quotes").select("id,provider_id,bidder_user_id,amount_pence").eq("id", createdOffer.id).maybeSingle(); const adminOfferRow = adminOffer.data; check("admin bid visibility", adminOfferRow?.id === createdOffer.id && (adminOfferRow?.provider_id || adminOfferRow?.bidder_user_id) === ids.provider && adminOfferRow?.amount_pence === 30000); const offerEmail = await dispatchEmail(provider, "offer", { jobId: createdJob.id, quoteId: createdOffer.id }); console.log(JSON.stringify({ emailEvent: "first_offer", result: offerEmail }));
    const selection = await customer.rpc("accept_marketplace_offer", { target_quote: createdOffer.id }); if (selection.error) fail(`customer selection: ${selection.error.message}`); const booking = await context.admin.from("marketplace_bookings").select("id").eq("job_id", createdJob.id).maybeSingle(); const createdBooking = booking.data!; if (booking.error || !createdBooking) fail("selection did not create booking"); manifest.add("marketplace_bookings", createdBooking.id); const pre = await row(context.admin, "marketplace_bookings", createdBooking.id); check("customer selection", pre.provider_id === ids.provider && ["pending_payment", "awaiting_booking_fee"].includes(pre.payment_status));
    const session = await stripe.checkout.sessions.create({ mode: "payment", line_items: [{ price_data: { currency: "gbp", product_data: { name: "Quickola sandbox booking" }, unit_amount: 30000 }, quantity: 1 }], metadata: { booking_id: createdBooking.id, job_id: createdJob.id, quote_id: createdOffer.id, scenario_run_id: runId }, success_url: "http://localhost:3000/sandbox-success", cancel_url: "http://localhost:3000/sandbox-cancel" }, { idempotencyKey: `quickola-sandbox-checkout:${runId}` }); stripeObjects.push(session.id);
    const intent = await stripe.paymentIntents.create({ amount: 30000, currency: "gbp", payment_method: "pm_card_visa", confirm: true, automatic_payment_methods: { enabled: true, allow_redirects: "never" }, metadata: { booking_id: createdBooking.id, scenario_run_id: runId } }); stripeObjects.push(intent.id);
    const paid = await context.admin.from("marketplace_bookings").update({ stripe_checkout_session_id: session.id, stripe_payment_intent_id: intent.id, payment_status: "paid", status: "booked", amount_pence: 30000, currency: "gbp", platform_fee_pence: 3000, paid_at: new Date().toISOString() }).eq("id", createdBooking.id).select("id").single(); if (paid.error) fail(`sandbox payment boundary: ${paid.error.message}`); const paidRow = await row(context.admin, "marketplace_bookings", createdBooking.id); check("payment success", paidRow.payment_status === "paid" && paidRow.status === "booked");
    for (const status of ["en_route", "arrived", "in_progress", "awaiting_customer_completion"]) { const result = await provider.rpc("update_marketplace_booking_status", { target_booking: createdBooking.id, next_status: status }); if (result.error) fail(`provider transition ${status}: ${result.error.message}`); } const awaiting = await row(context.admin, "marketplace_bookings", createdBooking.id); check("provider completion", awaiting.status === "awaiting_customer_completion" && !awaiting.completed_at); check("payout blocked before customer confirmation", !awaiting.stripe_transfer_id); const completionEmail = await dispatchEmail(provider, "provider_completion", { bookingId: createdBooking.id }); console.log(JSON.stringify({ emailEvent: "completion_confirmation_customer", result: completionEmail }));
    const complete = await customer.rpc("confirm_marketplace_completion_with_review", { target_booking: createdBooking.id, review_rating: 5, review_body: `Sandbox review ${runId}` }); if (complete.error) fail(`customer completion: ${complete.error.message}`); const completed = await row(context.admin, "marketplace_bookings", createdBooking.id); const reviews = await context.admin.from("marketplace_reviews").select("id,booking_id,customer_id,provider_id").eq("booking_id", createdBooking.id); const reviewRows = reviews.data || []; if (reviews.error || reviewRows.length !== 1 || !reviewRows[0]) fail("review count is not one"); const reviewRow = reviewRows[0]!; manifest.add("marketplace_reviews", reviewRow.id); check("customer completion + review", completed.status === "completed" && completed.completion_status === "completed" && Boolean(completed.completed_at));
    const providerReviewAggregate = await context.admin.from("marketplace_reviews").select("rating").eq("provider_id", ids.provider); const reviewRatings = providerReviewAggregate.data || []; const reviewAverage = reviewRatings.length ? reviewRatings.reduce((sum, review) => sum + review.rating, 0) / reviewRatings.length : 0; check("provider review aggregate", reviewRatings.length >= 1 && reviewAverage >= 1 && reviewAverage <= 5);
    const adminReview = await context.admin.from("marketplace_reviews").select("id,customer_id,provider_id,booking_id,rating,review_text").eq("id", reviewRow.id).maybeSingle(); const adminReviewRow = adminReview.data; check("admin review visibility", adminReviewRow?.customer_id === customerId && adminReviewRow?.provider_id === ids.provider && adminReviewRow?.booking_id === createdBooking.id && adminReviewRow?.rating === 5 && adminReviewRow?.review_text === `Sandbox review ${runId}`);
    const customerCompletionEmail = await dispatchEmail(customer, "customer_completion", { bookingId: createdBooking.id }); console.log(JSON.stringify({ emailEvent: "completion_confirmed_provider", result: customerCompletionEmail })); const [emailJobRows, emailBookingRows] = await Promise.all([context.admin.from("marketplace_email_notifications").select("id,event_type,recipient_email,status,error_text").eq("job_id", createdJob.id), context.admin.from("marketplace_email_notifications").select("id,event_type,recipient_email,status,error_text").eq("booking_id", createdBooking.id)]); if (emailJobRows.error || emailBookingRows.error) fail(`email audit lookup: ${emailJobRows.error?.message || emailBookingRows.error?.message}`); const emailEvents = Array.from(new Map([...(emailJobRows.data || []), ...(emailBookingRows.data || [])].map((event) => [event.id, event])).values()); console.log(JSON.stringify({ emailEvents, note: "Email dispatches use the existing production transactional functions through the sandbox-only authenticated adapter." })); if (!attemptPayout && emailEvents.length < 3) fail("email events: expected offer and completion notification audit rows were not created");
    if (attemptPayout) { const transfer = await stripe.transfers.create({ amount: 27000, currency: "gbp", destination: process.env.SANDBOX_STRIPE_CONNECTED_ACCOUNT_ID!, transfer_group: `marketplace_booking:${createdBooking.id}`, metadata: { booking_id: createdBooking.id, scenario_run_id: runId } }, { idempotencyKey: `marketplace-provider-transfer:${createdBooking.id}` }); stripeObjects.push(transfer.id); const second = await stripe.transfers.create({ amount: 27000, currency: "gbp", destination: process.env.SANDBOX_STRIPE_CONNECTED_ACCOUNT_ID!, transfer_group: `marketplace_booking:${createdBooking.id}`, metadata: { booking_id: createdBooking.id, scenario_run_id: runId } }, { idempotencyKey: `marketplace-provider-transfer:${createdBooking.id}` }); check("duplicate payout protection", second.id === transfer.id); } else check("no payout attempted", stripeObjects.every((objectId) => !objectId.startsWith("tr_"))); console.log(JSON.stringify({ stripeTestObjects: stripeObjects }));
    const cleanup = await manifest.cleanup(context.admin); check("cleanup", cleanup.retained.length === 0, JSON.stringify(cleanup.retained)); console.log("Scenario | PASS | DB assertions complete | Stripe assertions complete | Cleanup exact manifest IDs");
  } catch (error) { const cleanup = await manifest.cleanup(context.admin); console.error(JSON.stringify({ scenario: scenarioName, result: "FAIL", cleanup, stripeTestObjectsRetained: stripeObjects })); throw error; }
}
try { const context = getSandboxContext({ requireProductionOverride: true }); if (!process.argv.includes("--execute")) console.log(JSON.stringify({ sandbox: true, mode: "dry-run", supabaseHost: context.supabaseHost, scenarioCount: scenarios.length, scenarios, writes: false })); else if (requested === "job-review-email") await runNormal({ scenarioName: "job-review-email", attemptPayout: false }); else if (requested && requested !== "normal") fail("only --scenario normal and --scenario job-review-email are implemented"); else await runNormal(); } catch (error) { console.error(error instanceof Error ? error.message : "scenario command failed"); process.exitCode = 1; }
