"use client";

import { useState } from "react";
import { cancelCustomerMarketplaceJob, updateCustomerMarketplaceJob } from "@/app/jobs/actions";

export default function CustomerJobManageMenu({ token, canManage, note, timing, budget }: { token: string; canManage: boolean; note: string | null; timing: string | null; budget: number | null }) {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState(false);
  if (!canManage) return null;
  return <div className="relative mt-7 border-t border-[#e9edf1] pt-5"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} className="min-h-11 rounded-xl border border-[#dbe1ea] px-4 text-sm font-black text-[#061b3f] hover:bg-[#f7f9fb] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#23a955]/30">Manage job</button>{open && <div className="mt-3 rounded-2xl border border-[#e7ebef] bg-[#fbfcfd] p-4"><button type="button" onClick={() => setEditing((value) => !value)} className="block min-h-10 w-full rounded-lg px-3 text-left text-sm font-black hover:bg-white">Edit job</button>{editing && <form action={updateCustomerMarketplaceJob} className="mt-3 grid gap-3 border-t border-[#e7ebef] pt-3"><input type="hidden" name="token" value={token} /><label className="text-sm font-bold">Details<textarea name="optionalNote" defaultValue={note || ""} maxLength={4000} className="mt-1 min-h-20 w-full rounded-lg border border-[#dbe1ea] bg-white p-2 text-sm" /></label><label className="text-sm font-bold">Timing<input name="requestedTiming" defaultValue={timing || ""} maxLength={160} className="mt-1 min-h-10 w-full rounded-lg border border-[#dbe1ea] bg-white px-2 text-sm" /></label><label className="text-sm font-bold">Budget (£)<input name="budgetAmount" type="number" min="0" step="0.01" defaultValue={budget ?? ""} className="mt-1 min-h-10 w-full rounded-lg border border-[#dbe1ea] bg-white px-2 text-sm" /></label><button className="min-h-10 rounded-lg bg-[#061b3f] px-3 text-sm font-black text-white">Save changes</button></form>}<form action={cancelCustomerMarketplaceJob} onSubmit={(event) => { if (!window.confirm("Cancel this job? It will no longer be available to providers.")) event.preventDefault(); }} className="mt-2 border-t border-[#e7ebef] pt-2"><input type="hidden" name="token" value={token} /><button className="min-h-10 w-full rounded-lg px-3 text-left text-sm font-black text-red-700 hover:bg-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-red-200">Cancel job</button></form></div>}</div>;
}
